# Generated by Django 5.2.6 on 2025-10-30 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailtemplates", "0002_add_callback_data"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailsendjob",
            new_name="mailtemplat_created_992fa7_idx",
            old_name="mailtemplat_created_62c62e_idx",
        ),
        migrations.RenameIndex(
            model_name="emailsendjob",
            new_name="mailtemplat_status_4d61bf_idx",
            old_name="mailtemplat_status_24d393_idx",
        ),
        migrations.RenameIndex(
            model_name="emailsendjob",
            new_name="mailtemplat_created_c4af7a_idx",
            old_name="mailtemplat_created_76c21e_idx",
        ),
        migrations.RenameIndex(
            model_name="emailsendrecipient",
            new_name="mailtemplat_job_id_2c3d3d_idx",
            old_name="mailtemplat_job_id_66e1a8_idx",
        ),
        migrations.RenameIndex(
            model_name="emailsendrecipient",
            new_name="mailtemplat_job_id_d242a8_idx",
            old_name="mailtemplat_job_id_4b831e_idx",
        ),
        migrations.RenameIndex(
            model_name="emailsendrecipient",
            new_name="mailtemplat_email_4b63bb_idx",
            old_name="mailtemplat_email_e69d5d_idx",
        ),
    ]
