# COMMON
ENVIRONMENT=local
DEBUG=true
LOG_LEVEL=ERROR
SECRET_KEY=YOUR_SECRET_KEY
DATABASE_URL=postgres://backend:password@localhost:5432/backend
ALLOWED_HOSTS=localhost,127.0.0.1
CSRF_TRUSTED_ORIGINS=
CORS_ALLOWED_ORIGINS=
CORS_ALLOWED_ORIGIN_REGEXES=

ACCESS_TOKEN_LIFETIME=86400
REFRESH_TOKEN_LIFETIME=2592000

# SENTRY
SENTRY_DSN=YOUR_SENTRY_DSN
SENTRY_ENVIRONMENT=prod
SENTRY_TRACES_SAMPLE_RATE=0.3
SENTRY_SAMPLE_RATE=0.5

# CELERY
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_TASK_ALWAYS_EAGER=True
CELERY_TASK_EAGER_PROPAGATES=True

# CACHE
CACHE_URL=redis://localhost:6379/0
CACHE_PREFIX=
CACHE_TIMEOUT=2592000

# AWS
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_STORAGE_BUCKET_NAME=
AWS_REGION_NAME=
