# Generated by Django 5.2.6 on 2025-09-28 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Tên chi nhánh"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Mã chi nhánh"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Địa chỉ")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, verbose_name="Số điện thoại"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
            ],
            options={
                "verbose_name": "Chi nhánh",
                "verbose_name_plural": "Chi nhánh",
                "db_table": "hrm_branch",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Tên chức vụ")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Mã chức vụ"),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Tổng Giám đốc (TGD)"),
                            (2, "Giám đốc khối"),
                            (3, "Phó Giám đốc khối"),
                            (4, "Trưởng phòng"),
                            (5, "Phó Trưởng phòng"),
                            (6, "Giám sát"),
                            (7, "Nhân viên"),
                            (8, "Thực tập sinh"),
                        ],
                        verbose_name="Cấp bậc",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
            ],
            options={
                "verbose_name": "Chức vụ",
                "verbose_name_plural": "Chức vụ",
                "db_table": "hrm_position",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Tên khối")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Mã khối"),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("support", "Khối hỗ trợ"),
                            ("business", "Khối kinh doanh"),
                        ],
                        max_length=20,
                        verbose_name="Loại khối",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="hrm.branch",
                        verbose_name="Chi nhánh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khối",
                "verbose_name_plural": "Khối",
                "db_table": "hrm_block",
                "unique_together": {("code", "branch")},
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Tên phòng ban"),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Mã phòng ban")),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("business", "Kinh doanh"),
                            ("hr_admin", "Hành chính Nhân sự"),
                            ("recruit_training", "Tuyển dụng - Đào tạo"),
                            ("marketing", "Marketing"),
                            ("business_secretary", "Thư ký Kinh doanh"),
                            ("accounting", "Kế toán"),
                            ("trading_floor", "Sàn liên kết"),
                            ("project_promotion", "Xúc tiến Dự án"),
                            ("project_development", "Phát triển Dự án"),
                        ],
                        default="business",
                        max_length=50,
                        verbose_name="Chức năng phòng ban",
                    ),
                ),
                (
                    "is_main_department",
                    models.BooleanField(default=False, verbose_name="Phòng ban đầu mối"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="hrm.block",
                        verbose_name="Khối",
                    ),
                ),
                (
                    "management_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to="hrm.department",
                        verbose_name="Phòng ban quản lý",
                    ),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_departments",
                        to="hrm.department",
                        verbose_name="Phòng ban cha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phòng ban",
                "verbose_name_plural": "Phòng ban",
                "db_table": "hrm_department",
                "unique_together": {("code", "block")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(verbose_name="Ngày bắt đầu")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Ngày kết thúc"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=True, verbose_name="Chức vụ chính"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_positions",
                        to="hrm.department",
                        verbose_name="Phòng ban",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_positions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nhân viên",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_positions",
                        to="hrm.position",
                        verbose_name="Chức vụ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sơ đồ tổ chức",
                "verbose_name_plural": "Sơ đồ tổ chức",
                "db_table": "hrm_organization_chart",
                "unique_together": {("employee", "position", "department", "start_date")},
            },
        ),
    ]
