# Generated by Django 5.2.6 on 2026-01-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recruitmentcandidate",
            name="unique_citizen_id_when_not_null",
        ),
        migrations.AddConstraint(
            model_name="recruitmentcandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("citizen_id__isnull", False), models.Q(("citizen_id", ""), _negated=True)),
                fields=("citizen_id",),
                name="unique_citizen_id_when_not_null",
            ),
        ),
    ]
