# Generated by Django 5.2.6 on 2025-12-11 04:20

from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="timesheet_entry_complaint_complaint_date",
            field=models.DateField(blank=True, null=True, verbose_name="Timesheet Entry Complaint date"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="timesheet_entry_complaint_approved_check_in_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Timesheet Entry Complaint Approved check-in time"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="timesheet_entry_complaint_approved_check_out_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Timesheet Entry Complaint Approved check-out time"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="timesheet_entry_complaint_complaint_reason",
            field=libs.models.fields.SafeTextField(
                blank=True, null=True, verbose_name="Timesheet Entry Complaint Complaint reason"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="timesheet_entry_complaint_proposed_check_in_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Timesheet Entry Complaint Proposed check-in time"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="timesheet_entry_complaint_proposed_check_out_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Timesheet Entry Complaint Proposed check-out time"
            ),
        ),
    ]
