# Generated by Django 5.2.6 on 2025-10-03 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0002_alter_block_id_alter_branch_id_alter_department_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={"verbose_name": "Block", "verbose_name_plural": "Blocks"},
        ),
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name": "Branch", "verbose_name_plural": "Branches"},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "Department", "verbose_name_plural": "Departments"},
        ),
        migrations.AlterModelOptions(
            name="organizationchart",
            options={"verbose_name": "Organization Chart", "verbose_name_plural": "Organization Charts"},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["level", "name"], "verbose_name": "Position", "verbose_name_plural": "Positions"},
        ),
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[("support", "Support Block"), ("business", "Business Block")],
                max_length=20,
                verbose_name="Block type",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="hrm.branch",
                verbose_name="Branch",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Block code"),
        ),
        migrations.AlterField(
            model_name="block",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="block",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="block",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Block name"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Branch code"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Branch name"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="phone",
            field=models.CharField(blank=True, max_length=15, verbose_name="Phone number"),
        ),
        migrations.AlterField(
            model_name="department",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="hrm.block",
                verbose_name="Block",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=50, verbose_name="Department code"),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="department",
            name="function",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("hr_admin", "HR Administration"),
                    ("recruit_training", "Recruitment & Training"),
                    ("marketing", "Marketing"),
                    ("business_secretary", "Business Secretary"),
                    ("accounting", "Accounting"),
                    ("trading_floor", "Trading Floor"),
                    ("project_promotion", "Project Promotion"),
                    ("project_development", "Project Development"),
                ],
                default="business",
                max_length=50,
                verbose_name="Department function",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_main_department",
            field=models.BooleanField(default=False, verbose_name="Is main department"),
        ),
        migrations.AlterField(
            model_name="department",
            name="management_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="hrm.department",
                verbose_name="Management department",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Department name"),
        ),
        migrations.AlterField(
            model_name="department",
            name="parent_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_departments",
                to="hrm.department",
                verbose_name="Parent department",
            ),
        ),
        migrations.AlterField(
            model_name="organizationchart",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_positions",
                to="hrm.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="organizationchart",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_positions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="organizationchart",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="organizationchart",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="organizationchart",
            name="is_primary",
            field=models.BooleanField(default=True, verbose_name="Is primary position"),
        ),
        migrations.AlterField(
            model_name="organizationchart",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_positions",
                to="hrm.position",
                verbose_name="Position",
            ),
        ),
        migrations.AlterField(
            model_name="organizationchart",
            name="start_date",
            field=models.DateField(verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="position",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Position code"),
        ),
        migrations.AlterField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="position",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="position",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "Chief Executive Officer (CEO)"),
                    (2, "Block Director"),
                    (3, "Deputy Block Director"),
                    (4, "Department Manager"),
                    (5, "Deputy Department Manager"),
                    (6, "Supervisor"),
                    (7, "Staff"),
                    (8, "Intern"),
                ],
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Position name"),
        ),
    ]
