# Generated by Django 5.2.6 on 2025-12-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0002_proposal_timesheet_entry_complaint_complaint_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeworkhistory",
            name="name",
            field=models.CharField(
                choices=[
                    ("Change Position", "Change Position"),
                    ("Change Status", "Change Status"),
                    ("Transfer", "Transfer"),
                    ("Change Employee Type", "Change Employee Type"),
                    ("Change Contract", "Change Contract"),
                    ("Return to Work", "Return to Work"),
                ],
                help_text="Type of the work history event",
                max_length=50,
                verbose_name="Event type",
            ),
        ),
    ]
