# Generated by Django 5.2.6 on 2025-12-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0003_alter_employeeworkhistory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheetentry",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("on_time", "On time"), ("not_on_time", "Not on time"), ("absent", "Absent")],
                max_length=32,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
