# Generated by Django 5.2.6 on 2026-01-09 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0002_remove_recruitmentcandidate_unique_citizen_id_when_not_null_and_more"),
        ("hrm", "0003_remove_position_data_scope"),
    ]

    operations = []
