# Generated by Django 5.2.6 on 2025-12-11 16:57

from django.db import migrations, models


def fill_effective_date(apps, schema_editor):
    EmployeeDependent = apps.get_model("hrm", "EmployeeDependent")
    instances_to_update = []
    for dependent in EmployeeDependent.objects.filter(effective_date__isnull=True):
        dependent.effective_date = dependent.created_at.date()
        instances_to_update.append(dependent)
    EmployeeDependent.objects.bulk_update(instances_to_update, ["effective_date"])


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0004_alter_timesheetentry_status"),
    ]

    operations = [
        migrations.RunPython(fill_effective_date, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employeedependent",
            name="effective_date",
            field=models.DateField(
                help_text="Start date for tax deduction applicability", verbose_name="Effective date"
            ),
        ),
    ]
