# Generated by Django 5.2.6 on 2026-01-10 03:52

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        ("hrm", "0004_merge_20260109_2030"),
        ("realestate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancedailyreport",
            options={
                "verbose_name": "Báo Cáo Chấm Công Hàng Ngày",
                "verbose_name_plural": "Báo Cáo Chấm Công Hàng Ngày",
            },
        ),
        migrations.AlterModelOptions(
            name="attendanceexemption",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Miễn chấm công",
                "verbose_name_plural": "các nhân sự Miễn chấm công",
            },
        ),
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Log Chấm Công",
                "verbose_name_plural": "các Log Chấm Công",
            },
        ),
        migrations.AlterModelOptions(
            name="bank",
            options={
                "ordering": ["id"],
                "verbose_name": "Ngân Hàng",
                "verbose_name_plural": "Các ngân hàng",
            },
        ),
        migrations.AlterModelOptions(
            name="employeemonthlytimesheet",
            options={
                "verbose_name": "Bảng chấm công hàng tháng của nhân viên",
                "verbose_name_plural": "Bảng chấm công hàng tháng của nhân viên",
            },
        ),
        migrations.AlterModelOptions(
            name="employeeresignedreasonreport",
            options={
                "verbose_name": "Báo cáo lý do nghỉ việc của nhân viên",
                "verbose_name_plural": "Báo cáo lý do nghỉ việc của nhân viên",
            },
        ),
        migrations.AlterModelOptions(
            name="employeestatusbreakdownreport",
            options={
                "verbose_name": "Báo cáo phân tích tình trạng nhân viên",
                "verbose_name_plural": "Báo cáo phân tích tình trạng nhân viên",
            },
        ),
        migrations.AlterModelOptions(
            name="interviewcandidate",
            options={
                "ordering": ["interview_time"],
                "verbose_name": "Ứng viên",
                "verbose_name_plural": "Ứng viên",
            },
        ),
        migrations.AlterModelOptions(
            name="jobdescription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Mô tả công việc",
                "verbose_name_plural": "Mô tả công việc",
            },
        ),
        migrations.AlterModelOptions(
            name="recruitmentcandidatecontactlog",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Lịch sử liên hệ ứng viên",
                "verbose_name_plural": "Lịch sử liên hệ ứng viên",
            },
        ),
        migrations.AlterModelOptions(
            name="recruitmentsource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Nguồn tuyển dụng",
                "verbose_name_plural": "Nguồn tuyển dụng",
            },
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="attendance_method",
            field=models.CharField(
                choices=[
                    ("biometric_device", "Biometric Device"),
                    ("wifi", "WiFi"),
                    ("geolocation", "GeoLocation"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Phương thức chấm công",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="attendance_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_reports",
                to="hrm.attendancerecord",
                verbose_name="Log Chấm Công",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.block",
                verbose_name="Khối",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.branch",
                verbose_name="Chi Nhánh",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.department",
                verbose_name="Phòng Ban",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_daily_reports",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="realestate.project",
                verbose_name="Dự án",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="effective_date",
            field=models.DateField(
                blank=True,
                help_text="Date when exemption becomes active",
                null=True,
                verbose_name="Ngày Hiệu Lực",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="employee",
            field=models.OneToOneField(
                help_text="Employee to be exempt from attendance tracking",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_exemption",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes or remarks",
                max_length=1000,
                verbose_name="Ghi Chú",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="approve_status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "Đã duyệt"),
                    ("REJECTED", "Đã từ chối"),
                    ("PENDING", "Đang chờ"),
                ],
                db_index=True,
                default="APPROVED",
                help_text="Approval status of this attendance record",
                max_length=20,
                verbose_name="Trạng thái duyệt",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when this record was approved",
                null=True,
                verbose_name="Đã duyệt lúc",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee who approved this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_attendance_records",
                to="hrm.employee",
                verbose_name="Đã duyệt bởi",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="User ID from device, used to match with Employee.attendance_code",
                max_length=20,
                verbose_name="Mã Chấm Công",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_geolocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Geolocation reference (for geolocation attendance)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="hrm.attendancegeolocation",
                verbose_name="chấm Công GPS",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("biometric_device", "Biometric Device"),
                    ("wifi", "WiFi"),
                    ("geolocation", "GeoLocation"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="biometric_device",
                help_text="Type of attendance method used",
                max_length=20,
                verbose_name="Phương thức chấm công",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_wifi_device",
            field=models.ForeignKey(
                blank=True,
                help_text="WiFi device reference (for WiFi attendance)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="hrm.attendancewifidevice",
                verbose_name="Thiết bị WiFi",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="biometric_device",
            field=models.ForeignKey(
                blank=True,
                help_text="Attendance device that captured this record (for biometric device type)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="hrm.attendancedevice",
                verbose_name="Chấm công vân tay",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Mã Số Thuế"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee associated with this attendance record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Attendance photo (for geolocation attendance)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="files.filemodel",
                verbose_name="Ảnh",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="is_pending",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this attendance record is pending approval",
                verbose_name="Đang chờ",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="is_valid",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=True,
                help_text="Whether this attendance record is valid",
                null=True,
                verbose_name="Còn hiệu lực",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="GeoLocation latitude coordinate (for geolocation attendance)",
                max_digits=20,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Vĩ độ",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="GeoLocation longitude coordinate (for geolocation attendance)",
                max_digits=20,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Kinh độ",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="notes",
            field=libs.models.fields.SafeTextField(
                blank=True,
                help_text="Additional notes or comments about this attendance record",
                verbose_name="Ghi Chú",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="raw_data",
            field=models.JSONField(
                blank=True,
                help_text="Complete raw data from device for debugging purposes",
                null=True,
                verbose_name="Đữ liệu thô",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True,
                help_text="Date and time when attendance was recorded",
                verbose_name="Thời gian Ghi nhận",
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Mã Ngân Hàng"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên Ngân Hàng"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="carried_over_leave",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Giữ lại số ngày nghỉ từ năm trước. Chỉ áp dụng cho tháng 1. Sau đó, trường này phải được đặt về 0.",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="consumed_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Số ngày nghỉ đã sử dụng",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="early_leaving_minutes",
            field=models.IntegerField(default=0, verbose_name="Số phút về sớm"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_timesheets",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="generated_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Số ngày nghỉ phát sinh",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="late_coming_minutes",
            field=models.IntegerField(default=0, verbose_name="Số phút đi muộn"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="maternity_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Nghỉ việc hưởng chế độ thai sản",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="month_key",
            field=models.CharField(db_index=True, max_length=6, verbose_name="Tháng"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="note",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Ghi chú"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="official_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Giờ làm việc chính thức",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="official_working_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="Ngày làm việc chính thức",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="opening_balance_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Số ngày nghỉ đầu kỳ",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Làm việc ngoài giờ (OT)",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="paid_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Nghỉ phép có lương",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="probation_working_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="Ngày làm việc thử việc",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="public_holiday_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Nghỉ lễ",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="remaining_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Số ngày nghỉ còn lại",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="report_date",
            field=models.DateField(verbose_name="Ngày báo cáo"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="total_penalty_count",
            field=models.IntegerField(default=0, verbose_name="Tổng số lần bị phạt"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="total_worked_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sum of official_hours and overtime_hours",
                max_digits=8,
                verbose_name="Tổng số giờ làm việc",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="total_working_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="Tổng số ngày làm việc",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="unexcused_absence_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Nghỉ không lý do",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="unpaid_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Nghỉ không lương",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="agreement_termination",
            field=models.IntegerField(
                default=0,
                verbose_name="Thỏa thuận chấm dứt Hợp đồng lao động trước thời hạn",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.block",
                verbose_name="Khối",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.branch",
                verbose_name="Chi Nhánh",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="contract_expired",
            field=models.IntegerField(default=0, verbose_name="Hết hợp đồng"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="count_resigned",
            field=models.IntegerField(default=0, verbose_name="Số nhân viên đã nghỉ việc"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.department",
                verbose_name="Phòng Ban",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="disciplinary_termination",
            field=models.IntegerField(default=0, verbose_name="Sa thải do kỷ luật"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="job_abandonment",
            field=models.IntegerField(default=0, verbose_name="Bỏ việc"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="other",
            field=models.IntegerField(default=0, verbose_name="Khác"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="probation_fail",
            field=models.IntegerField(default=0, verbose_name="Thử việc không đạt"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="underperforming",
            field=models.IntegerField(default=0, verbose_name="Thành tích kém trong công việc"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="voluntary_career_change",
            field=models.IntegerField(
                default=0,
                verbose_name="Nguyện vọng theo đơn - Thay đổi định hướng công việc",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="voluntary_health",
            field=models.IntegerField(default=0, verbose_name="Nguyện vọng theo đơn - Không đảm bảo sức khỏe"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="voluntary_other",
            field=models.IntegerField(default=0, verbose_name="Nguyện vọng theo đơn - Khác"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="voluntary_personal",
            field=models.IntegerField(default=0, verbose_name="Nguyện vọng theo đơn - Bận việc cá nhân"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="workforce_reduction",
            field=models.IntegerField(default=0, verbose_name="Thanh lọc"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.block",
                verbose_name="Khối",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.branch",
                verbose_name="Chi Nhánh",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_active",
            field=models.IntegerField(default=0, verbose_name="Số nhân viên đang làm việc"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_maternity_leave",
            field=models.IntegerField(default=0, verbose_name="Số nhân viên nghỉ việc hưởng chế độ thai sản"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_onboarding",
            field=models.IntegerField(default=0, verbose_name="Số nhân viên đang onboarding"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_resigned",
            field=models.IntegerField(default=0, verbose_name="Số nhân viên đã nghỉ việc"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_resigned_reasons",
            field=models.JSONField(default=dict, verbose_name="Lý Do Nghỉ Việc"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_unpaid_leave",
            field=models.IntegerField(default=0, verbose_name="Số nhân viên nghỉ không lương"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.department",
                verbose_name="Phòng Ban",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="total_not_resigned",
            field=models.IntegerField(default=0, verbose_name="Tổng số nhân viên chưa nghỉ việc"),
        ),
        migrations.AlterField(
            model_name="interviewcandidate",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Email đã gửi lúc"),
        ),
        migrations.AlterField(
            model_name="interviewcandidate",
            name="interview_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_candidates",
                to="hrm.interviewschedule",
                verbose_name="Lịch phỏng vấn",
            ),
        ),
        migrations.AlterField(
            model_name="interviewcandidate",
            name="interview_time",
            field=models.DateTimeField(verbose_name="Số vòng phỏng vấn"),
        ),
        migrations.AlterField(
            model_name="interviewcandidate",
            name="recruitment_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_candidates",
                to="hrm.recruitmentcandidate",
                verbose_name="Ứng viên",
            ),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_descriptions",
                to="files.filemodel",
                verbose_name="File đính kèm",
            ),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="benefit",
            field=libs.models.fields.SafeTextField(verbose_name="Quyền lợi"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Mã mô tả công việc"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="note",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Ghi chú"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="position_title",
            field=models.CharField(max_length=255, verbose_name="Chức Vụ"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="preferred_criteria",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Tiêu chí ưu tiên"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="proposed_salary",
            field=models.CharField(max_length=100, verbose_name="Mức lương đề xuất"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="requirement",
            field=libs.models.fields.SafeTextField(verbose_name="Yêu cầu"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="responsibility",
            field=libs.models.fields.SafeTextField(verbose_name="Trách nhiệm"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Chức danh công việc"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="date",
            field=models.DateField(verbose_name="Ngày liên hệ"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidate_contact_logs",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="method",
            field=models.CharField(max_length=100, verbose_name="Phương thức liên hệ"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="note",
            field=models.TextField(blank=True, verbose_name="Ghi chú"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="recruitment_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_logs",
                to="hrm.recruitmentcandidate",
                verbose_name="Ứng viên",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Mã nguồn"),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="description",
            field=libs.models.fields.SafeTextField(blank=True, max_length=500, verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Tên nguồn"),
        ),
    ]
