# Generated by Django 5.2.6 on 2025-10-10 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_province_administrativeunit"),
        ("hrm", "0004_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="administrative_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="core.administrativeunit",
                verbose_name="Administrative unit",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="branch",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="core.province",
                verbose_name="Province",
            ),
        ),
    ]
