# Generated by Django 5.2.6 on 2025-10-10 07:35

import django.db.models.deletion
from django.db import migrations, models


def populate_department_branch(apps, schema_editor):
    """Populate department branch from block.branch"""
    Department = apps.get_model("hrm", "Department")
    for dept in Department.objects.select_related("block__branch").all():
        if dept.block and dept.block.branch:
            dept.branch = dept.block.branch
            dept.save(update_fields=["branch"])


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0005_add_branch_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="hrm.branch",
                verbose_name="Branch",
                null=True,
            ),
        ),
        migrations.RunPython(populate_department_branch, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="department",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="hrm.branch",
                verbose_name="Branch",
            ),
        ),
    ]
