# Generated by Django 5.2.9 on 2025-12-12 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0005_alter_employeedependent_effective_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeworkhistory",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                help_text="New contract for contract-change event",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_work_histories",
                to="hrm.contract",
                verbose_name="Contract",
            ),
        ),
    ]
