# Generated by Django 5.2.6 on 2026-01-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0005_alter_attendancedailyreport_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceexemption",
            name="end_date",
            field=models.DateField(
                blank=True, db_index=True, help_text="Date when exemption ends", null=True, verbose_name="End Date"
            ),
        ),
        migrations.AddField(
            model_name="attendanceexemption",
            name="status",
            field=models.CharField(
                choices=[("ENABLED", "Enabled"), ("DISABLED", "Disabled")],
                db_index=True,
                default="ENABLED",
                help_text="Status of the exemption",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="effective_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date when exemption becomes active",
                null=True,
                verbose_name="Ngày Hiệu Lực",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="employee",
            field=models.ForeignKey(
                help_text="Employee to be exempt from attendance tracking",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_exemptions",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceexemption",
            index=models.Index(fields=["status"], name="hrm_attenda_status_b25b1c_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceexemption",
            index=models.Index(fields=["end_date"], name="hrm_attenda_end_dat_61963f_idx"),
        ),
    ]
