# Generated by Django 5.2.10 on 2026-01-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
        ("hrm", "0005_alter_attendancedailyreport_options_and_more"),
        ("realestate", "0001_initial"),
    ]

    operations = [
        # Add new fields to StaffGrowthReport
        migrations.AddField(
            model_name="staffgrowthreport",
            name="timeframe_key",
            field=models.CharField(
                db_index=True,
                default="W00-0000",
                help_text="Format: 'W01-2026' for week or '01/2026' for month",
                max_length=20,
                verbose_name="Timeframe key",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffgrowthreport",
            name="timeframe_type",
            field=models.CharField(
                choices=[("week", "Week"), ("month", "Month")],
                default="week",
                max_length=10,
                verbose_name="Timeframe type",
            ),
            preserve_default=False,
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name="staffgrowthreport",
            name="month_key",
        ),
        migrations.RemoveField(
            model_name="staffgrowthreport",
            name="week_key",
        ),
        # Update unique constraint
        migrations.AlterUniqueTogether(
            name="staffgrowthreport",
            unique_together={
                ("timeframe_type", "timeframe_key", "branch", "block", "department")
            },
        ),
        # Update foreign keys to allow null/blank (to match previous state if changed)
        # Or just keep them as they were. The autogenerated migration added changes to block/branch/department
        # that seemed to just be changing `on_delete` or `related_name`?
        # Let's check the previous migration state or model.
        # The model definition I wrote has `on_delete=models.CASCADE, null=True, blank=True`.
        # The autogenerated migration showed changes to these fields.
        # I will include them to ensure consistency with the model code.
        migrations.AlterField(
            model_name="staffgrowthreport",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hrm.block",
            ),
        ),
        migrations.AlterField(
            model_name="staffgrowthreport",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hrm.branch",
            ),
        ),
        migrations.AlterField(
            model_name="staffgrowthreport",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hrm.department",
            ),
        ),
        # Create StaffGrowthEventLog model
        migrations.CreateModel(
            name="StaffGrowthEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("return", "Return"),
                            ("recruitment_source", "Recruitment Source"),
                            ("transfer", "Transfer"),
                            ("resignation", "Resignation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_date",
                    models.DateField(help_text="Original date of the event"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_growth_events",
                        to="hrm.employee",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="hrm.staffgrowthreport",
                    ),
                ),
            ],
            options={
                "unique_together": {("report", "employee", "event_type")},
            },
        ),
    ]
