# Generated by Django 5.2.6 on 2025-10-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_recruitmentchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentchannel',
            name='belong_to',
            field=models.CharField(choices=[('job_website', 'Job Website'), ('marketing', 'Marketing')], default='marketing', max_length=20, verbose_name='Belong to'),
        ),
    ]
