# Generated by Django 5.2.6 on 2025-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0006_department_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Channel name")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Channel code")),
                (
                    "belong_to",
                    models.CharField(
                        choices=[("job_website", "Job Website"), ("marketing", "Marketing")],
                        default="marketing",
                        max_length=20,
                        verbose_name="Belong to",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Recruitment Channel",
                "verbose_name_plural": "Recruitment Channels",
                "db_table": "hrm_recruitment_channel",
                "ordering": ["-created_at"],
            },
        ),
    ]
