# Generated by Django 5.2.6 on 2026-01-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0006_attendanceexemption_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workschedule",
            name="is_afternoon_required",
            field=models.BooleanField(
                default=True, help_text="Whether afternoon attendance is required", verbose_name="Afternoon required"
            ),
        ),
        migrations.AddField(
            model_name="workschedule",
            name="is_morning_required",
            field=models.BooleanField(
                default=True, help_text="Whether morning attendance is required", verbose_name="Morning required"
            ),
        ),
    ]
