# Generated by Django 5.2.6 on 2025-12-15 03:52

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0006_alter_employeeworkhistory_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeemonthlytimesheet",
            name="generated_leave_days",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Generated leave days"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="available_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Number of available leave days for the employee",
                max_digits=6,
                verbose_name="Available leave days",
            ),
        ),
    ]
