# Generated by Django 5.2.6 on 2026-01-15 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0007_add_work_schedule_required_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="annual_leave_days",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Number of annual leave days (maximum 30)",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)],
                verbose_name="Annual leave days",
            ),
        ),
    ]
