# Generated by Django 5.2.6 on 2025-12-15 04:48

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0007_employeemonthlytimesheet_generated_leave_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheetentry",
            name="day_type",
            field=models.CharField(
                blank=True,
                choices=[("holiday", "Holiday"), ("compensatory", "Compensatory"), ("official", "Official")],
                max_length=32,
                null=True,
                verbose_name="Day type",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="working_days",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Working days"
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Overtime hours"
            ),
        ),
        migrations.AlterField(
            model_name="timesheetentry",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On time"),
                    ("not_on_time", "Not on time"),
                    ("single_punch", "Single punch"),
                    ("absent", "Absent"),
                ],
                max_length=32,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
