# Generated by Django 5.2.6 on 2025-12-16 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0008_timesheetentry_day_type_timesheetentry_working_days_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contracttype",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contract Type",
                "verbose_name_plural": "Contract Types",
            },
        ),
    ]
