# Generated by manual creation for Employee model updates

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0009_update_code_related_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove old name field
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        # Add new fullname field
        migrations.AddField(
            model_name="employee",
            name="fullname",
            field=models.CharField(default="", max_length=200, verbose_name="Full name"),
            preserve_default=False,
        ),
        # Add username field
        migrations.AddField(
            model_name="employee",
            name="username",
            field=models.CharField(default="", max_length=100, unique=True, verbose_name="Username"),
            preserve_default=False,
        ),
        # Add email field
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True, verbose_name="Email"),
            preserve_default=False,
        ),
        # Add phone field
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=15, verbose_name="Phone number"),
        ),
        # Add branch field
        migrations.AddField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="hrm.branch",
                verbose_name="Branch",
            ),
            preserve_default=False,
        ),
        # Add block field
        migrations.AddField(
            model_name="employee",
            name="block",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="hrm.block",
                verbose_name="Block",
            ),
            preserve_default=False,
        ),
        # Add department field
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="hrm.department",
                verbose_name="Department",
            ),
            preserve_default=False,
        ),
        # Add note field
        migrations.AddField(
            model_name="employee",
            name="note",
            field=models.TextField(blank=True, verbose_name="Note"),
        ),
        # Alter user field to be nullable
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
