# Generated by Django 5.2.6 on 2025-12-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0009_alter_contracttype_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeecertificate",
            name="issuing_organization",
            field=models.CharField(
                blank=True,
                help_text="Organization that issued the certificate",
                max_length=100,
                null=True,
                verbose_name="Issuing organization",
            ),
        ),
    ]
