# Generated by Django 5.2.6 on 2026-01-16 04:50

from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0009_alter_attendanceexemption_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="address_text",
            field=libs.models.fields.SafeTextField(
                blank=True,
                db_index=True,
                default="",
                help_text="Address in text, used for Other Attendance record",
                verbose_name="Địa chỉ văn bản, dùng cho log chấm công Khác",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="end_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date when exemption ends",
                null=True,
                verbose_name="Ngày kết thúc",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="status",
            field=models.CharField(
                choices=[("ENABLED", "Đã kích hoạt"), ("DISABLED", "Đã tắt")],
                db_index=True,
                default="ENABLED",
                help_text="Status of the exemption",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="allow_referral",
            field=models.BooleanField(
                default=False,
                help_text="Enable users to set referrer and referee for candidates from this source",
                verbose_name="Allow referral",
            ),
        ),
    ]
