# Generated by Django 5.2.6 on 2026-01-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0009_alter_attendanceexemption_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceexemption",
            name="end_date",
            field=models.DateField(
                blank=True, db_index=True, help_text="Date when exemption ends", null=True, verbose_name="End Date"
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="status",
            field=models.CharField(
                choices=[("ENABLED", "Enabled"), ("DISABLED", "Disabled")],
                db_index=True,
                default="ENABLED",
                help_text="Status of the exemption",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="allow_referral",
            field=models.BooleanField(
                default=False,
                help_text="Enable users to set referrer and referee for candidates from this source",
                verbose_name="Allow referral",
            ),
        ),
    ]
