# Generated by Django 5.2.6 on 2025-12-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0010_alter_employeecertificate_issuing_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeworkhistory",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Decision associated with this work history event",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_work_histories",
                to="hrm.decision",
                verbose_name="Decision",
            ),
        ),
    ]
