# Generated by Django 5.2.6 on 2025-10-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0010_update_employee_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Source name")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Source code")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
            ],
            options={
                "verbose_name": "Recruitment Source",
                "verbose_name_plural": "Recruitment Sources",
                "db_table": "hrm_recruitment_source",
                "ordering": ["-created_at"],
            },
        ),
    ]
