# Generated by Django 5.2.6 on 2025-12-17 05:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0010_alter_employeecertificate_issuing_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheetentry",
            name="check_in_record",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Original Check-in"
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="check_out_record",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Original Check-out"
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="manually_corrected_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Manually corrected at"
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="manually_corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrected_timesheets",
                to="hrm.employee",
                verbose_name="Manually corrected by",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="ot_hours_calculated",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Calculated OT hours",
            ),
        ),
    ]
