# Generated by Django 5.2.6 on 2026-01-16 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0010_alter_attendanceexemption_end_date_and_more"),
        ("hrm", "0010_attendancerecord_address_text_and_more"),
    ]

    operations = []
