# Generated by Django 5.2.6 on 2025-10-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0011_recruitmentsource"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Job description code")),
                ("title", models.CharField(max_length=200, verbose_name="Job title")),
                ("responsibility", models.TextField(verbose_name="Responsibility")),
                ("requirement", models.TextField(verbose_name="Requirement")),
                ("preferred_criteria", models.TextField(blank=True, verbose_name="Preferred criteria")),
                ("benefit", models.TextField(verbose_name="Benefit")),
                ("proposed_salary", models.CharField(max_length=100, verbose_name="Proposed salary")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("attachment", models.CharField(blank=True, max_length=500, verbose_name="Attachment")),
            ],
            options={
                "verbose_name": "Job Description",
                "verbose_name_plural": "Job Descriptions",
                "db_table": "hrm_job_description",
                "ordering": ["-created_at"],
            },
        ),
    ]
