# Generated by Django 5.2.6 on 2025-12-17 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0011_employeeworkhistory_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheetentry",
            name="check_in_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Original Check-in"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="check_out_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Original Check-out"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="manually_corrected_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Manually corrected at"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="manually_corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrected_timesheets",
                to="hrm.employee",
                verbose_name="Manually corrected by",
            ),
        ),
    ]
