# Generated by Django 5.2.6 on 2025-10-16 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0012_jobdescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Request code")),
                ("name", models.CharField(max_length=200, verbose_name="Request name")),
                (
                    "recruitment_type",
                    models.CharField(
                        choices=[("NEW_HIRE", "New Hire"), ("REPLACEMENT", "Replacement")],
                        max_length=20,
                        verbose_name="Recruitment type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("OPEN", "Open"), ("PAUSED", "Paused"), ("CLOSED", "Closed")],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("proposed_salary", models.CharField(max_length=100, verbose_name="Proposed salary")),
                ("number_of_positions", models.IntegerField(default=1, verbose_name="Number of positions")),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_requests",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_requests",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_requests",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "job_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_requests",
                        to="hrm.jobdescription",
                        verbose_name="Job description",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposed_recruitment_requests",
                        to="hrm.employee",
                        verbose_name="Proposer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruitment Request",
                "verbose_name_plural": "Recruitment Requests",
                "db_table": "hrm_recruitment_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
