# Generated by Django 5.2.6 on 2025-12-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0012_timesheetentry_check_in_record_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheetentry",
            name="day_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("holiday", "Holiday day"),
                    ("compensatory", "Compensatory day"),
                    ("official", "Official day"),
                ],
                max_length=32,
                null=True,
                verbose_name="Day type",
            ),
        ),
    ]
