# Generated by Django 5.2.6 on 2026-01-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0012_alter_attendanceexemption_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheetentry",
            name="working_day_type",
            field=models.CharField(
                choices=[("official", "Official"), ("probation", "Probation")],
                default="official",
                max_length=20,
                verbose_name="Working day type",
            ),
        ),
        migrations.AlterField(
            model_name="timesheetentry",
            name="net_percentage",
            field=models.IntegerField(
                blank=True,
                help_text="Snapshot of the contract net percentage.",
                null=True,
                verbose_name="Net percentage",
            ),
        ),
    ]
