# Generated by Django 5.2.6 on 2025-12-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0013_alter_timesheetentry_day_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when this record was approved",
                null=True,
                verbose_name="Approved at",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee who approved this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_attendance_records",
                to="hrm.employee",
                verbose_name="Approved by",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="is_pending",
            field=models.BooleanField(
                default=False,
                help_text="Whether this attendance record is pending approval",
                verbose_name="Is pending",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="is_valid",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Whether this attendance record is valid",
                null=True,
                verbose_name="Is valid",
            ),
        ),
    ]
