# Generated by Django 5.2.6 on 2025-10-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0013_add_recruitment_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentsource",
            name="allow_referral",
            field=models.BooleanField(
                default=False,
                help_text="Enable users to set referrer and referee for candidates from this source",
                verbose_name="Allow referral",
            ),
        ),
    ]
