# Generated by Django 5.2.6 on 2026-01-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0013_timesheetentry_working_day_type_and_more"),
    ]

    operations = [
        # STEP 1: Remove old unique_together constraint first (uses old fields)
        migrations.AlterUniqueTogether(
            name="staffgrowthreport",
            unique_together=set(),
        ),
        # STEP 2: Add new fields
        migrations.AddField(
            model_name="staffgrowthreport",
            name="timeframe_key",
            field=models.CharField(
                db_index=True,
                help_text="Format: 'W01-2026' for week or '01/2026' for month",
                max_length=20,
                null=True,
                verbose_name="Timeframe key",
            ),
        ),
        migrations.AddField(
            model_name="staffgrowthreport",
            name="timeframe_type",
            field=models.CharField(
                choices=[("week", "Week"), ("month", "Month")],
                db_index=True,
                max_length=10,
                null=True,
                verbose_name="Timeframe type",
            ),
        ),
        # STEP 3: Remove old fields
        migrations.RemoveField(
            model_name="staffgrowthreport",
            name="month_key",
        ),
        migrations.RemoveField(
            model_name="staffgrowthreport",
            name="week_key",
        ),
        # STEP 4: Add new unique_together constraint (uses new fields)
        migrations.AlterUniqueTogether(
            name="staffgrowthreport",
            unique_together={("timeframe_type", "timeframe_key", "branch", "block", "department")},
        ),
    ]
