# Generated by Django 5.2.6 on 2025-10-17 04:54

from django.db import migrations

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0014_recruitmentsource_allow_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="description",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="address",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="description",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="note",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="benefit",
            field=libs.models.fields.SafeTextField(verbose_name="Benefit"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="note",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="preferred_criteria",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Preferred criteria"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="requirement",
            field=libs.models.fields.SafeTextField(verbose_name="Requirement"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="responsibility",
            field=libs.models.fields.SafeTextField(verbose_name="Responsibility"),
        ),
        migrations.AlterField(
            model_name="position",
            name="description",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="recruitmentchannel",
            name="description",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="description",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Description"),
        ),
    ]
