# Generated by Django 5.2.6 on 2025-12-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0015_alter_attendancedailyreport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="net_percentage",
            field=models.IntegerField(
                choices=[(100, "100%"), (85, "85%")],
                default=100,
                help_text="Net salary percentage at the time of contract",
                verbose_name="Net percentage",
            ),
        ),
        migrations.AlterField(
            model_name="contracttype",
            name="net_percentage",
            field=models.IntegerField(
                choices=[(100, "100%"), (85, "85%")],
                default=100,
                help_text="Net salary percentage at the time of contract",
                verbose_name="Net percentage",
            ),
        ),
    ]
