# Generated by Django 5.2.6 on 2025-10-17 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0015_alter_block_description_alter_branch_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Candidate code")),
                ("name", models.CharField(max_length=200, verbose_name="Candidate name")),
                (
                    "citizen_id",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Citizen ID must contain exactly 12 digits.", regex="^\\d{12}$"
                            )
                        ],
                        verbose_name="Citizen ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Years of experience"),
                ),
                ("submitted_date", models.DateField(verbose_name="Submitted date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONTACTED", "Contacted"),
                            ("INTERVIEW_SCHEDULED_1", "Interview Scheduled 1"),
                            ("INTERVIEWED_1", "Interviewed 1"),
                            ("INTERVIEW_SCHEDULED_2", "Interview Scheduled 2"),
                            ("INTERVIEWED_2", "Interviewed 2"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="CONTACTED",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("onboard_date", models.DateField(blank=True, null=True, verbose_name="Onboard date")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_candidates",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_candidates",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_candidates",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "recruitment_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="hrm.recruitmentchannel",
                        verbose_name="Recruitment channel",
                    ),
                ),
                (
                    "recruitment_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="hrm.recruitmentrequest",
                        verbose_name="Recruitment request",
                    ),
                ),
                (
                    "recruitment_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="hrm.recruitmentsource",
                        verbose_name="Recruitment source",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_candidates",
                        to="hrm.employee",
                        verbose_name="Referrer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruitment Candidate",
                "verbose_name_plural": "Recruitment Candidates",
                "db_table": "hrm_recruitment_candidate",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentCandidateContactLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Contact date")),
                ("method", models.CharField(max_length=100, verbose_name="Contact method")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_contact_logs",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "recruitment_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_logs",
                        to="hrm.recruitmentcandidate",
                        verbose_name="Recruitment candidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruitment Candidate Contact Log",
                "verbose_name_plural": "Recruitment Candidate Contact Logs",
                "db_table": "hrm_recruitment_candidate_contact_log",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
