# Generated by Django 5.2.6 on 2025-12-19 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0016_alter_attendancedailyreport_options_and_more"),
        ("hrm", "0016_alter_contract_net_percentage_and_more"),
    ]

    operations = []
