# Generated by Django 5.2.6 on 2025-10-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0016_recruitmentcandidate_recruitmentcandidatecontactlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Expense date')),
                ('num_candidates_participated', models.PositiveIntegerField(default=0, verbose_name='Number of candidates participated')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total cost')),
                ('num_candidates_hired', models.PositiveIntegerField(default=0, verbose_name='Number of candidates hired')),
                ('activity', models.TextField(blank=True, max_length=1000, verbose_name='Activity description')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='Note')),
                ('recruitment_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='hrm.recruitmentchannel', verbose_name='Recruitment channel')),
                ('recruitment_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='hrm.recruitmentrequest', verbose_name='Recruitment request')),
                ('recruitment_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='hrm.recruitmentsource', verbose_name='Recruitment source')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_expenses', to='hrm.employee', verbose_name='Referee')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_expenses', to='hrm.employee', verbose_name='Referrer')),
            ],
            options={
                'verbose_name': 'Recruitment Expense',
                'verbose_name_plural': 'Recruitment Expenses',
                'db_table': 'hrm_recruitment_expense',
                'ordering': ['-created_at'],
            },
        ),
    ]
