# Generated by Django 5.2.6 on 2025-10-21 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_add_uploaded_by_field"),
        ("hrm", "0017_recruitmentexpense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdescription",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_descriptions",
                to="files.filemodel",
                verbose_name="Attachment",
            ),
        ),
    ]
