# Generated by Django 5.2.6 on 2025-12-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0017_merge_20251219_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeworkhistory",
            name="new_employee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OFFICIAL", "Official"),
                    ("APPRENTICE", "Apprentice"),
                    ("UNPAID_OFFICIAL", "Unpaid - Official"),
                    ("UNPAID_PROBATION", "Unpaid - Probation"),
                    ("PROBATION", "Probation"),
                    ("INTERN", "Intern"),
                    ("PROBATION_TYPE_1", "Probation Type 1"),
                ],
                help_text="New employee type",
                max_length=50,
                null=True,
                verbose_name="New employee type",
            ),
        ),
        migrations.AddField(
            model_name="employeeworkhistory",
            name="old_employee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OFFICIAL", "Official"),
                    ("APPRENTICE", "Apprentice"),
                    ("UNPAID_OFFICIAL", "Unpaid - Official"),
                    ("UNPAID_PROBATION", "Unpaid - Probation"),
                    ("PROBATION", "Probation"),
                    ("INTERN", "Intern"),
                    ("PROBATION_TYPE_1", "Probation Type 1"),
                ],
                help_text="Previous employee type",
                max_length=50,
                null=True,
                verbose_name="Old employee type",
            ),
        ),
    ]
