# Generated by Django 5.2.6 on 2025-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0018_change_job_description_attachment_to_foreignkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="position_title",
            field=models.CharField(default="", max_length=255, verbose_name="Position title"),
        ),
    ]
