# Generated by Django 5.2.6 on 2025-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0019_add_position_title_to_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdescription",
            name="position_title",
            field=models.CharField(max_length=255, verbose_name="Position title"),
        ),
    ]
