# Generated by Django 5.2.6 on 2025-10-22 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0019_add_position_title_to_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='position_title',
            field=models.CharField(max_length=255, verbose_name='Position title'),
        ),
        migrations.CreateModel(
            name='HiredCandidateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(verbose_name='Report date')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20, verbose_name='Period type')),
                ('source_type', models.CharField(choices=[('introduction', 'Introduction'), ('recruitment', 'Recruitment'), ('return', 'Return')], max_length=20, verbose_name='Source type')),
                ('num_candidates_hired', models.PositiveIntegerField(default=0, verbose_name='Number of candidates hired')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hired_candidate_reports', to='hrm.block', verbose_name='Block')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hired_candidate_reports', to='hrm.branch', verbose_name='Branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hired_candidate_reports', to='hrm.department', verbose_name='Department')),
                ('employee', models.ForeignKey(blank=True, help_text="Only applicable for 'introduction' source type", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hired_candidate_reports', to='hrm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Hired Candidate Report',
                'verbose_name_plural': 'Hired Candidate Reports',
                'db_table': 'hrm_hired_candidate_report',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentChannelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(verbose_name='Report date')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20, verbose_name='Period type')),
                ('org_unit_name', models.CharField(max_length=200, verbose_name='Organization unit name')),
                ('org_unit_type', models.CharField(choices=[('branch', 'Branch'), ('block', 'Block'), ('department', 'Department')], max_length=20, verbose_name='Organization unit type')),
                ('num_hires', models.PositiveIntegerField(default=0, verbose_name='Number of hires')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_channel_reports', to='hrm.block', verbose_name='Block')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_channel_reports', to='hrm.branch', verbose_name='Branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_channel_reports', to='hrm.department', verbose_name='Department')),
                ('recruitment_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_reports', to='hrm.recruitmentchannel', verbose_name='Recruitment channel')),
            ],
            options={
                'verbose_name': 'Recruitment Channel Report',
                'verbose_name_plural': 'Recruitment Channel Reports',
                'db_table': 'hrm_recruitment_channel_report',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentCostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(verbose_name='Report date')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20, verbose_name='Period type')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total cost')),
                ('num_hires', models.PositiveIntegerField(default=0, verbose_name='Number of hires')),
                ('avg_cost_per_hire', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Average cost per hire')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_cost_reports', to='hrm.block', verbose_name='Block')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_cost_reports', to='hrm.branch', verbose_name='Branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_cost_reports', to='hrm.department', verbose_name='Department')),
                ('recruitment_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_reports', to='hrm.recruitmentchannel', verbose_name='Recruitment channel')),
                ('recruitment_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_reports', to='hrm.recruitmentsource', verbose_name='Recruitment source')),
            ],
            options={
                'verbose_name': 'Recruitment Cost Report',
                'verbose_name_plural': 'Recruitment Cost Reports',
                'db_table': 'hrm_recruitment_cost_report',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentSourceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(verbose_name='Report date')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20, verbose_name='Period type')),
                ('org_unit_name', models.CharField(max_length=200, verbose_name='Organization unit name')),
                ('org_unit_type', models.CharField(choices=[('branch', 'Branch'), ('block', 'Block'), ('department', 'Department')], max_length=20, verbose_name='Organization unit type')),
                ('num_hires', models.PositiveIntegerField(default=0, verbose_name='Number of hires')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_source_reports', to='hrm.block', verbose_name='Block')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_source_reports', to='hrm.branch', verbose_name='Branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_source_reports', to='hrm.department', verbose_name='Department')),
                ('recruitment_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_reports', to='hrm.recruitmentsource', verbose_name='Recruitment source')),
            ],
            options={
                'verbose_name': 'Recruitment Source Report',
                'verbose_name_plural': 'Recruitment Source Reports',
                'db_table': 'hrm_recruitment_source_report',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(verbose_name='Report date')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20, verbose_name='Period type')),
                ('total_referral_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total referral cost')),
                ('num_referrals', models.PositiveIntegerField(default=0, verbose_name='Number of referrals')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_cost_reports', to='hrm.department', verbose_name='Department')),
                ('employee', models.ForeignKey(blank=True, help_text='Null for summary record, populated for employee-level detail', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_cost_reports', to='hrm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Referral Cost Report',
                'verbose_name_plural': 'Referral Cost Reports',
                'db_table': 'hrm_referral_cost_report',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffGrowthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(verbose_name='Report date')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20, verbose_name='Period type')),
                ('num_introductions', models.PositiveIntegerField(default=0, verbose_name='Number of introductions')),
                ('num_returns', models.PositiveIntegerField(default=0, verbose_name='Number of returns')),
                ('num_new_hires', models.PositiveIntegerField(default=0, verbose_name='Number of new hires')),
                ('num_transfers', models.PositiveIntegerField(default=0, verbose_name='Number of transfers')),
                ('num_resignations', models.PositiveIntegerField(default=0, verbose_name='Number of resignations')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_growth_reports', to='hrm.block', verbose_name='Block')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_growth_reports', to='hrm.branch', verbose_name='Branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_growth_reports', to='hrm.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Staff Growth Report',
                'verbose_name_plural': 'Staff Growth Reports',
                'db_table': 'hrm_staff_growth_report',
                'ordering': ['-report_date'],
                'unique_together': {('report_date', 'period_type', 'branch', 'block', 'department')},
            },
        ),
    ]
