# Generated by Django 5.2.6 on 2025-12-23 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0019_alter_attendancedailyreport_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancedailyreport",
            options={"verbose_name": "Attendance Daily Report", "verbose_name_plural": "Attendance Daily Reports"},
        ),
        migrations.AlterModelOptions(
            name="attendanceexemption",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Attendance Exemption",
                "verbose_name_plural": "Attendance Exemptions",
            },
        ),
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
            },
        ),
        migrations.AlterModelOptions(
            name="bank",
            options={"ordering": ["id"], "verbose_name": "Bank", "verbose_name_plural": "Banks"},
        ),
        migrations.AlterModelOptions(
            name="interviewcandidate",
            options={
                "ordering": ["interview_time"],
                "verbose_name": "Interview Candidate",
                "verbose_name_plural": "Interview Candidates",
            },
        ),
        migrations.AlterModelOptions(
            name="jobdescription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Job Description",
                "verbose_name_plural": "Job Descriptions",
            },
        ),
        migrations.AlterModelOptions(
            name="recruitmentcandidatecontactlog",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Recruitment Candidate Contact Log",
                "verbose_name_plural": "Recruitment Candidate Contact Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="recruitmentsource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Recruitment Source",
                "verbose_name_plural": "Recruitment Sources",
            },
        ),
    ]
