# Generated by Django 5.2.6 on 2025-10-22 11:16

import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0020_alter_jobdescription_position_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdescription",
            name="position_title",
            field=models.CharField(max_length=255, verbose_name="Position title"),
        ),
        migrations.CreateModel(
            name="InterviewSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "interview_type",
                    models.CharField(
                        choices=[("IN_PERSON", "In Person"), ("ONLINE", "Online")],
                        default="IN_PERSON",
                        max_length=20,
                        verbose_name="Interview type",
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Location")),
                ("time", models.DateTimeField(verbose_name="Interview time")),
                ("note", libs.models.fields.SafeTextField(blank=True, verbose_name="Note")),
                (
                    "interviewers",
                    models.ManyToManyField(
                        blank=True, related_name="interview_schedules", to="hrm.employee", verbose_name="Interviewers"
                    ),
                ),
                (
                    "recruitment_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interview_schedules",
                        to="hrm.recruitmentrequest",
                        verbose_name="Recruitment request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Schedule",
                "verbose_name_plural": "Interview Schedules",
                "db_table": "hrm_interview_schedule",
                "ordering": ["-time"],
            },
        ),
        migrations.CreateModel(
            name="InterviewCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("interview_time", models.DateTimeField(verbose_name="Interview time")),
                ("email_sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Email sent at")),
                (
                    "interview_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_candidates",
                        to="hrm.interviewschedule",
                        verbose_name="Interview schedule",
                    ),
                ),
                (
                    "recruitment_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_candidates",
                        to="hrm.recruitmentcandidate",
                        verbose_name="Recruitment candidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Candidate",
                "verbose_name_plural": "Interview Candidates",
                "db_table": "hrm_interview_candidate",
                "ordering": ["interview_time"],
                "unique_together": {("recruitment_candidate", "interview_schedule")},
            },
        ),
    ]
