# Generated by Django 5.2.6 on 2025-10-23 04:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def populate_personal_email(apps, schema_editor):
    Employee = apps.get_model("hrm", "Employee")
    for employee in Employee.objects.all():
        if not employee.personal_email:
            employee.personal_email = f"{employee.username}_{employee.id}@example.com"
            employee.save(update_fields=["personal_email"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_nationality"),
        ("files", "0002_add_uploaded_by_field"),
        ("hrm", "0021_add_interview_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Contract type name")),
            ],
            options={
                "verbose_name": "Contract type",
                "verbose_name_plural": "Contract types",
                "db_table": "hrm_contract_type",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="attendance_code",
            field=models.CharField(
                default="000000",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Attendance code must contain only digits", regex="^\\d+$"
                    )
                ],
                verbose_name="Attendance code",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_avatars",
                to="files.filemodel",
                verbose_name="Avatar",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="citizen_id",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Citizen ID must contain only digits", regex="^\\d*$"
                    )
                ],
                verbose_name="Citizen ID",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="citizen_id_issued_date",
            field=models.DateField(blank=True, null=True, verbose_name="Citizen ID issued date"),
        ),
        migrations.AddField(
            model_name="employee",
            name="citizen_id_issued_place",
            field=models.CharField(blank=True, max_length=100, verbose_name="Citizen ID issued place"),
        ),
        migrations.AddField(
            model_name="employee",
            name="code_type",
            field=models.CharField(
                choices=[("MV", "MV"), ("CTV", "CTV")], default="MV", max_length=10, verbose_name="Employee type"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(default="1900-01-01", verbose_name="Date of birth"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Emergency contact name"),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must contain only digits", regex="^\\d*$"
                    )
                ],
                verbose_name="Emergency contact phone",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="ethnicity",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ethnicity"),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")], default="MALE", max_length=10, verbose_name="Gender"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                choices=[("SINGLE", "Single"), ("MARRIED", "Married"), ("DIVORCED", "Divorced")],
                default="SINGLE",
                max_length=10,
                verbose_name="Marital status",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="core.nationality",
                verbose_name="Nationality",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="permanent_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Permanent address"),
        ),
        migrations.AddField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=100, verbose_name="Personal email"),
            preserve_default=False,
        ),
        migrations.RunPython(populate_personal_email, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(max_length=100, verbose_name="Personal email", unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=100, verbose_name="Place of birth"),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="hrm.position",
                verbose_name="Position",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="religion",
            field=models.CharField(blank=True, max_length=100, verbose_name="Religion"),
        ),
        migrations.AddField(
            model_name="employee",
            name="residential_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Residential address"),
        ),
        migrations.AddField(
            model_name="employee",
            name="resignation_date",
            field=models.DateField(blank=True, null=True, verbose_name="Resignation date"),
        ),
        migrations.AddField(
            model_name="employee",
            name="resignation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Career Change", "Career Change"),
                    ("Underperforming", "Underperforming"),
                    ("Terminated", "Terminated"),
                    ("Personal Issues", "Personal Issues"),
                    ("Job Abandonment", "Job Abandonment"),
                    ("Not a Good Fit", "Not a Good Fit"),
                    ("Health Issues", "Health Issues"),
                ],
                max_length=50,
                null=True,
                verbose_name="Resignation reason",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="start_date",
            field=models.DateField(default="2024-01-01", verbose_name="Start date"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Onboarding", "Onboarding"),
                    ("Resigned", "Resigned"),
                    ("Maternity Leave", "Maternity Leave"),
                    ("Unpaid Leave", "Unpaid Leave"),
                ],
                default="Active",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="tax_code",
            field=models.CharField(blank=True, max_length=12, verbose_name="Tax code"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits", regex="^\\d{10}$"
                    )
                ],
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="username",
            field=models.CharField(max_length=150, unique=True, verbose_name="Username"),
        ),
        migrations.AddField(
            model_name="employee",
            name="contract_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="hrm.contracttype",
                verbose_name="Contract type",
            ),
        ),
    ]
