# Generated by Django 5.2.6 on 2025-12-24 04:47

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0021_alter_attendancedailyreport_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeemonthlytimesheet",
            name="holiday_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Holiday overtime hours"
            ),
        ),
        migrations.AddField(
            model_name="employeemonthlytimesheet",
            name="saturday_in_week_overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Saturday and in week overtime hours",
            ),
        ),
        migrations.AddField(
            model_name="employeemonthlytimesheet",
            name="sunday_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Sunday overtime hours"
            ),
        ),
    ]
