# Generated by Django 5.2.6 on 2025-10-27 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0022_contracttype_remove_employee_fullname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HiredCandidateReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(verbose_name="Report date")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("referral_source", "Referral Source"),
                            ("marketing_channel", "Marketing Channel"),
                            ("job_website_channel", "Job Website Channel"),
                            ("recruitment_department_source", "Recruitment Department Source"),
                            ("returning_employee", "Returning Employee"),
                        ],
                        max_length=50,
                        verbose_name="Source type",
                    ),
                ),
                (
                    "month_key",
                    models.CharField(
                        db_index=True,
                        help_text="Format: MM/YYYY for monthly aggregation",
                        max_length=7,
                        verbose_name="Month key",
                    ),
                ),
                (
                    "week_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Format: Week W - MM/YYYY for weekly aggregation",
                        max_length=20,
                        null=True,
                        verbose_name="Week key",
                    ),
                ),
                (
                    "num_candidates_hired",
                    models.PositiveIntegerField(default=0, verbose_name="Number of candidates hired"),
                ),
                (
                    "num_experienced",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Candidates with prior work experience",
                        verbose_name="Number of experienced candidates",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only applicable for 'referral_source' type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hired_candidate_reports",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hired Candidate Report",
                "verbose_name_plural": "Hired Candidate Reports",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentChannelReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(verbose_name="Report date")),
                ("num_hires", models.PositiveIntegerField(default=0, verbose_name="Number of hires")),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "recruitment_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_reports",
                        to="hrm.recruitmentchannel",
                        verbose_name="Recruitment channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruitment Channel Report",
                "verbose_name_plural": "Recruitment Channel Reports",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentCostReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(verbose_name="Report date")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("referral_source", "Referral Source"),
                            ("marketing_channel", "Marketing Channel"),
                            ("job_website_channel", "Job Website Channel"),
                            ("recruitment_department_source", "Recruitment Department Source"),
                            ("returning_employee", "Returning Employee"),
                        ],
                        max_length=50,
                        verbose_name="Source type",
                    ),
                ),
                (
                    "month_key",
                    models.CharField(
                        db_index=True,
                        help_text="Format: YYYY-MM for monthly aggregation",
                        max_length=7,
                        verbose_name="Month key",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Total cost"),
                ),
                ("num_hires", models.PositiveIntegerField(default=0, verbose_name="Number of hires")),
                (
                    "avg_cost_per_hire",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Average cost per hire"
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruitment Cost Report",
                "verbose_name_plural": "Recruitment Cost Reports",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentSourceReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(verbose_name="Report date")),
                ("num_hires", models.PositiveIntegerField(default=0, verbose_name="Number of hires")),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "recruitment_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_reports",
                        to="hrm.recruitmentsource",
                        verbose_name="Recruitment source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruitment Source Report",
                "verbose_name_plural": "Recruitment Source Reports",
            },
        ),
        migrations.CreateModel(
            name="StaffGrowthReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(verbose_name="Report date")),
                (
                    "month_key",
                    models.CharField(
                        db_index=True,
                        help_text="Format: MM/YYYY for monthly aggregation",
                        max_length=7,
                        verbose_name="Month key",
                    ),
                ),
                (
                    "week_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Format: Week W - MM/YYYY for weekly aggregation",
                        max_length=20,
                        null=True,
                        verbose_name="Week key",
                    ),
                ),
                ("num_introductions", models.PositiveIntegerField(default=0, verbose_name="Number of introductions")),
                ("num_returns", models.PositiveIntegerField(default=0, verbose_name="Number of returns")),
                (
                    "num_recruitment_source",
                    models.PositiveIntegerField(default=0, verbose_name="Number of new recruitment source"),
                ),
                ("num_transfers", models.PositiveIntegerField(default=0, verbose_name="Number of transfers")),
                ("num_resignations", models.PositiveIntegerField(default=0, verbose_name="Number of resignations")),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_reports",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Growth Report",
                "verbose_name_plural": "Staff Growth Reports",
            },
        ),
    ]
