# Generated by Django 5.2.6 on 2025-10-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0023_hiredcandidatereport_recruitmentchannelreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredcandidatereport',
            name='week_key',
            field=models.CharField(blank=True, db_index=True, help_text='Format: Week W - MM/YYYY for weekly aggregation', max_length=20, null=True, verbose_name='Week key'),
        ),
    ]
