# Generated by Django 5.2.6 on 2025-10-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0023_hiredcandidatereport_recruitmentchannelreport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentchannel",
            name="belong_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("job_website", "Job Website"),
                    ("marketing", "Marketing"),
                    ("hunt", "Hunt"),
                    ("school", "School"),
                ],
                default="",
                max_length=20,
                verbose_name="Belong to",
            ),
        ),
    ]
