# Generated by Django 5.2.6 on 2025-12-25 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0023_alter_attendancedailyreport_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancedailyreport",
            options={
                "verbose_name": "Báo Cáo Chấm Công Hàng Ngày",
                "verbose_name_plural": "Báo Cáo Chấm Công Hàng Ngày",
            },
        ),
        migrations.AlterModelOptions(
            name="attendanceexemption",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Miễn chấm công",
                "verbose_name_plural": "các nhân sự Miễn chấm công",
            },
        ),
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Log Chấm Công",
                "verbose_name_plural": "các Log Chấm Công",
            },
        ),
        migrations.AlterModelOptions(
            name="bank",
            options={"ordering": ["id"], "verbose_name": "Ngân Hàng", "verbose_name_plural": "Ngân hàng"},
        ),
        migrations.AlterModelOptions(
            name="interviewcandidate",
            options={"ordering": ["interview_time"], "verbose_name": "Ứng viên", "verbose_name_plural": "Ứng viên"},
        ),
        migrations.AlterModelOptions(
            name="jobdescription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Mô tả công việc",
                "verbose_name_plural": "Mô tả công việc",
            },
        ),
        migrations.AlterModelOptions(
            name="recruitmentcandidatecontactlog",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Lịch sử liên hệ ứng viên",
                "verbose_name_plural": "Lịch sử liên hệ ứng viên",
            },
        ),
        migrations.AlterModelOptions(
            name="recruitmentsource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Nguồn tuyển dụng",
                "verbose_name_plural": "Nguồn tuyển dụng",
            },
        ),
    ]
