# Generated by Django 5.2.6 on 2025-10-26 13:09

from django.db import migrations, models


def populate_week_key(apps, schema_editor):
    """Populate week_key for existing HiredCandidateReport records."""
    from datetime import timedelta
    
    HiredCandidateReport = apps.get_model('hrm', 'HiredCandidateReport')
    
    def get_week_key_from_date(report_date):
        """Generate week key from a date."""
        # Get the Monday of the week containing report_date
        monday = report_date - timedelta(days=report_date.weekday())
        
        # Calculate week number within the month
        first_day_of_month = report_date.replace(day=1)
        first_monday = first_day_of_month
        while first_monday.weekday() != 0:  # 0 is Monday
            first_monday += timedelta(days=1)
        
        # Calculate week number
        if monday < first_monday:
            # This week spans the previous month
            if monday.month == 1:
                prev_month = 12
                prev_year = monday.year - 1
            else:
                prev_month = monday.month - 1
                prev_year = monday.year
            
            # Get the last day of previous month
            last_day_prev_month = first_day_of_month - timedelta(days=1)
            # Get its Monday
            prev_monday = last_day_prev_month - timedelta(days=last_day_prev_month.weekday())
            return get_week_key_from_date(prev_monday)
        
        week_diff = (monday - first_monday).days
        week_number = (week_diff // 7) + 1
        
        # Use "Week" as English term for consistency in database
        return f"Week {week_number} - {monday.month:02d}/{monday.year}"
    
    # Update all existing records
    for report in HiredCandidateReport.objects.all():
        report.week_key = get_week_key_from_date(report.report_date)
        report.save(update_fields=['week_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0023_hiredcandidatereport_recruitmentchannelreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredcandidatereport',
            name='week_key',
            field=models.CharField(blank=True, db_index=True, help_text='Format: Week W - MM/YYYY for weekly aggregation', max_length=20, null=True, verbose_name='Week key'),
        ),
        migrations.RunPython(populate_week_key, reverse_code=migrations.RunPython.noop),
    ]
