# Generated by Django 5.2.6 on 2025-10-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0024_update_recruitment_channel_belong_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentcandidate',
            name='years_of_experience',
            field=models.CharField(choices=[('NO_EXPERIENCE', 'No Experience'), ('LESS_THAN_ONE_YEAR', 'Less Than One Year'), ('ONE_TO_THREE_YEARS', '1-3 Years'), ('THREE_TO_FIVE_YEARS', '3-5 Years'), ('MORE_THAN_FIVE_YEARS', 'More Than 5 Years')], default='NO_EXPERIENCE', max_length=30, verbose_name='Years of experience'),
        ),
        migrations.AlterField(
            model_name='recruitmentchannel',
            name='belong_to',
            field=models.CharField(blank=True, choices=[('job_website', 'Job Website'), ('marketing', 'Marketing'), ('hunt', 'Hunt'), ('school', 'School'), ('other', 'Other')], default='', max_length=20, verbose_name='Belong to'),
        ),
    ]
