# Generated by Django 5.2.6 on 2025-12-26 08:54

import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0025_alter_bank_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_daily_reports",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="employee",
            field=models.OneToOneField(
                help_text="Employee to be exempt from attendance tracking",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_exemption",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Mã Số Thuế"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee associated with this attendance record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_timesheets",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="note",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Ghi Chú"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="note",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Ghi Chú"),
        ),
        migrations.AlterField(
            model_name="proposaltimesheetentry",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timesheet_entries",
                to="hrm.proposal",
                verbose_name="Proposal",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidate_contact_logs",
                to="hrm.employee",
                verbose_name="Nhân sự",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="note",
            field=models.TextField(blank=True, verbose_name="Ghi Chú"),
        ),
    ]
