# Generated by Django 5.2.6 on 2025-12-26 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0026_alter_attendancedailyreport_employee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="device_change_contact_info",
        ),
    ]
