# Generated by Django 5.2.6 on 2025-12-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0027_remove_proposal_device_change_contact_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_geolocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Geolocation reference (for geolocation attendance)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="hrm.attendancegeolocation",
                verbose_name="chấm Công GPS",
            ),
        ),
    ]
