# Generated by Django 5.2.6 on 2025-10-31 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_add_uploaded_by_field'),
        ('hrm', '0028_employee_is_onboarding_email_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_type', models.CharField(choices=[('foreign_language', 'Foreign language certificate'), ('computer', 'Computer certificate'), ('diploma', 'Graduation diploma'), ('other', 'Other'), ('broker_training_completion', 'Broker training completion'), ('real_estate_practice_license', 'Real estate practice license')], help_text='Type of certificate', max_length=50, verbose_name='Certificate type')),
                ('certificate_code', models.CharField(editable=False, help_text='Auto-generated certificate code based on certificate type', max_length=20, verbose_name='Certificate code')),
                ('certificate_name', models.CharField(blank=True, help_text='Specific name of the certificate or exam', max_length=255, verbose_name='Certificate name')),
                ('issue_date', models.DateField(blank=True, help_text='Date when the certificate was issued', null=True, verbose_name='Issue date')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when the certificate expires (if applicable)', null=True, verbose_name='Expiry date')),
                ('issuing_organization', models.CharField(blank=True, help_text='Organization that issued the certificate', max_length=255, verbose_name='Issuing organization')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the certificate', verbose_name='Notes')),
                ('employee', models.ForeignKey(help_text='Employee who owns this certificate', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='hrm.employee', verbose_name='Employee')),
                ('file', models.ForeignKey(blank=True, help_text='Uploaded certificate file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_certificates', to='files.filemodel', verbose_name='Certificate file')),
            ],
            options={
                'verbose_name': 'Employee certificate',
                'verbose_name_plural': 'Employee certificates',
                'db_table': 'hrm_employee_certificate',
                'ordering': ['certificate_code', '-issue_date'],
                'indexes': [models.Index(fields=['employee', 'certificate_type'], name='hrm_employe_employe_287b98_idx'), models.Index(fields=['certificate_code'], name='hrm_employe_certifi_f69eb7_idx'), models.Index(fields=['issue_date'], name='hrm_employe_issue_d_2a8496_idx'), models.Index(fields=['expiry_date'], name='hrm_employe_expiry__e902ce_idx')],
            },
        ),
    ]
