# Generated by Django 5.2.6 on 2025-12-31 03:24

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0028_alter_attendancerecord_attendance_geolocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeemonthlytimesheet",
            name="holiday_overtime_hours",
        ),
        migrations.RemoveField(
            model_name="employeemonthlytimesheet",
            name="saturday_in_week_overtime_hours",
        ),
        migrations.RemoveField(
            model_name="employeemonthlytimesheet",
            name="sunday_overtime_hours",
        ),
        migrations.AddField(
            model_name="employeemonthlytimesheet",
            name="early_leaving_minutes",
            field=models.IntegerField(default=0, verbose_name="Số phút về sớm"),
        ),
        migrations.AddField(
            model_name="employeemonthlytimesheet",
            name="late_coming_minutes",
            field=models.IntegerField(default=0, verbose_name="Số phút đi muộn"),
        ),
        migrations.AddField(
            model_name="employeemonthlytimesheet",
            name="tc1_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="TC1 overtime hours (Weekday)"
            ),
        ),
        migrations.AddField(
            model_name="employeemonthlytimesheet",
            name="tc2_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="TC2 overtime hours (Weekend)"
            ),
        ),
        migrations.AddField(
            model_name="employeemonthlytimesheet",
            name="tc3_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="TC3 overtime hours (Holiday)"
            ),
        ),
        migrations.AddField(
            model_name="employeemonthlytimesheet",
            name="total_penalty_count",
            field=models.IntegerField(default=0, verbose_name="Tổng số lần bị phạt"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="allowed_late_minutes",
            field=models.IntegerField(default=0, verbose_name="Allowed late minutes"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="allowed_late_minutes_reason",
            field=models.CharField(
                blank=True,
                choices=[("standard", "Standard"), ("maternity", "Maternity"), ("late_exemption", "Late exemption")],
                max_length=32,
                null=True,
                verbose_name="Allowed late minutes reason",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="approved_ot_end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Approved OT End Time"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="approved_ot_minutes",
            field=models.IntegerField(default=0, verbose_name="Approved OT Minutes"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="approved_ot_start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Approved OT Start Time"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="compensation_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Compensation value"
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                help_text="Snapshot of the active contract at the time of creation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrm.contract",
                verbose_name="Contract",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="early_minutes",
            field=models.IntegerField(default=0, verbose_name="Early minutes"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="is_exempt",
            field=models.BooleanField(
                default=False,
                help_text="Whether the employee is exempt from attendance tracking (e.g., Board of Directors).",
                verbose_name="Is exempt",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="is_punished",
            field=models.BooleanField(default=False, verbose_name="Is punished"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="late_minutes",
            field=models.IntegerField(default=0, verbose_name="Late minutes"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="net_percentage",
            field=models.IntegerField(
                default=100, help_text="Snapshot of the contract net percentage.", verbose_name="Net percentage"
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="ot_end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="OT End Time"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="ot_start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="OT Start Time"),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="ot_tc1_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="OT TC1 (Weekday) hours"
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="ot_tc2_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="OT TC2 (Weekend) hours"
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="ot_tc3_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="OT TC3 (Holiday) hours"
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="paid_leave_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Paid leave hours"
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="date",
            field=models.DateField(verbose_name="Ngày liên hệ"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="method",
            field=models.CharField(max_length=100, verbose_name="Phương thức liên hệ"),
        ),
    ]
