# Generated by Django 5.2.6 on 2025-12-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0029_remove_employeemonthlytimesheet_holiday_overtime_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="early_leaving_minutes",
            field=models.IntegerField(default=0, verbose_name="Early leaving minutes"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="late_coming_minutes",
            field=models.IntegerField(default=0, verbose_name="Late coming minutes"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="total_penalty_count",
            field=models.IntegerField(default=0, verbose_name="Total penalty count"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="date",
            field=models.DateField(verbose_name="Contact date"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="method",
            field=models.CharField(max_length=100, verbose_name="Contact method"),
        ),
    ]
