# Generated by Django 5.2.6 on 2025-12-31 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0028_alter_attendancerecord_attendance_geolocation"),
        ("hrm", "0029_alter_attendancedailyreport_options_and_more"),
    ]

    operations = []
