# Generated by Django 5.2.6 on 2025-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0030_employeerelationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerelationship",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("CHILD", "Child"),
                    ("WIFE", "Wife"),
                    ("HUSBAND", "Husband"),
                    ("FATHER", "Father"),
                    ("MONTHER", "Monther"),
                    ("BROTHER", "Brother"),
                    ("SISTER", "Sister"),
                    ("SIBLING", "Sibling"),
                    ("GRANDFATHER", "Grandfather"),
                    ("GRANDMOTHER", "Grandmother"),
                    ("OTHER", "Other"),
                ],
                help_text="Type of relationship to the employee",
                max_length=20,
                verbose_name="Relation type",
            ),
        ),
    ]
