# Generated by Django 5.2.6 on 2025-12-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0030_remove_department_assignment_source_add_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="early_leaving_minutes",
            field=models.IntegerField(default=0, verbose_name="Số phút về sớm"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="late_coming_minutes",
            field=models.IntegerField(default=0, verbose_name="Số phút đi muộn"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="total_penalty_count",
            field=models.IntegerField(default=0, verbose_name="Tổng số lần bị phạt"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="date",
            field=models.DateField(verbose_name="Ngày liên hệ"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="method",
            field=models.CharField(max_length=100, verbose_name="Phương thức liên hệ"),
        ),
    ]
