# Generated by Django 5.2.6 on 2025-12-31 11:16

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        ("hrm", "0031_alter_employeemonthlytimesheet_early_leaving_minutes_and_more"),
        ("realestate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancedailyreport",
            options={
                "verbose_name": "Attendance Daily Report",
                "verbose_name_plural": "Attendance Daily Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="attendanceexemption",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Attendance Exemption",
                "verbose_name_plural": "Attendance Exemptions",
            },
        ),
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
            },
        ),
        migrations.AlterModelOptions(
            name="bank",
            options={
                "ordering": ["id"],
                "verbose_name": "Bank",
                "verbose_name_plural": "Banks",
            },
        ),
        migrations.AlterModelOptions(
            name="employeemonthlytimesheet",
            options={
                "verbose_name": "Employee monthly timesheet",
                "verbose_name_plural": "Employee monthly timesheets",
            },
        ),
        migrations.AlterModelOptions(
            name="employeeresignedreasonreport",
            options={
                "verbose_name": "Employee Resigned Reason Report",
                "verbose_name_plural": "Employee Resigned Reason Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="employeestatusbreakdownreport",
            options={
                "verbose_name": "Employee Status Breakdown Report",
                "verbose_name_plural": "Employee Status Breakdown Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="interviewcandidate",
            options={
                "ordering": ["interview_time"],
                "verbose_name": "Interview Candidate",
                "verbose_name_plural": "Interview Candidates",
            },
        ),
        migrations.AlterModelOptions(
            name="jobdescription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Job Description",
                "verbose_name_plural": "Job Descriptions",
            },
        ),
        migrations.AlterModelOptions(
            name="recruitmentcandidatecontactlog",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Recruitment Candidate Contact Log",
                "verbose_name_plural": "Recruitment Candidate Contact Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="recruitmentsource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Recruitment Source",
                "verbose_name_plural": "Recruitment Sources",
            },
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="attendance_method",
            field=models.CharField(
                choices=[
                    ("biometric_device", "Biometric Device"),
                    ("wifi", "WiFi"),
                    ("geolocation", "GeoLocation"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Attendance type",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="attendance_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_reports",
                to="hrm.attendancerecord",
                verbose_name="Attendance record",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.block",
                verbose_name="Block",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.branch",
                verbose_name="Branch",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_daily_reports",
                to="hrm.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedailyreport",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="realestate.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="effective_date",
            field=models.DateField(
                blank=True,
                help_text="Date when exemption becomes active",
                null=True,
                verbose_name="Effective Date",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="employee",
            field=models.OneToOneField(
                help_text="Employee to be exempt from attendance tracking",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_exemption",
                to="hrm.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceexemption",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes or remarks",
                max_length=1000,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when this record was approved",
                null=True,
                verbose_name="Approved at",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee who approved this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_attendance_records",
                to="hrm.employee",
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_code",
            field=models.CharField(
                blank=True,
                help_text="User ID from device, used to match with Employee.attendance_code",
                max_length=20,
                verbose_name="Attendance code",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_geolocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Geolocation reference (for geolocation attendance)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="hrm.attendancegeolocation",
                verbose_name="Attendance geolocation",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("biometric_device", "Biometric Device"),
                    ("wifi", "WiFi"),
                    ("geolocation", "GeoLocation"),
                    ("other", "Other"),
                ],
                default="biometric_device",
                help_text="Type of attendance method used",
                max_length=20,
                verbose_name="Attendance type",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_wifi_device",
            field=models.ForeignKey(
                blank=True,
                help_text="WiFi device reference (for WiFi attendance)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="hrm.attendancewifidevice",
                verbose_name="WiFi device",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="biometric_device",
            field=models.ForeignKey(
                blank=True,
                help_text="Attendance device that captured this record (for biometric device type)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="hrm.attendancedevice",
                verbose_name="Biometric Device",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee associated with this attendance record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="hrm.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Attendance photo (for geolocation attendance)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="files.filemodel",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="is_pending",
            field=models.BooleanField(
                default=False,
                help_text="Whether this attendance record is pending approval",
                verbose_name="Is pending",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="is_valid",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Whether this attendance record is valid",
                null=True,
                verbose_name="Is valid",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="GeoLocation latitude coordinate (for geolocation attendance)",
                max_digits=20,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="GeoLocation longitude coordinate (for geolocation attendance)",
                max_digits=20,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="notes",
            field=libs.models.fields.SafeTextField(
                blank=True,
                help_text="Additional notes or comments about this attendance record",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="raw_data",
            field=models.JSONField(
                blank=True,
                help_text="Complete raw data from device for debugging purposes",
                null=True,
                verbose_name="Raw data",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="timestamp",
            field=models.DateTimeField(
                help_text="Date and time when attendance was recorded",
                verbose_name="Timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Bank code"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Bank name"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="carried_over_leave",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Carried over leave from last year. Only applied for January. After that, this field must be set to 0.",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="consumed_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Consumed leave days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="early_leaving_minutes",
            field=models.IntegerField(default=0, verbose_name="Early leaving minutes"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_timesheets",
                to="hrm.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="generated_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Generated leave days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="late_coming_minutes",
            field=models.IntegerField(default=0, verbose_name="Late coming minutes"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="maternity_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Maternity leave days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="month_key",
            field=models.CharField(max_length=6, verbose_name="Month key"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="note",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="official_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Official hours",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="official_working_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="Official working days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="opening_balance_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Opening balance leave days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Overtime hours",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="paid_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Paid leave days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="probation_working_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="Probation working days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="public_holiday_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Public holiday days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="remaining_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Remaining leave days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="report_date",
            field=models.DateField(verbose_name="Report date"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="total_penalty_count",
            field=models.IntegerField(default=0, verbose_name="Total penalty count"),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="total_worked_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sum of official_hours and overtime_hours",
                max_digits=8,
                verbose_name="Total worked hours",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="total_working_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="Total working days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="unexcused_absence_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Unexcused absence days",
            ),
        ),
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="unpaid_leave_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Unpaid leave days",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="agreement_termination",
            field=models.IntegerField(default=0, verbose_name="Agreement Termination"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.block",
                verbose_name="Block",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.branch",
                verbose_name="Branch",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="contract_expired",
            field=models.IntegerField(default=0, verbose_name="Contract Expired"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="count_resigned",
            field=models.IntegerField(default=0, verbose_name="Resigned count"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="disciplinary_termination",
            field=models.IntegerField(default=0, verbose_name="Disciplinary Termination"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="job_abandonment",
            field=models.IntegerField(default=0, verbose_name="Job Abandonment"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="other",
            field=models.IntegerField(default=0, verbose_name="Other"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="probation_fail",
            field=models.IntegerField(default=0, verbose_name="Probation Fail"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="underperforming",
            field=models.IntegerField(default=0, verbose_name="Underperforming"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="voluntary_career_change",
            field=models.IntegerField(default=0, verbose_name="Voluntary - Career Change"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="voluntary_health",
            field=models.IntegerField(default=0, verbose_name="Voluntary - Health Reasons"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="voluntary_other",
            field=models.IntegerField(default=0, verbose_name="Voluntary - Other"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="voluntary_personal",
            field=models.IntegerField(default=0, verbose_name="Voluntary - Personal Reasons"),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="workforce_reduction",
            field=models.IntegerField(default=0, verbose_name="Workforce Reduction"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.block",
                verbose_name="Block",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.branch",
                verbose_name="Branch",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_active",
            field=models.IntegerField(default=0, verbose_name="Active count"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_maternity_leave",
            field=models.IntegerField(default=0, verbose_name="Maternity leave count"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_onboarding",
            field=models.IntegerField(default=0, verbose_name="Onboarding count"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_resigned",
            field=models.IntegerField(default=0, verbose_name="Resigned count"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_resigned_reasons",
            field=models.JSONField(default=dict, verbose_name="Resignation reasons breakdown"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="count_unpaid_leave",
            field=models.IntegerField(default=0, verbose_name="Unpaid leave count"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hrm.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="total_not_resigned",
            field=models.IntegerField(default=0, verbose_name="Total not resigned"),
        ),
        migrations.AlterField(
            model_name="interviewcandidate",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Email sent at"),
        ),
        migrations.AlterField(
            model_name="interviewcandidate",
            name="interview_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_candidates",
                to="hrm.interviewschedule",
                verbose_name="Interview schedule",
            ),
        ),
        migrations.AlterField(
            model_name="interviewcandidate",
            name="interview_time",
            field=models.DateTimeField(verbose_name="Interview time"),
        ),
        migrations.AlterField(
            model_name="interviewcandidate",
            name="recruitment_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_candidates",
                to="hrm.recruitmentcandidate",
                verbose_name="Recruitment candidate",
            ),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_descriptions",
                to="files.filemodel",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="benefit",
            field=libs.models.fields.SafeTextField(verbose_name="Benefit"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Job description code"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="note",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="position_title",
            field=models.CharField(max_length=255, verbose_name="Position title"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="preferred_criteria",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Preferred criteria"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="proposed_salary",
            field=models.CharField(max_length=100, verbose_name="Proposed salary"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="requirement",
            field=libs.models.fields.SafeTextField(verbose_name="Requirement"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="responsibility",
            field=libs.models.fields.SafeTextField(verbose_name="Responsibility"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Job title"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="date",
            field=models.DateField(verbose_name="Contact date"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidate_contact_logs",
                to="hrm.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="method",
            field=models.CharField(max_length=100, verbose_name="Contact method"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="note",
            field=models.TextField(blank=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="recruitment_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_logs",
                to="hrm.recruitmentcandidate",
                verbose_name="Recruitment candidate",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Source code"),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="description",
            field=libs.models.fields.SafeTextField(blank=True, max_length=500, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Source name"),
        ),
        migrations.AlterField(
            model_name="timesheetentry",
            name="working_days",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                null=True,
                verbose_name="Working days",
            ),
        ),
    ]
