# Generated by Django 5.2.6 on 2025-10-31 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.hrm.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_add_uploaded_by_field'),
        ('hrm', '0031_alter_employeerelationship_relation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependent_name', models.CharField(help_text='Full name of the dependent', max_length=255, verbose_name='Dependent name')),
                ('relationship', models.CharField(choices=[('CHILD', 'Child'), ('WIFE', 'Wife'), ('HUSBAND', 'Husband'), ('FATHER', 'Father'), ('MONTHER', 'Monther'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('SIBLING', 'Sibling'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('OTHER', 'Other')], help_text='Type of relationship to the employee', max_length=20, verbose_name='Relationship')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth of the dependent', null=True, verbose_name='Date of birth')),
                ('id_number', models.CharField(blank=True, help_text='National ID (CMND/CCCD) - 9 or 12 digits', max_length=12, validators=[apps.hrm.utils.validators.validate_national_id], verbose_name='ID number')),
                ('note', models.TextField(blank=True, help_text='Additional notes or information', verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this dependent record is active', verbose_name='Is active')),
                ('attachment', models.ForeignKey(blank=True, help_text='Supporting document or file attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_dependents', to='files.filemodel', verbose_name='Attachment')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dependents', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(help_text='Employee associated with this dependent', on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='hrm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Dependent',
                'verbose_name_plural': 'Employee Dependents',
                'db_table': 'hrm_employee_dependent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='hrm_employe_employe_12d73e_idx'), models.Index(fields=['id_number'], name='hrm_employe_id_numb_1cb2b2_idx'), models.Index(fields=['dependent_name'], name='hrm_employe_depende_7640f0_idx'), models.Index(fields=['relationship'], name='hrm_employe_relatio_3054f9_idx')],
            },
        ),
    ]
