# Generated by Django 5.2.6 on 2025-11-03 04:38

from django.conf import settings
from django.db import migrations, models

import apps.hrm.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_add_uploaded_by_field"),
        ("hrm", "0033_rename_id_fields_to_citizen_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="employeedependent",
            name="hrm_employe_id_numb_1cb2b2_idx",
        ),
        migrations.RemoveIndex(
            model_name="employeerelationship",
            name="hrm_employe_nationa_2a1f6a_idx",
        ),
        migrations.AlterField(
            model_name="employeedependent",
            name="citizen_id",
            field=models.CharField(
                blank=True,
                help_text="National ID (CMND/CCCD) - 9 or 12 digits",
                max_length=12,
                validators=[apps.hrm.utils.validators.validate_national_id],
                verbose_name="Citizen ID",
            ),
        ),
        migrations.AlterField(
            model_name="employeerelationship",
            name="citizen_id",
            field=models.CharField(
                blank=True,
                help_text="National ID (CMND/CCCD) - 9 or 12 digits",
                max_length=12,
                validators=[apps.hrm.utils.validators.validate_national_id],
                verbose_name="Citizen ID",
            ),
        ),
        migrations.AddIndex(
            model_name="employeedependent",
            index=models.Index(fields=["citizen_id"], name="hrm_employe_citizen_1858af_idx"),
        ),
        migrations.AddIndex(
            model_name="employeerelationship",
            index=models.Index(fields=["citizen_id"], name="hrm_employe_citizen_2b54df_idx"),
        ),
    ]
