# Generated by Django 5.2.6 on 2026-01-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0034_alter_attendancedailyreport_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(max_length=100, unique=True, verbose_name="Personal email"),
        ),
    ]
