# Generated by Django 5.2.6 on 2025-11-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0034_remove_employeedependent_hrm_employe_id_numb_1cb2b2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecertificate',
            name='status',
            field=models.CharField(
                choices=[
                    ('Valid', 'Valid'),
                    ('Near_expiry', 'Near expiry'),
                    ('Expired', 'Expired')
                ],
                default='Valid',
                help_text='Certificate status based on expiry date',
                max_length=20,
                verbose_name='Status',
                db_index=True,
            ),
        ),
        migrations.AddIndex(
            model_name='employeecertificate',
            index=models.Index(fields=['status'], name='hrm_employe_status_abc123_idx'),
        ),
    ]
