# Generated by Django 5.2.6 on 2026-01-06 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0035_alter_employee_personal_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentcandidate",
            name="citizen_id",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Citizen ID must contain from 9 to 12 digits", regex="^\\d{9,12}$"
                    )
                ],
                verbose_name="Citizen ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="recruitmentcandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("citizen_id__isnull", False)),
                fields=("citizen_id",),
                name="unique_citizen_id_when_not_null",
            ),
        ),
    ]
