# Generated by Django 5.2.6 on 2025-11-03 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0035_add_certificate_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employeecertificate",
            new_name="hrm_employe_status_320c12_idx",
            old_name="hrm_employe_status_abc123_idx",
        ),
    ]
