# Generated by Django 5.2.6 on 2026-01-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0036_alter_recruitmentcandidate_citizen_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="approve_status",
            field=models.CharField(
                choices=[("APPROVED", "Đã duyệt"), ("REJECTED", "Đã từ chối"), ("PENDING", "Đang chờ")],
                default="APPROVED",
                help_text="Approval status of this attendance record",
                max_length=20,
                verbose_name="Trạng thái duyệt",
            ),
        ),
    ]
