# Generated by Django 5.2.6 on 2025-11-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0036_rename_hrm_employe_status_abc123_idx_hrm_employe_status_320c12_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecertificate',
            old_name='file',
            new_name='attachment',
        ),
    ]
