# Generated by Django 5.2.6 on 2025-11-03 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0037_attendancedevice_attendancerecord"),
        ("hrm", "0037_rename_file_to_attachment_employee_certificate"),
    ]

    operations = []
