# Generated by Django 5.2.6 on 2026-01-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0037_attendancerecord_approve_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="approve_status",
            field=models.CharField(
                choices=[("APPROVED", "Đã duyệt"), ("REJECTED", "Đã từ chối"), ("PENDING", "Đang chờ")],
                db_index=True,
                default="APPROVED",
                help_text="Approval status of this attendance record",
                max_length=20,
                verbose_name="Trạng thái duyệt",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="User ID from device, used to match with Employee.attendance_code",
                max_length=20,
                verbose_name="Mã Chấm Công",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("biometric_device", "Biometric Device"),
                    ("wifi", "WiFi"),
                    ("geolocation", "GeoLocation"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="biometric_device",
                help_text="Type of attendance method used",
                max_length=20,
                verbose_name="Phương thức chấm công",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="is_pending",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this attendance record is pending approval",
                verbose_name="Đang chờ",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="is_valid",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=True,
                help_text="Whether this attendance record is valid",
                null=True,
                verbose_name="Còn hiệu lực",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True,
                help_text="Date and time when attendance was recorded",
                verbose_name="Thời gian Ghi nhận",
            ),
        ),
    ]
