# Generated by Django 5.2.6 on 2026-01-07 17:13

from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0038_alter_attendancerecord_approve_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemonthlytimesheet",
            name="note",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Ghi chú"),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="note",
            field=libs.models.fields.SafeTextField(blank=True, verbose_name="Ghi chú"),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidatecontactlog",
            name="note",
            field=models.TextField(blank=True, verbose_name="Ghi chú"),
        ),
    ]
