# Generated by Django 5.2.6 on 2025-11-03 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0038_merge_20251103_1443"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Bank name")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Bank code")),
            ],
            options={
                "verbose_name": "Bank",
                "verbose_name_plural": "Banks",
                "db_table": "hrm_bank",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="recruitment_candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hrm.recruitmentcandidate",
                verbose_name="Recruitment Candidate",
            ),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(max_length=20, verbose_name="Account number")),
                ("account_name", models.CharField(max_length=50, verbose_name="Account name")),
                ("is_primary", models.BooleanField(default=False, verbose_name="Is primary")),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="hrm.bank",
                        verbose_name="Bank",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "db_table": "hrm_bank_account",
                "ordering": ["-is_primary", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("employee",),
                        name="unique_primary_bank_account_per_employee",
                    )
                ],
            },
        ),
    ]
