# Generated by Django 5.2.6 on 2026-01-08 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_add_role_data_scope"),
        ("hrm", "0039_alter_employeemonthlytimesheet_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleBlockScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_scopes",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_scopes",
                        to="core.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Block Scope",
                "verbose_name_plural": "Role Block Scopes",
                "db_table": "hrm_role_block_scope",
                "unique_together": {("role", "block")},
            },
        ),
        migrations.CreateModel(
            name="RoleBranchScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_scopes",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_scopes",
                        to="core.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Branch Scope",
                "verbose_name_plural": "Role Branch Scopes",
                "db_table": "hrm_role_branch_scope",
                "unique_together": {("role", "branch")},
            },
        ),
        migrations.CreateModel(
            name="RoleDepartmentScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_scopes",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_scopes",
                        to="core.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Department Scope",
                "verbose_name_plural": "Role Department Scopes",
                "db_table": "hrm_role_department_scope",
                "unique_together": {("role", "department")},
            },
        ),
    ]
