# Generated by Django 5.2.6 on 2025-11-03 09:26

import django.core.validators
from django.conf import settings
from django.db import migrations, models
from django.utils.crypto import get_random_string


def generate_random_citizen_id(existing_id):
    """Generate a random 12-digit string for citizen_id"""
    allowed_chars = "0123456789"
    # Use existing_id to add some uniqueness, then pad with random digits
    return f"0{existing_id}{get_random_string(9, allowed_chars)}"[:12]


def populate_employee_data(apps, schema_editor):
    """Add default random citizen_id to existing employees without one"""
    Employee = apps.get_model("hrm", "Employee")

    employees_to_update = []
    used_ids = set()

    # Get existing citizen_ids to avoid duplicates
    for emp in Employee.objects.exclude(citizen_id="").values_list("citizen_id", flat=True):
        used_ids.add(emp)

    # Generate unique citizen_ids for employees without one
    for employee in Employee.objects.filter(citizen_id=""):
        attempts = 0
        max_attempts = 1000  # Prevent infinite loops
        while attempts < max_attempts:
            new_id = generate_random_citizen_id(employee.id)
            if new_id not in used_ids:
                used_ids.add(new_id)
                employee.citizen_id = new_id
                employees_to_update.append(employee)
                break
            attempts += 1

        if attempts >= max_attempts:
            raise ValueError(
                f"Failed to generate unique citizen_id for employee {employee.id} after {max_attempts} attempts"
            )

    for employee in Employee.objects.all():
        employee.tax_code = (
            f"{employee.tax_code}{employee.id}"[:12] or f"{employee.id}{get_random_string(9, '0123456789')}"[:12]
        )
        employees_to_update.append(employee)

    if employees_to_update:
        Employee.objects.bulk_update(employees_to_update, ["citizen_id", "tax_code"])


def populate_recruitment_candidate_citizen_id(apps, schema_editor):
    """Add default random citizen_id to existing candidates without valid one"""
    RecruitmentCandidate = apps.get_model("hrm", "RecruitmentCandidate")

    candidates_to_update = []
    used_ids = set()

    # Single pass: collect valid IDs and identify candidates needing updates
    for candidate in RecruitmentCandidate.objects.all():
        if candidate.citizen_id and len(candidate.citizen_id) == 12 and candidate.citizen_id.isdigit():
            used_ids.add(candidate.citizen_id)
        else:
            candidates_to_update.append(candidate)

    # Generate unique citizen_ids for candidates without valid one
    for candidate in candidates_to_update:
        attempts = 0
        max_attempts = 1000  # Prevent infinite loops
        while attempts < max_attempts:
            new_id = generate_random_citizen_id(candidate.id)
            if new_id not in used_ids:
                used_ids.add(new_id)
                candidate.citizen_id = new_id
                break
            attempts += 1

        if attempts >= max_attempts:
            raise ValueError(
                f"Failed to generate unique citizen_id for candidate {candidate.id} after {max_attempts} attempts"
            )

    if candidates_to_update:
        RecruitmentCandidate.objects.bulk_update(candidates_to_update, ["citizen_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_nationality"),
        ("files", "0002_add_uploaded_by_field"),
        ("hrm", "0039_bank_employee_recruitment_candidate_bankaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, populate missing/invalid citizen_ids with random values
        migrations.RunPython(
            populate_employee_data,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            populate_recruitment_candidate_citizen_id,
            reverse_code=migrations.RunPython.noop,
        ),
        # Then make the fields required and unique
        migrations.AlterField(
            model_name="employee",
            name="citizen_id",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Citizen ID must contain exactly 12 digits", regex="^\\d{12}$"
                    )
                ],
                verbose_name="Citizen ID",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidate",
            name="citizen_id",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Citizen ID must contain exactly 12 digits", regex="^\\d{12}$"
                    )
                ],
                verbose_name="Citizen ID",
            ),
        ),
        # Add constraint for tax_code uniqueness when not null
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(tax_code__isnull=False) & ~models.Q(tax_code=""),
                fields=("tax_code",),
                name="unique_tax_code_when_not_null",
            ),
        ),
    ]
