# Generated by Django 5.2.6 on 2025-11-04 05:58

from django.db import migrations


def fix_monther_to_mother(apps, schema_editor):
    """Update MONTHER to MOTHER in all relationship fields."""
    EmployeeDependent = apps.get_model("hrm", "EmployeeDependent")
    EmployeeRelationship = apps.get_model("hrm", "EmployeeRelationship")

    # Fix EmployeeDependent.relationship field
    dependent_count = EmployeeDependent.objects.filter(relationship="MONTHER").update(relationship="MOTHER")
    
    # Fix EmployeeRelationship.relation_type field
    relationship_count = EmployeeRelationship.objects.filter(relation_type="MONTHER").update(relation_type="MOTHER")
    
    if dependent_count > 0 or relationship_count > 0:
        print(f"Fixed typo: Updated {dependent_count} dependent(s) and {relationship_count} relationship(s) from MONTHER to MOTHER")


def reverse_fix_monther_to_mother(apps, schema_editor):
    """Reverse the fix by changing MOTHER back to MONTHER."""
    EmployeeDependent = apps.get_model("hrm", "EmployeeDependent")
    EmployeeRelationship = apps.get_model("hrm", "EmployeeRelationship")

    # Reverse EmployeeDependent.relationship field
    dependent_count = EmployeeDependent.objects.filter(relationship="MOTHER").update(relationship="MONTHER")
    
    # Reverse EmployeeRelationship.relation_type field
    relationship_count = EmployeeRelationship.objects.filter(relation_type="MOTHER").update(relation_type="MONTHER")
    
    if dependent_count > 0 or relationship_count > 0:
        print(f"Reversed fix: Updated {dependent_count} dependent(s) and {relationship_count} relationship(s) from MOTHER to MONTHER")


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0041_add_code_fields_and_typo_fix'),
    ]

    operations = [
        migrations.RunPython(fix_monther_to_mother, reverse_fix_monther_to_mother),
    ]
