# Generated by Django 5.2.6 on 2025-11-04 05:59

from django.db import migrations


def generate_model_code_migration(instance, code_prefix):
    """Generate a code for a model instance based on its ID and class prefix.

    This is a copy of the generate_model_code function for use in migrations.
    """
    if instance.id is None:
        return None

    instance_id = instance.id

    # Format with at least 3 digits, but allow more if needed
    if instance_id < 1000:
        subcode = f"{instance_id:03d}"
    else:
        subcode = str(instance_id)

    return f"{code_prefix}{subcode}"


def backfill_employee_certificate_codes(apps, schema_editor):
    """Backfill codes for EmployeeCertificate records."""
    EmployeeCertificate = apps.get_model("hrm", "EmployeeCertificate")

    # Process in batches
    batch_size = 500
    certificates = EmployeeCertificate.objects.filter(code__isnull=True).order_by("id")

    updated_count = 0
    for certificate in certificates.iterator(chunk_size=batch_size):
        certificate.code = generate_model_code_migration(certificate, "EC")
        certificate.save(update_fields=["code"])
        updated_count += 1

    if updated_count > 0:
        print(f"Backfilled {updated_count} EmployeeCertificate code(s)")


def backfill_employee_dependent_codes(apps, schema_editor):
    """Backfill codes for EmployeeDependent records."""
    EmployeeDependent = apps.get_model("hrm", "EmployeeDependent")

    # Process in batches
    batch_size = 500
    dependents = EmployeeDependent.objects.filter(code__isnull=True).order_by("id")

    updated_count = 0
    for dependent in dependents.iterator(chunk_size=batch_size):
        dependent.code = generate_model_code_migration(dependent, "ED")
        dependent.save(update_fields=["code"])
        updated_count += 1

    if updated_count > 0:
        print(f"Backfilled {updated_count} EmployeeDependent code(s)")


def backfill_employee_relationship_codes(apps, schema_editor):
    """Backfill codes for EmployeeRelationship records."""
    EmployeeRelationship = apps.get_model("hrm", "EmployeeRelationship")

    # Process in batches
    batch_size = 500
    relationships = EmployeeRelationship.objects.filter(code__isnull=True).order_by("id")

    updated_count = 0
    for relationship in relationships.iterator(chunk_size=batch_size):
        relationship.code = generate_model_code_migration(relationship, "ER")
        relationship.save(update_fields=["code"])
        updated_count += 1

    if updated_count > 0:
        print(f"Backfilled {updated_count} EmployeeRelationship code(s)")


def reverse_backfill_codes(apps, schema_editor):
    """Reverse the backfill by setting codes back to NULL."""
    EmployeeCertificate = apps.get_model("hrm", "EmployeeCertificate")
    EmployeeDependent = apps.get_model("hrm", "EmployeeDependent")
    EmployeeRelationship = apps.get_model("hrm", "EmployeeRelationship")

    cert_count = EmployeeCertificate.objects.update(code=None)
    dep_count = EmployeeDependent.objects.update(code=None)
    rel_count = EmployeeRelationship.objects.update(code=None)

    print(f"Reversed backfill: Set {cert_count} certificate(s), {dep_count} dependent(s), and {rel_count} relationship(s) codes to NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0042_fix_monther_to_mother_data'),
    ]

    operations = [
        migrations.RunPython(backfill_employee_certificate_codes, reverse_backfill_codes),
        migrations.RunPython(backfill_employee_dependent_codes, migrations.RunPython.noop),
        migrations.RunPython(backfill_employee_relationship_codes, migrations.RunPython.noop),
    ]
