# Generated by Django 5.2.6 on 2025-11-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0043_backfill_code_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeWorkHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="Date of the work history event", verbose_name="Date")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Change Position", "Change Position"),
                            ("Change Status", "Change Status"),
                            ("Transfer", "Transfer"),
                        ],
                        help_text="Type of the work history event",
                        max_length=50,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, help_text="Detailed description of the work history event", verbose_name="Details"
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        help_text="Block (auto-populated from employee)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_work_histories",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch (auto-populated from employee)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_work_histories",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department (auto-populated from employee)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_work_histories",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee associated with this work history record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_histories",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Position (auto-populated from employee)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_work_histories",
                        to="hrm.position",
                        verbose_name="Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee work history",
                "verbose_name_plural": "Employee work histories",
                "db_table": "hrm_employee_work_history",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["employee", "date"], name="hrm_employe_employe_92aac1_idx"),
                    models.Index(fields=["branch"], name="hrm_employe_branch__0313ae_idx"),
                    models.Index(fields=["block"], name="hrm_employe_block_i_5c7432_idx"),
                    models.Index(fields=["department"], name="hrm_employe_departm_b2b69a_idx"),
                    models.Index(fields=["position"], name="hrm_employe_positio_47ccd7_idx"),
                    models.Index(fields=["date"], name="hrm_employe_date_84ca01_idx"),
                ],
            },
        ),
    ]
