# Generated by Django 5.2.6 on 2025-11-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0044_employeeworkhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedevice',
            name='delta_time_seconds',
            field=models.IntegerField(default=0, help_text='Time difference between system and device (system_time - device_time) in seconds', verbose_name='Delta time in seconds'),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='time_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when device time was last synchronized', null=True, verbose_name='Time last synchronized'),
        ),
    ]
