# Generated by Django 5.2.6 on 2025-11-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0044_employeeworkhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="resignation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGREEMENT_TERMINATION", "Agreement Termination"),
                    ("PROBATION_FAIL", "Probation Fail"),
                    ("JOB_ABANDONMENT", "Job Abandonment"),
                    ("DISCIPLINARY_TERMINATION", "Disciplinary Termination"),
                    ("WORKFORCE_REDUCTION", "Workforce Reduction"),
                    ("UNDERPERFORMING", "Underperforming"),
                    ("CONTRACT_EXPIRED", "Contract Expired"),
                    ("VOLUNTARY_HEALTH", "Voluntary - Health Reasons"),
                    ("VOLUNTARY_PERSONAL", "Voluntary - Personal Reasons"),
                    ("VOLUNTARY_CAREER_CHANGE", "Voluntary - Career Change"),
                    ("VOLUNTARY_OTHER", "Voluntary - Other"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="Resignation reason",
            ),
        ),
    ]
