# Generated by Django 5.2.6 on 2025-11-05 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0045_alter_employee_resignation_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeStatusBreakdownReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(db_index=True, verbose_name="Report date")),
                ("count_active", models.IntegerField(default=0, verbose_name="Active count")),
                ("count_onboarding", models.IntegerField(default=0, verbose_name="Onboarding count")),
                ("count_maternity_leave", models.IntegerField(default=0, verbose_name="Maternity leave count")),
                ("count_unpaid_leave", models.IntegerField(default=0, verbose_name="Unpaid leave count")),
                ("count_resigned", models.IntegerField(default=0, verbose_name="Resigned count")),
                ("total_not_resigned", models.IntegerField(default=0, verbose_name="Total not resigned")),
                (
                    "count_resigned_reasons",
                    models.JSONField(default=dict, verbose_name="Resignation reasons breakdown"),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Status Breakdown Report",
                "verbose_name_plural": "Employee Status Breakdown Reports",
                "db_table": "hrm_employee_status_breakdown_report",
                "indexes": [
                    models.Index(fields=["report_date"], name="hrm_employe_report__da1685_idx"),
                    models.Index(fields=["branch", "block", "department"], name="hrm_employe_branch__b02471_idx"),
                ],
                "unique_together": {("report_date", "branch", "block", "department")},
            },
        ),
    ]
