# Generated by Django 5.2.6 on 2025-11-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0046_employeestatusbreakdownreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="resignation_date",
        ),
        migrations.AddField(
            model_name="employee",
            name="resignation_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Resignation end date"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="resignation_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Resignation start date"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Onboarding", "Onboarding"),
                    ("Resigned", "Resigned"),
                    ("Maternity Leave", "Maternity Leave"),
                    ("Unpaid Leave", "Unpaid Leave"),
                ],
                default="Onboarding",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
