# Generated by Django 5.2.6 on 2025-11-06 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0047_remove_employee_resignation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="citizen_id",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Citizen ID must contain from 9 to 12 digits",
                        regex="^\\d{9,12}$",
                    )
                ],
                verbose_name="Citizen ID",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentcandidate",
            name="citizen_id",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Citizen ID must contain from 9 to 12 digits",
                        regex="^\\d{9,12}$",
                    )
                ],
                verbose_name="Citizen ID",
            ),
        ),
    ]
