# Generated by Django 5.2.6 on 2025-11-06 11:52

import django.db.models.deletion
import libs.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0048_alter_employee_citizen_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkhistory',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='New contract for contract-change event', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_work_histories', to='hrm.contracttype', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='employeeworkhistory',
            name='from_date',
            field=models.DateField(blank=True, help_text='Start date of the event period', null=True, verbose_name='From date'),
        ),
        migrations.AddField(
            model_name='employeeworkhistory',
            name='note',
            field=libs.models.fields.SafeTextField(blank=True, help_text='Additional notes about the work history event', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='employeeworkhistory',
            name='previous_data',
            field=models.JSONField(blank=True, help_text='JSON data storing previous values (status, branch_id, block_id, department_id, contract_type, contract_id)', null=True, verbose_name='Previous data'),
        ),
        migrations.AddField(
            model_name='employeeworkhistory',
            name='resignation_reason',
            field=models.CharField(blank=True, choices=[('AGREEMENT_TERMINATION', 'Agreement Termination'), ('PROBATION_FAIL', 'Probation Fail'), ('JOB_ABANDONMENT', 'Job Abandonment'), ('DISCIPLINARY_TERMINATION', 'Disciplinary Termination'), ('WORKFORCE_REDUCTION', 'Workforce Reduction'), ('UNDERPERFORMING', 'Underperforming'), ('CONTRACT_EXPIRED', 'Contract Expired'), ('VOLUNTARY_HEALTH', 'Voluntary - Health Reasons'), ('VOLUNTARY_PERSONAL', 'Voluntary - Personal Reasons'), ('VOLUNTARY_CAREER_CHANGE', 'Voluntary - Career Change'), ('VOLUNTARY_OTHER', 'Voluntary - Other'), ('OTHER', 'Other')], help_text='Reason for resignation (if applicable)', max_length=50, null=True, verbose_name='Resignation reason'),
        ),
        migrations.AddField(
            model_name='employeeworkhistory',
            name='retain_seniority',
            field=models.BooleanField(blank=True, help_text='For return to work events, whether seniority is retained or reset', null=True, verbose_name='Retain seniority'),
        ),
        migrations.AddField(
            model_name='employeeworkhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Onboarding', 'Onboarding'), ('Resigned', 'Resigned'), ('Maternity Leave', 'Maternity Leave'), ('Unpaid Leave', 'Unpaid Leave')], help_text='New employee status after the event (for state-change events)', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='employeeworkhistory',
            name='to_date',
            field=models.DateField(blank=True, help_text='End date of the event period', null=True, verbose_name='To date'),
        ),
        migrations.AlterField(
            model_name='employeeworkhistory',
            name='name',
            field=models.CharField(choices=[('Change Position', 'Change Position'), ('Change Status', 'Change Status'), ('Transfer', 'Transfer'), ('Change Contract', 'Change Contract')], help_text='Type of the work history event', max_length=50, verbose_name='Event type'),
        ),
    ]
