# Generated by Django 5.2.6 on 2025-11-11 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0051_add_return_to_work_event_type"),
        ("hrm", "0051_employeeresignedreasonreport"),
    ]

    operations = []
