# Generated by Django 5.2.6 on 2025-11-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0052_merge_20251111_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeresignedreasonreport",
            name="need_refresh",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if this report needs to be recalculated by batch task",
                verbose_name="Needs refresh",
            ),
        ),
        migrations.AddField(
            model_name="employeestatusbreakdownreport",
            name="need_refresh",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if this report needs to be recalculated by batch task",
                verbose_name="Needs refresh",
            ),
        ),
        migrations.AddField(
            model_name="hiredcandidatereport",
            name="need_refresh",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if this report needs to be recalculated by batch task",
                verbose_name="Needs refresh",
            ),
        ),
        migrations.AddField(
            model_name="recruitmentchannelreport",
            name="need_refresh",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if this report needs to be recalculated by batch task",
                verbose_name="Needs refresh",
            ),
        ),
        migrations.AddField(
            model_name="recruitmentcostreport",
            name="need_refresh",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if this report needs to be recalculated by batch task",
                verbose_name="Needs refresh",
            ),
        ),
        migrations.AddField(
            model_name="recruitmentsourcereport",
            name="need_refresh",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if this report needs to be recalculated by batch task",
                verbose_name="Needs refresh",
            ),
        ),
        migrations.AddField(
            model_name="staffgrowthreport",
            name="need_refresh",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if this report needs to be recalculated by batch task",
                verbose_name="Needs refresh",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresignedreasonreport",
            name="report_date",
            field=models.DateField(verbose_name="Report date"),
        ),
        migrations.AlterField(
            model_name="employeestatusbreakdownreport",
            name="report_date",
            field=models.DateField(verbose_name="Report date"),
        ),
    ]
