# Generated by Django 5.2.6 on 2025-11-13 04:20

from django.db import migrations, models


def generate_model_code_migration(instance, code_prefix):
    """Generate a code for a model instance based on its ID and class prefix.

    This is a copy of the generate_model_code function for use in migrations.
    """
    if instance.id is None:
        return None

    instance_id = instance.id

    # Format with at least 3 digits, but allow more if needed
    if instance_id < 1000:
        subcode = f"{instance_id:03d}"
    else:
        subcode = str(instance_id)

    return f"{code_prefix}{subcode}"


def set_code(apps, schema_editor):
    AttendanceDevice = apps.get_model("hrm", "AttendanceDevice")
    AttendanceRecord = apps.get_model("hrm", "AttendanceRecord")

    all_models = [(AttendanceDevice, "MC"), (AttendanceRecord, "DD")]
    for model, PREFIX in all_models:
        for record in model.objects.all():
            record.code = generate_model_code_migration(record, PREFIX)
            record.save()


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0053_employeeresignedreasonreport_need_refresh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancedevice",
            name="code",
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name="Code"),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="code",
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name="Code"),
        ),
        migrations.RunPython(set_code, migrations.RunPython.noop),
    ]
