# Generated by Django 5.2.6 on 2025-11-13 04:20

from django.db import migrations, models

from libs.code_generation import generate_model_code


def set_code(apps, schema_editor):
    AttendanceDevice = apps.get_model("hrm", "AttendanceDevice")
    AttendanceRecord = apps.get_model("hrm", "AttendanceRecord")

    all_models = [AttendanceDevice, AttendanceRecord]
    for model in all_models:
        for record in model.objects.all():
            record.code = generate_model_code(record)
            record.save()


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0053_employeeresignedreasonreport_need_refresh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancedevice",
            name="code",
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name="Code"),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="code",
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name="Code"),
        ),
        migrations.RunPython(set_code, migrations.RunPython.noop),
    ]
