# Generated by Django 5.2.6 on 2025-11-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0054_attendancedevice_code_attendancerecord_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancedevice",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Code"),
        ),
    ]
