# Generated by Django 5.2.6 on 2025-11-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0055_alter_attendancedevice_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancedevice",
            name="note",
            field=models.TextField(
                blank=True, default="", help_text="Additional notes or comments about the device", verbose_name="Note"
            ),
        ),
    ]
