# Generated by Django 5.2.6 on 2025-11-14 06:02

import django.core.validators
import django.db.models.deletion
import libs.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0055_alter_attendancedevice_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Project name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Project code')),
                ('description', libs.models.fields.SafeTextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'hrm_project',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Geolocation name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Geolocation code')),
                ('address', libs.models.fields.SafeTextField(blank=True, verbose_name='Address')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude coordinate', max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude coordinate', max_digits=10, verbose_name='Longitude')),
                ('radius_m', models.IntegerField(default=100, help_text='Radius in meters for geofencing', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Radius (meters)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('notes', libs.models.fields.SafeTextField(blank=True, verbose_name='Notes')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_geolocations', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geolocations', to='hrm.project', verbose_name='Project')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_geolocations', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Project Geolocation',
                'verbose_name_plural': 'Project Geolocations',
                'db_table': 'hrm_project_geolocation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='hrm_project_project_58c22e_idx'), models.Index(fields=['deleted'], name='hrm_project_deleted_ec071d_idx')],
            },
        ),
    ]
