# Generated by Django 5.2.6 on 2025-11-14 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0056_attendancedevice_note"),
        ("hrm", "0056_attendancegeolocation"),
    ]

    operations = []
