# Generated by Django 5.2.6 on 2025-11-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0057_merge_20251114_1447"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2, "Monday"),
                            (3, "Tuesday"),
                            (4, "Wednesday"),
                            (5, "Thursday"),
                            (6, "Friday"),
                            (7, "Saturday"),
                            (8, "Sunday"),
                        ],
                        help_text="Day of the week",
                        unique=True,
                        verbose_name="Weekday",
                    ),
                ),
                (
                    "morning_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Start time of morning session",
                        null=True,
                        verbose_name="Morning start time",
                    ),
                ),
                (
                    "morning_end_time",
                    models.TimeField(
                        blank=True, help_text="End time of morning session", null=True, verbose_name="Morning end time"
                    ),
                ),
                (
                    "noon_start_time",
                    models.TimeField(
                        blank=True, help_text="Start time of noon session", null=True, verbose_name="Noon start time"
                    ),
                ),
                (
                    "noon_end_time",
                    models.TimeField(
                        blank=True, help_text="End time of noon session", null=True, verbose_name="Noon end time"
                    ),
                ),
                (
                    "afternoon_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Start time of afternoon session",
                        null=True,
                        verbose_name="Afternoon start time",
                    ),
                ),
                (
                    "afternoon_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="End time of afternoon session",
                        null=True,
                        verbose_name="Afternoon end time",
                    ),
                ),
                (
                    "allowed_late_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of minutes late allowed",
                        null=True,
                        verbose_name="Allowed late minutes",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text="Additional notes", max_length=255, null=True, verbose_name="Note"
                    ),
                ),
            ],
            options={
                "verbose_name": "Work schedule",
                "verbose_name_plural": "Work schedules",
                "db_table": "hrm_work_schedule",
                "ordering": ["weekday"],
            },
        ),
    ]
