# Generated by Django 5.2.6 on 2025-11-17 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0057_workschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Holiday name")),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_holidays",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_holidays",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "db_table": "hrm_holiday",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CompensatoryWorkday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Compensatory workday date")),
                (
                    "session",
                    models.CharField(
                        choices=[("morning", "Morning"), ("afternoon", "Afternoon"), ("full_day", "Full Day")],
                        default="full_day",
                        max_length=20,
                        verbose_name="Session",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_compensatory_days",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_compensatory_days",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "holiday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensatory_days",
                        to="hrm.holiday",
                        verbose_name="Holiday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compensatory Workday",
                "verbose_name_plural": "Compensatory Workdays",
                "db_table": "hrm_compensatory_workday",
                "ordering": ["date"],
            },
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(fields=["start_date", "end_date"], name="hrm_holiday_start_d_e6bf97_idx"),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(fields=["status"], name="hrm_holiday_status_e9c183_idx"),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(fields=["deleted"], name="hrm_holiday_deleted_25deb5_idx"),
        ),
        migrations.AddIndex(
            model_name="compensatoryworkday",
            index=models.Index(fields=["date"], name="hrm_compens_date_4f6a69_idx"),
        ),
        migrations.AddIndex(
            model_name="compensatoryworkday",
            index=models.Index(fields=["status"], name="hrm_compens_status_6b6b46_idx"),
        ),
        migrations.AddIndex(
            model_name="compensatoryworkday",
            index=models.Index(fields=["deleted"], name="hrm_compens_deleted_f1e47c_idx"),
        ),
        migrations.AddConstraint(
            model_name="compensatoryworkday",
            constraint=models.UniqueConstraint(
                fields=("holiday", "date"),
                name="unique_holiday_compensatory_date",
                violation_error_message="A compensatory workday with this date already exists for this holiday",
            ),
        ),
    ]
