# Generated by Django 5.2.6 on 2025-11-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0057_workschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Holiday name")),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "db_table": "hrm_holiday",
                "ordering": ["-start_date"],
                "indexes": [models.Index(fields=["start_date", "end_date"], name="hrm_holiday_start_d_e6bf97_idx")],
            },
        ),
        migrations.CreateModel(
            name="CompensatoryWorkday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Compensatory workday date")),
                (
                    "session",
                    models.CharField(
                        choices=[("morning", "Morning"), ("afternoon", "Afternoon"), ("full_day", "Full Day")],
                        default="full_day",
                        max_length=20,
                        verbose_name="Session",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "holiday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensatory_days",
                        to="hrm.holiday",
                        verbose_name="Holiday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compensatory Workday",
                "verbose_name_plural": "Compensatory Workdays",
                "db_table": "hrm_compensatory_workday",
                "ordering": ["date"],
                "indexes": [models.Index(fields=["date"], name="hrm_compens_date_4f6a69_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("holiday", "date"),
                        name="unique_holiday_compensatory_date",
                        violation_error_message="A compensatory workday with this date already exists for this holiday",
                    )
                ],
            },
        ),
    ]
