# Generated by Django 5.2.6 on 2025-11-17 02:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0057_workschedule"),
        ("hrm", "0058_add_holiday_and_compensatory_workday"),
    ]

    operations = []
