# Generated by Django 5.2.6 on 2025-11-17 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0058_holiday_compensatoryworkday"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceExemption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when exemption becomes active",
                        null=True,
                        verbose_name="Effective Date",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or remarks", max_length=1000, verbose_name="Notes"
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        help_text="Employee to be exempt from attendance tracking",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_exemption",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Exemption",
                "verbose_name_plural": "Attendance Exemptions",
                "db_table": "hrm_attendance_exemption",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["employee"], name="hrm_attenda_employe_2128ab_idx"),
                    models.Index(fields=["effective_date"], name="hrm_attenda_effecti_e85380_idx"),
                ],
            },
        ),
    ]
