# Generated by Django 5.2.6 on 2025-11-17 08:35

import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0058_holiday_compensatoryworkday"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceWifi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="WiFi name")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="WiFi code")),
                (
                    "bssid",
                    models.CharField(
                        help_text="WiFi hardware identifier (MAC address format: XX:XX:XX:XX:XX:XX)",
                        max_length=17,
                        unique=True,
                        verbose_name="BSSID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("in_use", "In use"), ("not_in_use", "Not in use")],
                        default="in_use",
                        max_length=20,
                        verbose_name="State",
                    ),
                ),
                ("notes", libs.models.fields.SafeTextField(blank=True, verbose_name="Notes")),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        help_text="Block where this WiFi is located (must belong to selected branch)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_wifis",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch where this WiFi is located",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_wifis",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance WiFi",
                "verbose_name_plural": "Attendance WiFis",
                "db_table": "hrm_attendance_wifi",
                "ordering": ["-created_at"],
            },
        ),
    ]
