# Generated by Django 5.2.6 on 2025-11-18 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0059_add_attendance_exemption"),
        ("hrm", "0059_add_attendance_wifi"),
    ]

    operations = []
