# Generated by Django 5.2.6 on 2025-11-18 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0060_merge_20251118_1044"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AttendanceWifi",
            new_name="WifiAttendanceDevice",
        ),
        migrations.AlterModelOptions(
            name="wifiattendancedevice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "WiFi Attendance Device",
                "verbose_name_plural": "WiFi Attendance Devices",
            },
        ),
    ]
