# Generated by Django 5.2.6 on 2025-11-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0060_rename_attendancewifi_to_wifiattendancedevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="phone",
            field=models.CharField(blank=True, max_length=1000, verbose_name="Phone number"),
        ),
    ]
