# Generated by Django 5.2.6 on 2025-11-18 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0061_alter_branch_phone"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WifiAttendanceDevice",
            new_name="AttendanceWifiDevice",
        ),
        migrations.AlterModelOptions(
            name="attendancewifidevice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Attendance WiFiDevice",
                "verbose_name_plural": "Attendance WiFiDevices",
            },
        ),
    ]
