# Generated by Django 5.2.6 on 2025-11-19 03:30

from django.db import migrations, models

import apps.hrm.models.attendance_geolocation


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0062_rename_wifiattendancedevice_to_attendancewifidevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancegeolocation",
            name="latitude",
            field=models.DecimalField(
                decimal_places=17,
                help_text="Latitude coordinate",
                max_digits=20,
                validators=[apps.hrm.models.attendance_geolocation.validate_latitude],
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="attendancegeolocation",
            name="longitude",
            field=models.DecimalField(
                decimal_places=17,
                help_text="Longitude coordinate",
                max_digits=20,
                validators=[apps.hrm.models.attendance_geolocation.validate_longitude],
                verbose_name="Longitude",
            ),
        ),
    ]
