# Generated by Django 5.2.6 on 2025-11-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_add_uploaded_by_field"),
        ("hrm", "0063_update_attendance_geolocation_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="citizen_id_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_citizen_id_files",
                to="files.filemodel",
                verbose_name="Citizen ID file",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="code_type",
            field=models.CharField(
                choices=[("MV", "MV"), ("CTV", "CTV"), ("OS", "OS")],
                default="MV",
                max_length=10,
                verbose_name="Employee type",
            ),
        ),
    ]
