# Generated by Django 5.2.6 on 2025-11-20 04:19

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0064_employee_citizen_id_file_alter_employee_code_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="available_leave_days",
            field=models.IntegerField(
                default=0,
                help_text="Number of available leave days for the employee",
                verbose_name="Available leave days",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeMonthlyTimesheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "need_refresh",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this report needs to be recalculated by batch task",
                        verbose_name="Needs refresh",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="Report date")),
                ("month_key", models.CharField(max_length=6, verbose_name="Month key")),
                (
                    "probation_working_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6, verbose_name="Probation working days"
                    ),
                ),
                (
                    "official_working_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6, verbose_name="Official working days"
                    ),
                ),
                (
                    "total_working_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6, verbose_name="Total working days"
                    ),
                ),
                (
                    "official_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Official hours"
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="TODO: Check logic after SRS is updated",
                        max_digits=8,
                        verbose_name="Overtime hours",
                    ),
                ),
                (
                    "total_worked_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of official_hours and overtime_hours",
                        max_digits=8,
                        verbose_name="Total worked hours",
                    ),
                ),
                (
                    "paid_leave_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Paid leave days"
                    ),
                ),
                (
                    "unpaid_leave_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Unpaid leave days"
                    ),
                ),
                (
                    "maternity_leave_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Maternity leave days"
                    ),
                ),
                (
                    "public_holiday_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Public holiday days"
                    ),
                ),
                (
                    "unexcused_absence_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Unexcused absence days"
                    ),
                ),
                (
                    "carried_over_leave",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Carried over leave from last year. Only applied for Januray. After that, this field must be set to 0.",
                    ),
                ),
                (
                    "opening_balance_leave_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Opening balance leave days",
                    ),
                ),
                (
                    "consumed_leave_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Consumed leave days"
                    ),
                ),
                (
                    "remaining_leave_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="Remaining leave days"
                    ),
                ),
                ("note", libs.models.fields.SafeTextField(blank=True, verbose_name="Note")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_timesheets",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee monthly timesheet",
                "verbose_name_plural": "Employee monthly timesheets",
                "db_table": "hrm_employee_monthly_timesheet",
                "indexes": [
                    models.Index(fields=["employee", "month_key"], name="idx_employee_month_key"),
                    models.Index(fields=["report_date"], name="idx_monthly_report_date"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("employee", "month_key"), name="uniq_employee_month_key")
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeSheetEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.DateTimeField(blank=True, null=True, verbose_name="Start time")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="End time")),
                (
                    "morning_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Morning hours"
                    ),
                ),
                (
                    "afternoon_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Afternoon hours"
                    ),
                ),
                (
                    "official_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Official hours"
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Overtime hours"
                    ),
                ),
                (
                    "total_worked_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6, verbose_name="Total worked hours"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("on_time", "On time"), ("not_on_time", "Not on time"), ("absent", "Absent")],
                        default="absent",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "absent_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paid_leave", "Paid leave"),
                            ("unpaid_leave", "Unpaid leave"),
                            ("maternity_leave", "Maternity leave"),
                            ("public_holiday", "Public holiday"),
                            ("unexcused_absence", "Unexcused Absence"),
                        ],
                        max_length=64,
                        null=True,
                        verbose_name="Absent reason",
                    ),
                ),
                ("is_full_salary", models.BooleanField(default=True, verbose_name="Is full salary")),
                ("count_for_payroll", models.BooleanField(default=True, verbose_name="Count for payroll")),
                ("note", libs.models.fields.SafeTextField(blank=True, verbose_name="Note")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timesheet",
                "verbose_name_plural": "Timesheets",
                "db_table": "hrm_timesheet",
                "indexes": [models.Index(fields=["employee", "date"], name="timesheet_employee_date_idx")],
            },
        ),
    ]
