# Generated by Django 5.2.6 on 2025-11-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0060_employee_available_leave_days_and_more'),
        ('hrm', '0064_employee_citizen_id_file_alter_employee_code_type'),
    ]

    operations = [
    ]
