# Generated by Django 5.2.6 on 2025-11-19 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0065_merge_20251119_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemonthlytimesheet',
            name='official_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Official hours'),
        ),
        migrations.AddField(
            model_name='employeemonthlytimesheet',
            name='working_days_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated as official_hours / 8, rounded to 2 decimal places', max_digits=8, verbose_name='Working days value'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='official_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Official hours'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Overtime hours'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='total_worked_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Total worked hours'),
        ),
        migrations.AlterField(
            model_name='employeemonthlytimesheet',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TODO: Check logic after SRS is updated', max_digits=8, verbose_name='Overtime hours'),
        ),
        migrations.AlterField(
            model_name='employeemonthlytimesheet',
            name='total_worked_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of official_hours and overtime_hours', max_digits=8, verbose_name='Total worked hours'),
        ),
    ]
