# Generated by Django 5.2.6 on 2025-11-21 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0065_employee_available_leave_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blocks",
                to="hrm.branch",
                verbose_name="Branch",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="hrm.block",
                verbose_name="Block",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="hrm.branch",
                verbose_name="Branch",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="parent_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_departments",
                to="hrm.department",
                verbose_name="Parent department",
            ),
        ),
    ]
