# Generated by Django 5.2.6 on 2025-11-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0066_add_timesheet_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemonthlytimesheet',
            name='working_days_value',
        ),
        migrations.RemoveField(
            model_name='timesheetentry',
            name='total_hours',
        ),
    ]
