# Generated by Django 5.2.6 on 2025-11-21 09:17
from django.db import migrations, models
from django.utils import timezone


def apply_correct_values(apps, schema_editor):
    EmployeeCertificate = apps.get_model("hrm", "EmployeeCertificate")
    need_update_certificates = []
    for certificate in EmployeeCertificate.objects.all():
        need_update = False
        if certificate.certificate_name and len(certificate.certificate_name) > 100:
            certificate.certificate_name = certificate.certificate_name[:100]
            need_update = True
        if not certificate.issuing_organization:
            certificate.issuing_organization = "Unknown Organization"
            need_update = True
        if not certificate.issue_date:
            certificate.issue_date = timezone.localdate()
            need_update = True
        if need_update:
            need_update_certificates.append(certificate)

    EmployeeCertificate.objects.bulk_update(
        need_update_certificates, ["certificate_name", "issue_date", "issuing_organization"]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0066_alter_block_branch_alter_department_block_and_more"),
    ]

    operations = [
        migrations.RunPython(apply_correct_values, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employeecertificate",
            name="certificate_name",
            field=models.CharField(
                blank=True,
                help_text="Specific name of the certificate or exam",
                max_length=100,
                verbose_name="Certificate name",
            ),
        ),
        migrations.AlterField(
            model_name="employeecertificate",
            name="issue_date",
            field=models.DateField(help_text="Date when the certificate was issued", verbose_name="Issue date"),
        ),
        migrations.AlterField(
            model_name="employeecertificate",
            name="issuing_organization",
            field=models.CharField(
                help_text="Organization that issued the certificate",
                max_length=100,
                verbose_name="Issuing organization",
            ),
        ),
    ]
