# Generated by Django 5.2.6 on 2025-11-21 11:30

import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0067_alter_employeecertificate_issue_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Proposal code")),
                ("proposal_date", models.DateField(auto_now_add=True, verbose_name="Proposal date")),
                (
                    "proposal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("post_maternity_benefits", "Post-maternity benefits"),
                            ("late_exemption", "Late exemption"),
                            ("overtime_work", "Overtime work"),
                            ("paid_leave", "Paid leave"),
                            ("unpaid_leave", "Unpaid leave"),
                            ("maternity_leave", "Maternity leave"),
                            ("attendance_exemption", "Attendance exemption"),
                            ("timesheet_entry_complaint", "Timesheet entry complaint"),
                        ],
                        max_length=64,
                        null=True,
                        verbose_name="Proposal type",
                    ),
                ),
                (
                    "proposal_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=32,
                        verbose_name="Proposal status",
                    ),
                ),
                (
                    "complaint_reason",
                    libs.models.fields.SafeTextField(blank=True, null=True, verbose_name="Complaint reason"),
                ),
                (
                    "proposed_check_in_time",
                    models.TimeField(blank=True, null=True, verbose_name="Proposed check-in time"),
                ),
                (
                    "proposed_check_out_time",
                    models.TimeField(blank=True, null=True, verbose_name="Proposed check-out time"),
                ),
                (
                    "approved_check_in_time",
                    models.TimeField(blank=True, null=True, verbose_name="Approved check-in time"),
                ),
                (
                    "approved_check_out_time",
                    models.TimeField(blank=True, null=True, verbose_name="Approved check-out time"),
                ),
                ("note", libs.models.fields.SafeTextField(blank=True, null=True, verbose_name="Note")),
            ],
            options={
                "verbose_name": "Proposal",
                "verbose_name_plural": "Proposals",
                "db_table": "hrm_proposal",
                "indexes": [
                    models.Index(fields=["proposal_status"], name="proposal_status_idx"),
                    models.Index(fields=["proposal_date"], name="proposal_date_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProposalTimeSheetEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        limit_choices_to={"proposal_type": "timesheet_entry_complaint"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_entries",
                        to="hrm.proposal",
                        verbose_name="Proposal",
                    ),
                ),
                (
                    "timesheet_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="hrm.timesheetentry",
                        verbose_name="Timesheet entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Timesheet Entry",
                "verbose_name_plural": "Proposal Timesheet Entries",
                "db_table": "hrm_proposal_timesheet_entry",
                "indexes": [
                    models.Index(fields=["proposal"], name="pt_proposal_idx"),
                    models.Index(fields=["timesheet_entry"], name="pt_entry_idx"),
                ],
                "unique_together": {("proposal", "timesheet_entry")},
            },
        ),
    ]
