# Generated by Django 5.2.6 on 2025-11-23 17:56

from django.db import migrations, models

import libs.models.fields


def truncate_existing_descriptions(apps, schema_editor):
    # NOTE: this function is to ensure existing data complies with new max_length constraints
    RecruitmentChannel = apps.get_model("hrm", "RecruitmentChannel")
    RecruitmentSource = apps.get_model("hrm", "RecruitmentSource")

    need_update_channels = []
    need_update_sources = []

    # Truncate descriptions in RecruitmentChannel
    for channel in RecruitmentChannel.objects.all():
        if channel.description and len(channel.description) > 500:
            channel.description = channel.description[:500]
            need_update_channels.append(channel)

    # Truncate descriptions in RecruitmentSource
    for source in RecruitmentSource.objects.all():
        if source.description and len(source.description) > 500:
            source.description = source.description[:500]
            need_update_sources.append(source)

    # Bulk update all modified channels and sources
    RecruitmentChannel.objects.bulk_update(need_update_channels, ["description"])
    RecruitmentSource.objects.bulk_update(need_update_sources, ["description"])


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0068_proposal_proposaltimesheetentry"),
    ]

    operations = [
        migrations.RunPython(truncate_existing_descriptions, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="recruitmentchannel",
            name="description",
            field=libs.models.fields.SafeTextField(blank=True, max_length=500, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="recruitmentchannel",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Channel name"),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="description",
            field=libs.models.fields.SafeTextField(blank=True, max_length=500, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="recruitmentsource",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Source name"),
        ),
    ]
