# Generated by Django 5.2.6 on 2025-11-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0069_alter_recruitmentchannel_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchContactInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_line", models.CharField(max_length=50, verbose_name="Business line")),
                ("name", models.CharField(max_length=100, verbose_name="Contact name")),
                ("phone_number", models.CharField(max_length=10, verbose_name="Phone number")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_infos",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch contact info",
                "verbose_name_plural": "Branch contact info",
                "db_table": "hrm_branch_contact_info",
                "ordering": ["name"],
            },
        ),
    ]
