# Generated by Django 5.2.6 on 2025-11-24 16:05

import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0069_branchcontactinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_proposals",
                to="hrm.employee",
                verbose_name="Approved by",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_proposals",
                to="hrm.employee",
                verbose_name="Created by",
            ),
        ),
        migrations.CreateModel(
            name="ProposalVerifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("verified", "Verified"), ("not_verified", "Not verified")],
                        default="not_verified",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("verified_time", models.DateTimeField(blank=True, null=True, verbose_name="Verified time")),
                ("note", libs.models.fields.SafeTextField(blank=True, null=True, verbose_name="Note")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifiable_proposals",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifiers",
                        to="hrm.proposal",
                        verbose_name="Proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Verifier",
                "verbose_name_plural": "Proposal Verifiers",
                "db_table": "hrm_proposal_verifier",
                "indexes": [
                    models.Index(fields=["proposal"], name="pv_proposal_idx"),
                    models.Index(fields=["employee"], name="pv_employee_idx"),
                ],
                "unique_together": {("proposal", "employee")},
            },
        ),
    ]
