# Generated by Django 5.2.6 on 2025-11-25 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0070_add_proposal_created_approved_by_and_verifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentcandidate",
            name="employee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_candidate",
                to="hrm.employee",
                verbose_name="Employee",
            ),
        ),
    ]
