# Generated by Django 5.2.6 on 2025-11-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0071_add_employee_to_recruitment_candidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="directed_blocks",
                to="hrm.employee",
                verbose_name="Block director",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="directed_branches",
                to="hrm.employee",
                verbose_name="Branch director",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_departments",
                to="hrm.employee",
                verbose_name="Department leader",
            ),
        ),
    ]
