# Generated by Django 5.2.6 on 2025-11-26 02:57

import django.db.models.deletion
from django.db import migrations, models


def set_default_created_by(apps, schema_editor):
    """Set a default created_by for existing Proposal records."""
    Employee = apps.get_model("hrm", "Employee")
    Proposal = apps.get_model("hrm", "Proposal")

    first_employee = Employee.objects.first()
    proposals = Proposal.objects.filter(created_by__isnull=True)
    need_update_proposals = []

    for proposal in proposals:
        if proposal.created_by is None:
            proposal.created_by = first_employee
            need_update_proposals.append(proposal)

    Proposal.objects.bulk_update(need_update_proposals, ["created_by"])


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0072_block_director_branch_director_department_leader"),
    ]

    operations = [
        migrations.RunPython(set_default_created_by, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="proposal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_proposals",
                to="hrm.employee",
                verbose_name="Created by",
            ),
        ),
    ]
