# Generated by Django 5.2.6 on 2025-11-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0073_alter_proposal_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecertificate",
            name="graduation_diploma",
            field=models.CharField(
                blank=True,
                help_text="Graduation diploma or degree",
                max_length=100,
                null=True,
                verbose_name="Graduation diploma",
            ),
        ),
        migrations.AddField(
            model_name="employeecertificate",
            name="training_specialization",
            field=models.CharField(
                blank=True,
                help_text="Training specialization or major",
                max_length=100,
                null=True,
                verbose_name="Training specialization",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentrequest",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Request name"),
        ),
    ]
