# Generated by Django 5.2.6 on 2025-11-26 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0074_update_recruitment_and_certificate_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bank",
            options={"ordering": ["id"], "verbose_name": "Bank", "verbose_name_plural": "Banks"},
        ),
    ]
