# Generated by Django 5.2.6 on 2025-11-26 13:43

import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0075_alter_bank_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_number",
                    models.CharField(
                        help_text="Unique decision number/code",
                        max_length=50,
                        unique=True,
                        verbose_name="Decision number",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name or title of the decision", max_length=500, verbose_name="Decision name"
                    ),
                ),
                (
                    "signing_date",
                    models.DateField(help_text="Date when the decision was signed", verbose_name="Signing date"),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when the decision becomes effective", verbose_name="Effective date"
                    ),
                ),
                (
                    "reason",
                    libs.models.fields.SafeTextField(
                        blank=True,
                        help_text="Reason for the decision",
                        max_length=500,
                        null=True,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "content",
                    libs.models.fields.SafeTextField(
                        blank=True,
                        help_text="Full content of the decision",
                        max_length=2000,
                        null=True,
                        verbose_name="Decision content",
                    ),
                ),
                (
                    "note",
                    libs.models.fields.SafeTextField(
                        blank=True, help_text="Additional notes", max_length=1000, null=True, verbose_name="Note"
                    ),
                ),
                (
                    "signing_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("issued", "Issued")],
                        default="draft",
                        help_text="Current signing status of the decision",
                        max_length=20,
                        verbose_name="Signing status",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        help_text="Employee who signed the decision",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_decisions",
                        to="hrm.employee",
                        verbose_name="Signer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision",
                "verbose_name_plural": "Decisions",
                "db_table": "hrm_decision",
                "ordering": ["-signing_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["decision_number"], name="decision_number_idx"),
                    models.Index(fields=["signing_date"], name="decision_signing_date_idx"),
                    models.Index(fields=["effective_date"], name="decision_effective_date_idx"),
                    models.Index(fields=["signing_status"], name="decision_signing_status_idx"),
                ],
            },
        ),
    ]
