# Generated by manual edit on 2025-11-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0075_update_attendance_record_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='device',
            new_name='biometric_device',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='hrm_attenda_biomet_idx',
            old_fields=['device', '-timestamp'],
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_type',
            field=models.CharField(
                choices=[('biometric_device', 'Biometric Device'), ('wifi', 'WiFi'), ('geolocation', 'GeoLocation'), ('other', 'Other')],
                default='biometric_device',
                help_text='Type of attendance method used',
                max_length=20,
                verbose_name='Attendance type'
            ),
        ),
    ]
