# Generated by Django 5.2.6 on 2025-11-27 04:52

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_add_uploaded_by_field"),
        ("hrm", "0076_decision"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="hrm_attenda_device__d1a9e3_idx",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="device",
        ),
        migrations.AddField(
            model_name="attendancegeolocation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Geographic point for spatial queries (auto-populated from lat/long)",
                null=True,
                srid=4326,
                verbose_name="Location Point",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="attendance_geolocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Geolocation reference (for geolocation attendance)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="hrm.attendancegeolocation",
                verbose_name="Attendance geolocation",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("biometric_device", "Biometric Device"),
                    ("wifi", "WiFi"),
                    ("geolocation", "GeoLocation"),
                    ("other", "Other"),
                ],
                default="biometric_device",
                help_text="Type of attendance method used",
                max_length=20,
                verbose_name="Attendance type",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="attendance_wifi_device",
            field=models.ForeignKey(
                blank=True,
                help_text="WiFi device reference (for WiFi attendance)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="hrm.attendancewifidevice",
                verbose_name="WiFi device",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="biometric_device",
            field=models.ForeignKey(
                blank=True,
                help_text="Attendance device that captured this record (for biometric device type)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="hrm.attendancedevice",
                verbose_name="Biometric Device",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee associated with this attendance record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="hrm.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Attendance photo (for geolocation attendance)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="files.filemodel",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="GeoLocation latitude coordinate (for geolocation attendance)",
                max_digits=20,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="GeoLocation longitude coordinate (for geolocation attendance)",
                max_digits=20,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_code",
            field=models.CharField(
                blank=True,
                help_text="User ID from device, used to match with Employee.attendance_code",
                max_length=20,
                verbose_name="Attendance code",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["biometric_device", "-timestamp"], name="hrm_attenda_biometr_77d2a0_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["employee", "-timestamp"], name="hrm_attenda_employe_e31335_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["attendance_type", "-timestamp"], name="hrm_attenda_attenda_9177f3_idx"),
        ),
    ]
