# Generated by Django 5.2.8 on 2025-11-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0076_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OFFICIAL", "Official"),
                    ("APPRENTICE", "Apprentice"),
                    ("UNPAID_OFFICIAL", "Unpaid - Official"),
                    ("UNPAID_PROBATION", "Unpaid - Probation"),
                    ("PROBATION", "Probation"),
                    ("INTERN", "Intern"),
                    ("PROBATION_TYPE_1", "Probation Type 1"),
                ],
                max_length=30,
                null=True,
                verbose_name="Employee type (classification)",
            ),
        ),
    ]
