# Generated by Django 5.2.6 on 2025-11-27 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0077_add_employee_type_field"),
        ("hrm", "0077_remove_attendancerecord_hrm_attenda_device__d1a9e3_idx_and_more"),
    ]

    operations = []
