# Generated by Django - Migration to remove contract_type field from Employee model

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0078_merge_20251127_1321"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="contract_type",
        ),
    ]
