# Generated by Django 5.2.6 on 2025-11-27 08:27

import django.core.validators
import django.db.models.deletion
import libs.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_add_uploaded_by_field'),
        ('hrm', '0079_remove_employee_contract_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contract type', 'verbose_name_plural': 'Contract types'},
        ),
        migrations.AddField(
            model_name='contracttype',
            name='annual_leave_days',
            field=models.PositiveIntegerField(default=12, help_text='Number of annual leave days (maximum 12)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Annual leave days'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='base_salary',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Base salary amount', max_digits=20, verbose_name='Base salary'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='code',
            field=models.CharField(blank=True, help_text='Auto-generated unique contract type code', max_length=50, null=True, unique=True, verbose_name='Contract type code'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Number of months for fixed-term contracts', null=True, verbose_name='Duration in months'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='duration_type',
            field=models.CharField(choices=[('indefinite', 'Indefinite term'), ('fixed', 'Fixed term')], default='indefinite', help_text='Whether the contract has a fixed term or is indefinite', max_length=20, verbose_name='Duration type'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='has_social_insurance',
            field=models.BooleanField(default=True, help_text='Whether social insurance is included', verbose_name='Has social insurance'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='lunch_allowance',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Lunch allowance amount', max_digits=20, null=True, verbose_name='Lunch allowance'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='net_percentage',
            field=models.CharField(choices=[('100', '100%'), ('85', '85%')], default='100', help_text='Net salary percentage (100% or 85%)', max_length=5, verbose_name='Net percentage'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='note',
            field=libs.models.fields.SafeTextField(blank=True, help_text='Additional notes', max_length=500, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='other_allowance',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Other allowance amount', max_digits=20, null=True, verbose_name='Other allowance'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='phone_allowance',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Phone allowance amount', max_digits=20, null=True, verbose_name='Phone allowance'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='rights_and_obligations',
            field=libs.models.fields.SafeTextField(default='', help_text='Rights and obligations of parties', max_length=5000, verbose_name='Rights and obligations'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='symbol',
            field=models.CharField(default='', help_text='Symbol or abbreviation for the contract type', max_length=20, verbose_name='Contract type symbol'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='tax_calculation_method',
            field=models.CharField(choices=[('progressive', 'Progressive tax'), ('flat_10', '10% flat tax'), ('none', 'No tax')], default='progressive', help_text='Method for calculating tax', max_length=20, verbose_name='Tax calculation method'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='template_file',
            field=models.ForeignKey(blank=True, help_text='Template file for the contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_type_templates', to='files.filemodel', verbose_name='Template file'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='terms',
            field=libs.models.fields.SafeTextField(default='', help_text='Contract terms and conditions', max_length=5000, verbose_name='Terms'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='working_conditions',
            field=libs.models.fields.SafeTextField(default='', help_text='Description of working conditions', max_length=1000, verbose_name='Working conditions'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='working_time_type',
            field=models.CharField(choices=[('full_time', 'Full-time - Office hours'), ('part_time', 'Part-time'), ('other', 'Other')], default='full_time', help_text='Type of working time arrangement', max_length=20, verbose_name='Working time type'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.CharField(help_text='Name of the contract type', max_length=100, unique=True, verbose_name='Contract type name'),
        ),
    ]
