# Generated by Django 5.2.6 on 2025-11-28 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0080_alter_contracttype_options_and_more"),
        ("realestate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDailyReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(verbose_name="Report date")),
                (
                    "need_refresh",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this report needs to be recalculated by batch task",
                        verbose_name="Needs refresh",
                    ),
                ),
                (
                    "attendance_method",
                    models.CharField(
                        choices=[
                            ("biometric_device", "Biometric Device"),
                            ("wifi", "WiFi"),
                            ("geolocation", "GeoLocation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Attendance method",
                    ),
                ),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_reports",
                        to="hrm.attendancerecord",
                        verbose_name="Attendance record",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_daily_reports",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="realestate.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Daily Report",
                "verbose_name_plural": "Attendance Daily Reports",
                "db_table": "hrm_attendance_daily_report",
                "indexes": [
                    models.Index(fields=["report_date"], name="hrm_attenda_report__fc7e9c_idx"),
                    models.Index(fields=["branch", "block", "department"], name="hrm_attenda_branch__2de2ed_idx"),
                    models.Index(fields=["project"], name="hrm_attenda_project_a36cb6_idx"),
                    models.Index(fields=["attendance_method"], name="hrm_attenda_attenda_d309fb_idx"),
                ],
                "unique_together": {("report_date", "employee")},
            },
        ),
    ]
