# Generated by Django 5.2.6 on 2025-11-28 08:10

import django.db.models.deletion
import libs.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_add_uploaded_by_field'),
        ('hrm', '0081_attendancedailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, help_text='Auto-generated unique contract code', max_length=50, null=True, unique=True, verbose_name='Contract code')),
                ('contract_number', models.CharField(help_text='Unique contract number in format xx/yyyy/abc - MVL', max_length=100, unique=True, verbose_name='Contract number')),
                ('sign_date', models.DateField(help_text='Date when the contract was signed', verbose_name='Sign date')),
                ('effective_date', models.DateField(help_text='Date when the contract becomes effective', verbose_name='Effective date')),
                ('expiration_date', models.DateField(blank=True, help_text='Date when the contract expires (null for indefinite contracts)', null=True, verbose_name='Expiration date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('not_effective', 'Not effective'), ('active', 'Active'), ('about_to_expire', 'About to expire'), ('expired', 'Expired')], default='draft', help_text='Current status of the contract', max_length=20, verbose_name='Contract status')),
                ('base_salary', models.DecimalField(decimal_places=0, default=0, help_text='Base salary amount at the time of contract', max_digits=20, verbose_name='Base salary')),
                ('lunch_allowance', models.DecimalField(blank=True, decimal_places=0, help_text='Lunch allowance amount at the time of contract', max_digits=20, null=True, verbose_name='Lunch allowance')),
                ('phone_allowance', models.DecimalField(blank=True, decimal_places=0, help_text='Phone allowance amount at the time of contract', max_digits=20, null=True, verbose_name='Phone allowance')),
                ('other_allowance', models.DecimalField(blank=True, decimal_places=0, help_text='Other allowance amount at the time of contract', max_digits=20, null=True, verbose_name='Other allowance')),
                ('net_percentage', models.CharField(default='100', help_text='Net salary percentage at the time of contract', max_length=5, verbose_name='Net percentage')),
                ('tax_calculation_method', models.CharField(default='progressive', help_text='Tax calculation method at the time of contract', max_length=20, verbose_name='Tax calculation method')),
                ('has_social_insurance', models.BooleanField(default=True, help_text='Whether social insurance is included', verbose_name='Has social insurance')),
                ('working_conditions', libs.models.fields.SafeTextField(default='', help_text='Working conditions at the time of contract', max_length=1000, verbose_name='Working conditions')),
                ('rights_and_obligations', libs.models.fields.SafeTextField(default='', help_text='Rights and obligations at the time of contract', max_length=5000, verbose_name='Rights and obligations')),
                ('terms', libs.models.fields.SafeTextField(default='', help_text='Contract terms and conditions at the time of contract', max_length=5000, verbose_name='Terms')),
                ('note', libs.models.fields.SafeTextField(blank=True, help_text='Additional notes', max_length=500, null=True, verbose_name='Note')),
                ('attachment', models.ForeignKey(blank=True, help_text='Attached contract file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_attachments', to='files.filemodel', verbose_name='Attachment')),
                ('contract_type', models.ForeignKey(help_text='Type of the contract', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='hrm.contracttype', verbose_name='Contract type')),
                ('employee', models.ForeignKey(help_text='Employee associated with this contract', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='hrm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'hrm_contract',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='contract_code_idx'), models.Index(fields=['contract_number'], name='contract_number_idx'), models.Index(fields=['status'], name='contract_status_idx'), models.Index(fields=['effective_date'], name='contract_effective_date_idx'), models.Index(fields=['expiration_date'], name='contract_expiration_date_idx')],
            },
        ),
    ]
