# Generated by Django 5.2.6 on 2025-11-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0082_add_contract_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contract',
            name='contract_number_idx',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_number',
        ),
    ]
