# Generated by Django 5.2.6 on 2025-12-01 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0083_contract_appendix"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="effective_date",
            field=models.DateField(blank=True, null=True, verbose_name="Effective date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Extra data"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="handover_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handover_proposals",
                to="hrm.employee",
                verbose_name="Handover employee",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="new_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_proposals",
                to="hrm.department",
                verbose_name="New department",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="new_job_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_proposals",
                to="hrm.position",
                verbose_name="New job title",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="session",
            field=models.CharField(
                blank=True,
                choices=[("full_day", "Full day"), ("morning", "Morning"), ("afternoon", "Afternoon")],
                max_length=32,
                null=True,
                verbose_name="Session",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="total_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Total hours"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("post_maternity_benefits", "Post-maternity benefits"),
                    ("late_exemption", "Late exemption"),
                    ("overtime_work", "Overtime work"),
                    ("paid_leave", "Paid leave"),
                    ("unpaid_leave", "Unpaid leave"),
                    ("maternity_leave", "Maternity leave"),
                    ("attendance_exemption", "Attendance exemption"),
                    ("timesheet_entry_complaint", "Timesheet entry complaint"),
                    ("transfer", "Transfer"),
                    ("asset_allocation", "Asset allocation"),
                ],
                max_length=64,
                null=True,
                verbose_name="Proposal type",
            ),
        ),
        migrations.CreateModel(
            name="ProposalAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Asset name")),
                ("unit", models.CharField(max_length=50, verbose_name="Unit")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Quantity")),
                (
                    "proposal",
                    models.ForeignKey(
                        limit_choices_to={"proposal_type": "asset_allocation"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="hrm.proposal",
                        verbose_name="Proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Asset",
                "verbose_name_plural": "Proposal Assets",
                "db_table": "hrm_proposal_asset",
                "indexes": [models.Index(fields=["proposal"], name="pa_proposal_idx")],
            },
        ),
    ]
