# Generated by Django 5.2.6 on 2025-12-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0084_refactor_contract_appendix_to_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="kpi_salary",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="KPI salary amount at the time of contract",
                max_digits=20,
                verbose_name="KPI salary",
            ),
        ),
    ]
