# Generated by Django 5.2.6 on 2025-12-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0084_upgrade_proposal_management_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Proposal code'),
        ),
    ]
