# Generated by Django 5.2.6 on 2025-12-01 16:42

import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0085_contract_kpi_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="late_exemption_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Late exemption end date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="late_exemption_minutes",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Late exemption minutes"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="late_exemption_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Late exemption start date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="maternity_leave_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Maternity leave end date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="maternity_leave_estimated_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Maternity leave estimated due date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="maternity_leave_replacement_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_for_maternity_proposals",
                to="hrm.employee",
                verbose_name="Replacement employee for maternity leave",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="maternity_leave_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Maternity leave start date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="overtime_work_end_at",
            field=models.TimeField(blank=True, null=True, verbose_name="Overtime work end time"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="overtime_work_start_at",
            field=models.TimeField(blank=True, null=True, verbose_name="Overtime work start time"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="post_maternity_benefits_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Post-maternity benefits end date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="post_maternity_benefits_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Post-maternity benefits start date"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("post_maternity_benefits", "Post-maternity benefits"),
                    ("late_exemption", "Late exemption"),
                    ("overtime_work", "Overtime work"),
                    ("paid_leave", "Paid leave"),
                    ("unpaid_leave", "Unpaid leave"),
                    ("maternity_leave", "Maternity leave"),
                    ("attendance_exemption", "Attendance exemption"),
                    ("timesheet_entry_complaint", "Timesheet entry complaint"),
                    ("job_transfer", "Job Transfer"),
                    ("asset_allocation", "Asset Allocation"),
                ],
                max_length=64,
                null=True,
                verbose_name="Proposal type",
            ),
        ),
        migrations.CreateModel(
            name="ProposalAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Asset name")),
                (
                    "unit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("piece", "Piece"),
                            ("box", "Box"),
                            ("set", "Set"),
                            ("gram", "Gram"),
                            ("liter", "Liter"),
                            ("meter", "Meter"),
                            ("cylinder", "Cylinder"),
                            ("bag", "Bag"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Unit type",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                ("note", libs.models.fields.SafeTextField(blank=True, max_length=250, null=True, verbose_name="Note")),
                (
                    "proposal",
                    models.ForeignKey(
                        limit_choices_to={"proposal_type": "asset_allocation"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="hrm.proposal",
                        verbose_name="Proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Asset",
                "verbose_name_plural": "Proposal Assets",
                "db_table": "hrm_proposal_asset",
                "indexes": [models.Index(fields=["proposal"], name="pa_proposal_idx")],
            },
        ),
    ]
