# Generated by Django 5.2.6 on 2025-12-02 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0086_proposal_late_exemption_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="annual_leave_days",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Number of annual leave days (maximum 12)",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)],
                verbose_name="Annual leave days",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="duration_months",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of months for fixed-term contracts",
                null=True,
                verbose_name="Duration in months",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="duration_type",
            field=models.CharField(
                choices=[("indefinite", "Indefinite term"), ("fixed", "Fixed term")],
                default="indefinite",
                help_text="Whether the contract has a fixed term or is indefinite",
                max_length=20,
                verbose_name="Duration type",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="working_time_type",
            field=models.CharField(
                choices=[("full_time", "Full-time - Office hours"), ("part_time", "Part-time"), ("other", "Other")],
                default="full_time",
                help_text="Type of working time arrangement",
                max_length=20,
                verbose_name="Working time type",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="net_percentage",
            field=models.CharField(
                choices=[("100", "100%"), ("85", "85%")],
                default="100",
                help_text="Net salary percentage at the time of contract",
                max_length=5,
                verbose_name="Net percentage",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="tax_calculation_method",
            field=models.CharField(
                choices=[("progressive", "Progressive tax"), ("flat_10", "10% flat tax"), ("none", "No tax")],
                default="progressive",
                help_text="Tax calculation method at the time of contract",
                max_length=20,
                verbose_name="Tax calculation method",
            ),
        ),
    ]
