# Generated by Django 5.2.6 on 2025-12-02 07:30

import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0087_contract_annual_leave_days_contract_duration_months_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="overtime_work_end_at",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="overtime_work_start_at",
        ),
        migrations.AddField(
            model_name="proposal",
            name="job_transfer_effective_date",
            field=models.DateField(blank=True, null=True, verbose_name="Job transfer effective date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="job_transfer_new_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_transfer_proposals",
                to="hrm.block",
                verbose_name="New block",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="job_transfer_new_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_transfer_proposals",
                to="hrm.branch",
                verbose_name="New branch",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="job_transfer_new_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_transfer_proposals",
                to="hrm.department",
                verbose_name="New department",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="job_transfer_new_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_transfer_proposals",
                to="hrm.position",
                verbose_name="New position",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="job_transfer_reason",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Job transfer reason"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="paid_leave_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Paid leave end date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="paid_leave_reason",
            field=libs.models.fields.SafeTextField(
                blank=True, max_length=500, null=True, verbose_name="Paid leave reason"
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="paid_leave_shift",
            field=models.CharField(
                blank=True,
                choices=[("full_day", "Full Day"), ("morning", "Morning"), ("afternoon", "Afternoon")],
                max_length=20,
                null=True,
                verbose_name="Paid leave shift",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="paid_leave_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Paid leave start date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="unpaid_leave_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Unpaid leave end date"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="unpaid_leave_reason",
            field=libs.models.fields.SafeTextField(
                blank=True, max_length=500, null=True, verbose_name="Unpaid leave reason"
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="unpaid_leave_shift",
            field=models.CharField(
                blank=True,
                choices=[("full_day", "Full Day"), ("morning", "Morning"), ("afternoon", "Afternoon")],
                max_length=20,
                null=True,
                verbose_name="Unpaid leave shift",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="unpaid_leave_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Unpaid leave start date"),
        ),
        migrations.CreateModel(
            name="ProposalOvertimeEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Overtime date")),
                ("start_time", models.TimeField(verbose_name="Start time")),
                ("end_time", models.TimeField(verbose_name="End time")),
                (
                    "description",
                    libs.models.fields.SafeTextField(
                        blank=True, max_length=250, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        limit_choices_to={"proposal_type": "overtime_work"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_entries",
                        to="hrm.proposal",
                        verbose_name="Proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Overtime Entry",
                "verbose_name_plural": "Proposal Overtime Entries",
                "db_table": "hrm_proposal_overtime_entry",
                "indexes": [
                    models.Index(fields=["proposal"], name="poe_proposal_idx"),
                    models.Index(fields=["date"], name="poe_date_idx"),
                ],
            },
        ),
    ]
