# Generated by Django 5.2.6 on 2025-12-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_add_uploaded_by_field"),
        ("hrm", "0088_remove_proposal_overtime_work_end_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecertificate",
            name="effective_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the certificate becomes effective",
                null=True,
                verbose_name="Effective date",
            ),
        ),
        migrations.AddIndex(
            model_name="employeecertificate",
            index=models.Index(fields=["effective_date"], name="hrm_employe_effecti_bcd132_idx"),
        ),
    ]
