# Generated by Django 5.2.6 on 2025-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0091_add_is_manually_corrected_to_timesheet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="approved_check_in_time",
            new_name="timesheet_entry_complaint_approved_check_in_time",
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="approved_check_out_time",
            new_name="timesheet_entry_complaint_approved_check_out_time",
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="complaint_reason",
            new_name="timesheet_entry_complaint_complaint_reason",
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="proposed_check_in_time",
            new_name="timesheet_entry_complaint_proposed_check_in_time",
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="proposed_check_out_time",
            new_name="timesheet_entry_complaint_proposed_check_out_time",
        ),
        migrations.AddField(
            model_name="proposal",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Approved at"),
        ),
    ]
