# Generated by Django 5.2.6 on 2025-12-08 03:34

from django.db import migrations, models


def check_for_attendance_exemption_proposals(apps, schema_editor):
    """
    Check if there are any existing proposals with 'attendance_exemption' type.
    Raise an error if found, as this type is being removed.
    """
    Proposal = apps.get_model("hrm", "Proposal")
    count = Proposal.objects.filter(proposal_type="attendance_exemption").count()
    if count > 0:
        raise Exception(
            f"Found {count} proposal(s) with type 'attendance_exemption'. "
            f"Please migrate or delete these proposals before applying this migration."
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "hrm",
            "0092_rename_approved_check_in_time_proposal_timesheet_entry_complaint_approved_check_in_time_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(check_for_attendance_exemption_proposals, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="proposal",
            name="proposal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("post_maternity_benefits", "Post-maternity benefits"),
                    ("late_exemption", "Late exemption"),
                    ("overtime_work", "Overtime work"),
                    ("paid_leave", "Paid leave"),
                    ("unpaid_leave", "Unpaid leave"),
                    ("maternity_leave", "Maternity leave"),
                    ("timesheet_entry_complaint", "Timesheet entry complaint"),
                    ("job_transfer", "Job Transfer"),
                    ("asset_allocation", "Asset Allocation"),
                ],
                max_length=64,
                null=True,
                verbose_name="Proposal type",
            ),
        ),
    ]
