# Generated by Django 5.2.6 on 2025-12-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0093_remove_attendance_exemption_proposal_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancedevice",
            name="port",
            field=models.PositiveIntegerField(help_text="Network port for device communication", verbose_name="Port"),
        ),
    ]
