# Generated by Django 5.2.6 on 2025-12-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0094_alter_attendancedevice_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposalverifier",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("verified", "Verified"), ("not_verified", "Not verified")],
                default="pending",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
