# Generated by Django 5.2.6 on 2025-12-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0095_alter_proposalverifier_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="include_in_employee_report",
            field=models.BooleanField(default=True, verbose_name="Include in Employee report"),
        ),
    ]
