# Generated by Django 5.2.6 on 2025-12-09 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0096_add_include_in_hr_report_to_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="timesheet_entry_complaint_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Timesheet Entry Complaint Address"
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="timesheet_entry_complaint_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="Timesheet Entry Complaint Latitude coordinate",
                max_digits=20,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="timesheet_entry_complaint_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=17,
                help_text="Timesheet Entry Complaint Longitude coordinate",
                max_digits=20,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Longitude",
            ),
        ),
    ]
