# Generated by Django 5.2.6 on 2025-12-09 06:51

from django.db import migrations

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0097_proposal_timesheet_entry_complaint_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="resolution_note",
            field=libs.models.fields.SafeTextField(
                blank=True, null=True, verbose_name="Note for employee who approve/reject the proposal"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="note",
            field=libs.models.fields.SafeTextField(
                blank=True, null=True, verbose_name="Note for employee who create the proposal"
            ),
        ),
    ]
