# Generated by Django 5.2.6 on 2025-12-09 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0098_proposal_resolution_note_alter_proposal_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="resolution_note",
            new_name="approval_note",
        ),
    ]
