# Generated by Django 5.2.6 on 2025-12-10 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_add_uploaded_by_field"),
        ("hrm", "0099_rename_resolution_note_proposal_approval_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="timesheet_entry_complaint_complaint_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheet_entry_complaint_proposals",
                to="files.filemodel",
                verbose_name="Timesheet Entry Complaint Image",
            ),
        ),
    ]
