# Generated by Django 5.2.6 on 2025-12-10 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0100_proposal_timesheet_entry_complaint_complaint_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["-id"], "verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
    ]
