# Generated by Django 5.2.6 on 2025-12-10 07:59

import django.core.validators
from django.db import migrations, models


def apply_unique_phone_number(apps, schema_editor):
    """Apply unique constraint to existing phone numbers.

    This function ensures that all existing phone numbers are unique before
    applying the unique constraint. If duplicates are found, it raises an error.
    """
    Employee = apps.get_model("hrm", "Employee")
    need_update_employees = []
    employees = Employee.objects.all()

    # NOTE: convert all existing phone numbers to unique values using ID of employee
    for employee in employees:
        employee.phone = str(employee.id).zfill(10)
        need_update_employees.append(employee)
    Employee.objects.bulk_update(need_update_employees, ["phone"])


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0101_alter_employee_options"),
    ]

    operations = [
        migrations.RunPython(apply_unique_phone_number, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits", regex="^\\d{10}$"
                    )
                ],
                verbose_name="Phone number",
            ),
        ),
    ]
