# Generated by Django 5.2.6 on 2025-12-10 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0101_add_device_change_request_model"),
        ("hrm", "0101_alter_employee_options"),
    ]

    operations = []
