# Generated by Django 5.2.6 on 2025-12-10 08:48

from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0102_alter_employee_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="device_change_contact_info",
            field=libs.models.fields.SafeTextField(
                blank=True,
                help_text="Additional contact information or notes for device change request",
                null=True,
                verbose_name="Contact info / notes",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="device_change_new_device_id",
            field=models.CharField(
                blank=True,
                help_text="New device ID being requested",
                max_length=255,
                null=True,
                verbose_name="New device ID",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="device_change_new_platform",
            field=models.CharField(
                blank=True,
                help_text="Platform of the new device (ios, android, web)",
                max_length=20,
                null=True,
                verbose_name="New platform",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="device_change_old_device_id",
            field=models.CharField(
                blank=True,
                help_text="Previous device ID (if any)",
                max_length=255,
                null=True,
                verbose_name="Old device ID",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("post_maternity_benefits", "Post-maternity benefits"),
                    ("late_exemption", "Late exemption"),
                    ("overtime_work", "Overtime work"),
                    ("paid_leave", "Paid leave"),
                    ("unpaid_leave", "Unpaid leave"),
                    ("maternity_leave", "Maternity leave"),
                    ("timesheet_entry_complaint", "Timesheet entry complaint"),
                    ("job_transfer", "Job Transfer"),
                    ("asset_allocation", "Asset Allocation"),
                    ("device_change", "Device Change"),
                ],
                max_length=64,
                null=True,
                verbose_name="Proposal type",
            ),
        ),
    ]
