# Generated by Django on 2025-09-25

import django.utils.timezone
from django.db import migrations, models

import apps.core.querysets.user


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ("employee_code", models.CharField(max_length=100, unique=True, verbose_name="Mã nhân viên")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("phone_number", models.CharField(blank=True, max_length=15, null=True, verbose_name="Số điện thoại")),
                ("first_name", models.CharField(blank=True, max_length=30, verbose_name="Tên")),
                ("last_name", models.CharField(blank=True, max_length=30, verbose_name="Họ")),
                ("is_active", models.BooleanField(default=True, verbose_name="Hoạt động")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Nhân viên")),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ngày tham gia")),
                ("failed_login_attempts", models.IntegerField(default=0, verbose_name="Số lần đăng nhập thất bại")),
                ("locked_until", models.DateTimeField(blank=True, null=True, verbose_name="Khóa tài khoản đến")),
                ("otp_code", models.CharField(blank=True, max_length=6, verbose_name="Mã OTP")),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True, verbose_name="OTP hết hạn lúc")),
                ("otp_verified", models.BooleanField(default=False, verbose_name="OTP đã xác thực")),
                ("active_session_key", models.CharField(blank=True, max_length=255, verbose_name="Phiên hoạt động")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Người dùng",
                "verbose_name_plural": "Người dùng",
                "db_table": "core_user",
            },
            managers=[
                ("objects", apps.core.querysets.user.UserManager()),
            ],
        ),
    ]
