# Generated by Django 5.2.6 on 2026-01-08 07:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nationality name"),
                ),
            ],
            options={
                "verbose_name": "Nationality",
                "verbose_name_plural": "Nationalities",
                "db_table": "core_nationality",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Permission code"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Permission name"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="Description"),
                ),
                (
                    "module",
                    models.CharField(blank=True, max_length=100, verbose_name="Module"),
                ),
                (
                    "submodule",
                    models.CharField(blank=True, max_length=100, verbose_name="Submodule"),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "core_permission",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "username",
                    models.CharField(max_length=100, unique=True, verbose_name="Username"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=30, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=30, verbose_name="Last name"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date joined"),
                ),
                (
                    "mobile_token_version",
                    models.PositiveIntegerField(default=1, verbose_name="Mobile token version"),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(default=0, verbose_name="Failed login attempts"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="Locked until"),
                ),
                (
                    "otp_code",
                    models.CharField(blank=True, max_length=6, verbose_name="OTP code"),
                ),
                (
                    "otp_expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="OTP expires at"),
                ),
                (
                    "otp_verified",
                    models.BooleanField(default=False, verbose_name="OTP verified"),
                ),
                (
                    "active_session_key",
                    models.CharField(blank=True, max_length=255, verbose_name="Active session"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "core_user",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reset_token",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Reset Token",
                    ),
                ),
                ("otp_hash", models.CharField(max_length=128, verbose_name="OTP Hash")),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Verification Attempts"),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(default=5, verbose_name="Max Attempts"),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="Is Used")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset OTP",
                "verbose_name_plural": "Password Reset OTPs",
                "db_table": "core_password_reset_otp",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier code for the province",
                        max_length=50,
                        verbose_name="Province code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the province",
                        max_length=200,
                        verbose_name="Province name",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        help_text="English name of the province",
                        max_length=200,
                        verbose_name="English name",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("central_city", "Central City"),
                            ("province", "Province"),
                        ],
                        help_text="Administrative level of the province",
                        max_length=50,
                        verbose_name="Administrative level",
                    ),
                ),
                (
                    "decree",
                    models.CharField(
                        blank=True,
                        help_text="Legal decree reference",
                        max_length=100,
                        verbose_name="Decree",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this province is currently enabled",
                        verbose_name="Enabled",
                    ),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "db_table": "core_province",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("enabled", True)),
                        fields=("code",),
                        name="unique_enabled_province_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Role code"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Role name"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="Description"),
                ),
                (
                    "is_system_role",
                    models.BooleanField(default=False, verbose_name="System role"),
                ),
                (
                    "is_default_role",
                    models.BooleanField(default=False, verbose_name="Default role"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="core.permission",
                        verbose_name="Permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vai trò",
                "verbose_name_plural": "các Vai trò",
                "db_table": "core_role",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.role",
                verbose_name="Role",
            ),
        ),
        migrations.CreateModel(
            name="DeviceChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "new_device_id",
                    models.CharField(
                        help_text="Device ID being requested for assignment",
                        max_length=255,
                        verbose_name="New Device ID",
                    ),
                ),
                (
                    "new_platform",
                    models.CharField(
                        blank=True,
                        help_text="Platform of the new device (ios, android, web)",
                        max_length=20,
                        verbose_name="New Platform",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes from the requester",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        help_text="OTP code for verification (stored in plaintext for admin viewing)",
                        max_length=6,
                        verbose_name="OTP Code",
                    ),
                ),
                (
                    "otp_sent_at",
                    models.DateTimeField(
                        help_text="Timestamp when OTP was sent",
                        verbose_name="OTP Sent At",
                    ),
                ),
                (
                    "otp_expires_at",
                    models.DateTimeField(
                        help_text="Timestamp when OTP expires",
                        verbose_name="OTP Expires At",
                    ),
                ),
                (
                    "otp_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Number of OTP verification attempts",
                        verbose_name="OTP Attempts",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("otp_sent", "OTP Sent"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="otp_sent",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Change Request",
                "verbose_name_plural": "Device Change Requests",
                "db_table": "core_device_change_request",
                "indexes": [
                    models.Index(fields=["user"], name="dcr_user_idx"),
                    models.Index(fields=["status"], name="dcr_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdministrativeUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier code for the administrative unit",
                        max_length=50,
                        verbose_name="Unit code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the administrative unit",
                        max_length=200,
                        verbose_name="Unit name",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        help_text="English name of the administrative unit",
                        max_length=200,
                        verbose_name="English name",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("district", "District"),
                            ("commune", "Commune"),
                            ("ward", "Ward"),
                            ("township", "Township"),
                        ],
                        help_text="Administrative level of the unit",
                        max_length=50,
                        verbose_name="Administrative level",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this administrative unit is currently enabled",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "parent_province",
                    models.ForeignKey(
                        help_text="Province that this unit belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrative_units",
                        to="core.province",
                        verbose_name="Parent province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Unit",
                "verbose_name_plural": "Administrative Units",
                "db_table": "core_administrative_unit",
                "ordering": ["parent_province__code", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("enabled", True)),
                        fields=("code",),
                        name="unique_enabled_administrative_unit_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "client",
                    models.CharField(
                        choices=[("mobile", "Mobile"), ("web", "Web")],
                        default="mobile",
                        max_length=20,
                        verbose_name="Client",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Client provided device identifier",
                        max_length=255,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "push_token",
                    models.CharField(
                        blank=True,
                        help_text="Push notification token (e.g., FCM/APNS)",
                        max_length=255,
                        verbose_name="Push token",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        help_text="Device platform (iOS/Android)",
                        max_length=20,
                        verbose_name="Platform",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="State",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last seen at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User device",
                "verbose_name_plural": "User devices",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("client", "mobile"), ("state", "active")),
                        fields=("user",),
                        name="uniq_active_mobile_device_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("client", "mobile"), ("state", "active")),
                        fields=("device_id",),
                        name="uniq_active_mobile_device_id",
                    ),
                ],
            },
        ),
    ]
