# Generated by Django 5.2.6 on 2026-01-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="data_scope_level",
            field=models.CharField(
                choices=[
                    ("root", "Root - Full access"),
                    ("branch", "Cấp chi nhánh"),
                    ("block", "Cấp khối"),
                    ("department", "Cấp phòng ban"),
                ],
                default="root",
                help_text="Determines the organizational level this role can access",
                max_length=20,
                verbose_name="Data scope level",
            ),
        ),
    ]
