# Generated by Django 5.2.6 on 2026-01-08 16:16

from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ios_latest_version",
                    models.CharField(default="1.0.0", max_length=32),
                ),
                (
                    "ios_min_supported_version",
                    models.CharField(default="1.0.0", max_length=32),
                ),
                ("ios_store_url", models.URLField(blank=True, default="")),
                (
                    "android_latest_version",
                    models.CharField(default="1.0.0", max_length=32),
                ),
                (
                    "android_min_supported_version",
                    models.CharField(default="1.0.0", max_length=32),
                ),
                ("android_store_url", models.URLField(blank=True, default="")),
                ("maintenance_enabled", models.BooleanField(default=False)),
                (
                    "maintenance_message",
                    libs.models.fields.SafeTextField(blank=True, default=""),
                ),
                (
                    "feature_flags",
                    libs.models.fields.SafeTextField(blank=True, default="{}"),
                ),
                ("links_terms_url", models.URLField(blank=True, default="")),
                ("links_privacy_url", models.URLField(blank=True, default="")),
                ("links_support_url", models.URLField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_mobile_app_config",
            },
        ),
    ]
