# Generated by Django 5.2.6 on 2025-12-18 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["code"],
                "verbose_name": "Vai trò",
                "verbose_name_plural": "các Vai trò",
            },
        ),
    ]
