# Generated by Django 5.2.6 on 2025-09-27 02:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_managers_remove_user_employee_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reset_token",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Reset Token",
                    ),
                ),
                ("otp_hash", models.CharField(max_length=128, verbose_name="OTP Hash")),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Verification Attempts"),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(default=5, verbose_name="Max Attempts"),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="Is Used")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset OTP",
                "verbose_name_plural": "Password Reset OTPs",
                "db_table": "core_password_reset_otp",
                "ordering": ["-created_at"],
            },
        ),
    ]
