# Generated by Django 5.2.6 on 2026-01-09 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_mobileappconfig"),
        ("core", "0002_role_data_scope_level"),
    ]

    operations = []
