# Generated by Django 5.2.6 on 2025-12-22 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_role_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["code"],
                "verbose_name": "Vai trò",
                "verbose_name_plural": "các Vai trò",
            },
        ),
        migrations.RemoveField(
            model_name="userdevice",
            name="active",
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_token_version",
            field=models.PositiveIntegerField(default=1, verbose_name="Mobile token version"),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="client",
            field=models.CharField(
                choices=[("mobile", "Mobile"), ("web", "Web")],
                default="mobile",
                max_length=20,
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last seen at"),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="push_token",
            field=models.CharField(
                blank=True,
                help_text="Push notification token (e.g., FCM/APNS)",
                max_length=255,
                verbose_name="Push token",
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("revoked", "Revoked"),
                ],
                default="active",
                max_length=20,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_id",
            field=models.CharField(
                help_text="Client provided device identifier",
                max_length=255,
                verbose_name="Device ID",
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")],
                help_text="Device platform (iOS/Android)",
                max_length=20,
                verbose_name="Platform",
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddConstraint(
            model_name="userdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client", "mobile"), ("state", "active")),
                fields=("user",),
                name="uniq_active_mobile_device_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="userdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client", "mobile"), ("state", "active")),
                fields=("device_id",),
                name="uniq_active_mobile_device_id",
            ),
        ),
    ]
