# Generated by Django 5.2.6 on 2025-10-02 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0004_alter_user_id_userdevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Mã vai trò")),
                ("name", models.CharField(max_length=200, verbose_name="Tên vai trò")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                ("is_system_role", models.BooleanField(default=False, verbose_name="Vai trò hệ thống")),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="auth.permission", verbose_name="Quyền"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vai trò",
                "verbose_name_plural": "Vai trò",
                "db_table": "core_role",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.role",
                verbose_name="Vai trò",
            ),
        ),
    ]
