# Generated by Django 5.2.6 on 2025-10-06 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_user_id_userdevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100, unique=True, verbose_name="Mã quyền")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="Mô tả")),
            ],
            options={
                "verbose_name": "Quyền",
                "verbose_name_plural": "Quyền",
                "db_table": "core_permission",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="active_session_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="Active session"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date joined"),
        ),
        migrations.AlterField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0, verbose_name="Failed login attempts"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Locked until"),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, verbose_name="OTP code"),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="OTP expires at"),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp_verified",
            field=models.BooleanField(default=False, verbose_name="OTP verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Phone number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, unique=True, verbose_name="Username"),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Mã vai trò")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Tên vai trò")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="Mô tả")),
                ("is_system_role", models.BooleanField(default=False, verbose_name="Vai trò hệ thống")),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="core.permission", verbose_name="Quyền"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vai trò",
                "verbose_name_plural": "Vai trò",
                "db_table": "core_role",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.role",
                verbose_name="Vai trò",
            ),
        ),
    ]
