# Generated by Django 5.2.6 on 2025-10-02 08:21

from django.db import migrations


def create_default_roles(apps, schema_editor):
    """Create default system roles VT001 and VT002"""
    Role = apps.get_model("core", "Role")
    Permission = apps.get_model("auth", "Permission")

    # Create VT001 - Admin hệ thống with all permissions
    admin_role, created = Role.objects.get_or_create(
        code="VT001",
        defaults={
            "name": "Admin hệ thống",
            "description": "Vai trò có tất cả các quyền của hệ thống",
            "is_system_role": True,
        },
    )
    if created:
        # Assign all permissions to admin role
        all_permissions = Permission.objects.all()
        admin_role.permissions.set(all_permissions)

    # Create VT002 - Vai trò cơ bản
    Role.objects.get_or_create(
        code="VT002",
        defaults={
            "name": "Vai trò cơ bản",
            "description": "Vai trò mặc định của tài khoản nhân viên khi được tạo mới",
            "is_system_role": True,
        },
    )


def reverse_default_roles(apps, schema_editor):
    """Remove default system roles"""
    Role = apps.get_model("core", "Role")
    Role.objects.filter(code__in=["VT001", "VT002"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_role_model"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_default_roles, reverse_default_roles),
    ]
