# Generated by Django 5.2.6 on 2025-10-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_module_submodule_to_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["code"], "verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Role code"),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.CharField(blank=True, max_length=255, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_system_role",
            field=models.BooleanField(default=False, verbose_name="System role"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Role name"),
        ),
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="core.permission", verbose_name="Permissions"
            ),
        ),
    ]
