# Generated by Django 5.2.6 on 2025-10-03 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_change_user_roles_to_single_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="active_session_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="Active session"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date joined"),
        ),
        migrations.AlterField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0, verbose_name="Failed login attempts"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Locked until"),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, verbose_name="OTP code"),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="OTP expires at"),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp_verified",
            field=models.BooleanField(default=False, verbose_name="OTP verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Phone number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, unique=True, verbose_name="Username"),
        ),
    ]
