# Generated by Django 5.2.6 on 2025-12-23 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_userdevice_created_at_userdevice_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["code"], "verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
    ]
