# Generated by Django 5.2.6 on 2025-10-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_role_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Permission name'),
        ),
    ]
