# Generated by Django 5.2.6 on 2025-12-24 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_role_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["code"], "verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
    ]
