# Generated by Django 5.2.6 on 2025-10-06 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_user_options_alter_user_active_session_key_and_more"),
        ("core", "0008_alter_user_options_alter_user_active_session_key_and_more"),
    ]

    operations = []
