# Generated by Django 5.2.6 on 2025-10-07 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdevice",
            options={"verbose_name": "User device", "verbose_name_plural": "User devices"},
        ),
        migrations.AddField(
            model_name="userdevice",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the device is active for receiving notifications",
                verbose_name="Active",
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="fcm_token",
            field=models.CharField(
                blank=True, help_text="Firebase Cloud Messaging token", max_length=255, verbose_name="FCM token"
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")],
                help_text="Device platform (iOS, Android, or Web)",
                max_length=20,
                verbose_name="Platform",
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_id",
            field=models.CharField(
                help_text="Unique identifier for the device", max_length=255, unique=True, verbose_name="Device ID"
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
