# Generated by Django 5.2.6 on 2025-10-09 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_userdevice_options_userdevice_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier code for the province",
                        max_length=50,
                        verbose_name="Province code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the province", max_length=200, verbose_name="Province name"
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        help_text="English name of the province",
                        max_length=200,
                        verbose_name="English name",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("central_city", "Central City"), ("province", "Province")],
                        help_text="Administrative level of the province",
                        max_length=50,
                        verbose_name="Administrative level",
                    ),
                ),
                (
                    "decree",
                    models.CharField(
                        blank=True, help_text="Legal decree reference", max_length=100, verbose_name="Decree"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this province is currently enabled", verbose_name="Enabled"
                    ),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "db_table": "core_province",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("enabled", True)), fields=("code",), name="unique_enabled_province_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AdministrativeUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier code for the administrative unit",
                        max_length=50,
                        verbose_name="Unit code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the administrative unit", max_length=200, verbose_name="Unit name"
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        help_text="English name of the administrative unit",
                        max_length=200,
                        verbose_name="English name",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("district", "District"),
                            ("commune", "Commune"),
                            ("ward", "Ward"),
                            ("township", "Township"),
                        ],
                        help_text="Administrative level of the unit",
                        max_length=50,
                        verbose_name="Administrative level",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this administrative unit is currently enabled",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "parent_province",
                    models.ForeignKey(
                        help_text="Province that this unit belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrative_units",
                        to="core.province",
                        verbose_name="Parent province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Unit",
                "verbose_name_plural": "Administrative Units",
                "db_table": "core_administrative_unit",
                "ordering": ["parent_province__code", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("enabled", True)),
                        fields=("code",),
                        name="unique_enabled_administrative_unit_code",
                    )
                ],
            },
        ),
    ]
