# Generated by Django 5.2.6 on 2025-12-30 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_role_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nationality",
            options={"verbose_name": "Nationality", "verbose_name_plural": "Nationalities"},
        ),
    ]
