# Generated by Django 5.2.6 on 2025-12-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_role_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["code"],
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
    ]
