# Generated by Django 5.2.6 on 2026-01-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_nationality_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_default_role",
            field=models.BooleanField(default=False, verbose_name="Default role"),
        ),
    ]
