# Generated by Django 5.2.6 on 2025-12-31 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_nationality_options"),
        ("core", "0012_alter_role_options"),
    ]

    operations = []
