# Generated by Django 5.2.6 on 2025-12-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_nationality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdevice",
            name="fcm_token",
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_id",
            field=models.CharField(
                help_text="Firebase Cloud Messaging token", max_length=255, unique=True, verbose_name="Device ID"
            ),
        ),
    ]
