# Generated by Django 5.2.6 on 2025-12-10 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_userdevice_fcm_token_and_more"),
        ("hrm", "0103_proposal_device_change_contact_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "new_device_id",
                    models.CharField(
                        help_text="Device ID being requested for assignment",
                        max_length=255,
                        verbose_name="New Device ID",
                    ),
                ),
                (
                    "new_platform",
                    models.CharField(
                        blank=True,
                        help_text="Platform of the new device (ios, android, web)",
                        max_length=20,
                        verbose_name="New Platform",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes from the requester", null=True, verbose_name="Notes"
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        help_text="OTP code for verification (stored in plaintext for admin viewing)",
                        max_length=6,
                        verbose_name="OTP Code",
                    ),
                ),
                (
                    "otp_sent_at",
                    models.DateTimeField(help_text="Timestamp when OTP was sent", verbose_name="OTP Sent At"),
                ),
                (
                    "otp_expires_at",
                    models.DateTimeField(help_text="Timestamp when OTP expires", verbose_name="OTP Expires At"),
                ),
                (
                    "otp_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of OTP verification attempts", verbose_name="OTP Attempts"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("otp_sent", "OTP Sent"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="otp_sent",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee associated with the user (if exists)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_change_requests",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Change Request",
                "verbose_name_plural": "Device Change Requests",
                "db_table": "core_device_change_request",
                "indexes": [
                    models.Index(fields=["user"], name="dcr_user_idx"),
                    models.Index(fields=["status"], name="dcr_status_idx"),
                ],
            },
        ),
    ]
