# Generated by Django 5.2.6 on 2026-01-08 05:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_administrativeunit_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["code"],
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.RemoveField(
            model_name="devicechangerequest",
            name="employee",
        ),
    ]
