# Generated by Django 5.2.6 on 2025-12-10 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_add_device_change_request_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="devicechangerequest",
            name="dcr_request_id_idx",
        ),
        migrations.RemoveField(
            model_name="devicechangerequest",
            name="request_id",
        ),
    ]
