# Generated by Django 5.2.6 on 2026-01-08 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_role_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["code"],
                "verbose_name": "Vai trò",
                "verbose_name_plural": "các Vai trò",
            },
        ),
    ]
