# Generated by Django 5.2.6 on 2025-12-10 07:45

from django.db import migrations, models


def clear_old_device_change_requests(apps, schema_editor):
    """Clear old device change requests before renaming field.

    Old OTP hashes are 64 characters, new OTP codes are 6 characters.
    We need to clear old data before changing field size.
    """
    DeviceChangeRequest = apps.get_model("core", "DeviceChangeRequest")
    DeviceChangeRequest.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_devicechangerequest_request_id"),
    ]

    operations = [
        # Step 1: Clear old data first
        migrations.RunPython(clear_old_device_change_requests, migrations.RunPython.noop),
        # Step 2: Rename field
        migrations.RenameField(
            model_name="devicechangerequest",
            old_name="otp_hash",
            new_name="otp_code",
        ),
        # Step 3: Alter field to new size
        migrations.AlterField(
            model_name="devicechangerequest",
            name="otp_code",
            field=models.CharField(
                help_text="OTP code for verification (stored in plaintext for admin viewing)",
                max_length=6,
                verbose_name="OTP Code",
            ),
        ),
    ]
