"""Serializers for ContractAppendix model."""

from django.utils.translation import gettext as _
from rest_framework import serializers

from apps.hrm.api.serializers.common_nested import ContractNestedSerializer
from apps.hrm.models import Contract, ContractAppendix


class ContractAppendixListSerializer(serializers.ModelSerializer):
    """Serializer for ContractAppendix list view."""

    # Nested serializer for contract
    contract = ContractNestedSerializer(read_only=True)

    # appendix_number is a property that returns code
    appendix_number = serializers.CharField(read_only=True)

    class Meta:
        model = ContractAppendix
        fields = [
            "id",
            "code",
            "appendix_code",
            "appendix_number",
            "contract",
            "sign_date",
            "effective_date",
            "created_at",
        ]
        read_only_fields = fields


class ContractAppendixSerializer(serializers.ModelSerializer):
    """Serializer for ContractAppendix detail, create, and update operations.

    This serializer provides:
    - Validation: Ensures proper date logic
    - Read-only code fields (auto-generated by signal)
    """

    # Nested read-only serializer for response
    contract = ContractNestedSerializer(read_only=True)

    # Write-only field for POST/PUT/PATCH operations
    contract_id = serializers.PrimaryKeyRelatedField(
        queryset=Contract.objects.all(),
        source="contract",
        write_only=True,
        required=True,
        help_text="ID of the contract for this appendix",
    )

    # appendix_number is a property that returns code
    appendix_number = serializers.CharField(read_only=True)

    class Meta:
        model = ContractAppendix
        fields = [
            "id",
            "code",
            "appendix_code",
            "appendix_number",
            "contract",
            "contract_id",
            "sign_date",
            "effective_date",
            "content",
            "note",
            "created_at",
            "updated_at",
        ]
        read_only_fields = [
            "id",
            "code",
            "appendix_code",
            "appendix_number",
            "contract",
            "created_at",
            "updated_at",
        ]

    def validate(self, attrs):
        """Validate contract appendix data.

        Ensures that:
        - sign_date <= effective_date
        """
        instance = self.instance

        # Get dates from attrs or fallback to instance values
        sign_date = attrs.get("sign_date", getattr(instance, "sign_date", None))
        effective_date = attrs.get("effective_date", getattr(instance, "effective_date", None))

        # Validate date logic
        if sign_date and effective_date and sign_date > effective_date:
            raise serializers.ValidationError({"sign_date": _("Sign date must be on or before effective date.")})

        return attrs


class ContractAppendixExportSerializer(serializers.ModelSerializer):
    """Serializer for ContractAppendix XLSX export."""

    contract_code = serializers.CharField(source="contract.code", read_only=True)
    employee_code = serializers.CharField(source="contract.employee.code", read_only=True)
    employee_fullname = serializers.CharField(source="contract.employee.fullname", read_only=True)
    appendix_number = serializers.CharField(read_only=True)

    class Meta:
        model = ContractAppendix
        fields = [
            "code",
            "appendix_code",
            "appendix_number",
            "contract_code",
            "employee_code",
            "employee_fullname",
            "sign_date",
            "effective_date",
            "content",
            "note",
            "created_at",
        ]
