"""Tests for the import_roles management command."""

from io import StringIO

from django.core.management import call_command
from django.test import TestCase

from apps.core.models import Permission, Role


class ImportRolesCommandTest(TestCase):
    """Test cases for import_roles management command."""

    def setUp(self):
        """Clean up roles and permissions before each test."""
        Role.objects.all().delete()
        Permission.objects.all().delete()

    def _create_permissions(self, codes):
        """Helper to create Permission objects."""
        permissions = []
        for code in codes:
            perm, _ = Permission.objects.get_or_create(code=code)
            permissions.append(perm)
        return permissions

    def test_command_has_attributes_initialized(self):
        """Test that Command object has attributes properly initialized."""
        from apps.core.management.commands.import_roles import Command

        cmd = Command()
        self.assertTrue(hasattr(cmd, "verbose"))
        self.assertTrue(hasattr(cmd, "dry_run"))
        self.assertFalse(cmd.verbose)
        self.assertFalse(cmd.dry_run)

    def test_logging_works_without_errors(self):
        """Test that logging methods work without AttributeError."""
        from apps.core.management.commands.import_roles import Command

        cmd = Command()
        out = StringIO()
        cmd.stdout = out

        cmd._log("debug", "Test message")
        cmd._log("info", "Test info")
        cmd._log("warning", "Test warning")

        output = out.getvalue()
        self.assertIn("✓ Test info", output)
        self.assertIn("⚠ Test warning", output)

    def test_import_roles_from_fixtures(self):
        """Test importing roles from actual fixture files."""
        # Create some permissions that are referenced in the fixtures
        self._create_permissions(
            [
                "attendance_record.wifi_attendance",
                "attendance_record.geolocation_attendance",
                "attendance_record.retrieve",
                "attendance_record.list",
                "attendance_record.partial_update",
                "role.create",
                "role.update",
                "role.destroy",
                "user.create",
                "user.update",
                "proposal_asset_allocation.create",
                "proposal_asset_allocation.destroy",
                "proposal_asset_allocation.histories",
                "proposal_asset_allocation.history_detail",
                "proposal_asset_allocation.list",
                "proposal_asset_allocation.partial_update",
                "proposal_asset_allocation.retrieve",
                "proposal_asset_allocation.update",
                "proposal_asset_allocation.approve",
                "proposal_asset_allocation.reject",
                "proposal_device_change.create",
                "proposal_device_change.destroy",
                "proposal_device_change.histories",
                "proposal_device_change.history_detail",
                "proposal_device_change.list",
                "proposal_device_change.partial_update",
                "proposal_device_change.retrieve",
                "proposal_device_change.update",
                "proposal_device_change.approve",
                "proposal_device_change.reject",
                "proposal_device_change.export",
                "proposal_job_transfer.create",
                "proposal_job_transfer.destroy",
                "proposal_job_transfer.histories",
                "proposal_job_transfer.history_detail",
                "proposal_job_transfer.list",
                "proposal_job_transfer.partial_update",
                "proposal_job_transfer.retrieve",
                "proposal_job_transfer.update",
                "proposal_job_transfer.approve",
                "proposal_job_transfer.reject",
                "proposal_job_transfer.export",
                "proposal_late_exemption.create",
                "proposal_late_exemption.destroy",
                "proposal_late_exemption.histories",
                "proposal_late_exemption.history_detail",
                "proposal_late_exemption.list",
                "proposal_late_exemption.partial_update",
                "proposal_late_exemption.retrieve",
                "proposal_late_exemption.update",
                "proposal_late_exemption.approve",
                "proposal_late_exemption.reject",
                "proposal_late_exemption.export",
                "proposal_maternity_leave.create",
                "proposal_maternity_leave.destroy",
                "proposal_maternity_leave.histories",
                "proposal_maternity_leave.history_detail",
                "proposal_maternity_leave.list",
                "proposal_maternity_leave.partial_update",
                "proposal_maternity_leave.retrieve",
                "proposal_maternity_leave.update",
                "proposal_maternity_leave.approve",
                "proposal_maternity_leave.reject",
                "proposal_maternity_leave.export",
                "proposal_overtime_work.create",
                "proposal_overtime_work.destroy",
                "proposal_overtime_work.histories",
                "proposal_overtime_work.history_detail",
                "proposal_overtime_work.list",
                "proposal_overtime_work.partial_update",
                "proposal_overtime_work.retrieve",
                "proposal_overtime_work.update",
                "proposal_overtime_work.approve",
                "proposal_overtime_work.reject",
                "proposal_overtime_work.export",
                "proposal_paid_leave.create",
                "proposal_paid_leave.destroy",
                "proposal_paid_leave.histories",
                "proposal_paid_leave.history_detail",
                "proposal_paid_leave.list",
                "proposal_paid_leave.partial_update",
                "proposal_paid_leave.retrieve",
                "proposal_paid_leave.update",
                "proposal_paid_leave.approve",
                "proposal_paid_leave.reject",
                "proposal_paid_leave.export",
                "proposal_post_maternity_benefits.create",
                "proposal_post_maternity_benefits.destroy",
                "proposal_post_maternity_benefits.histories",
                "proposal_post_maternity_benefits.history_detail",
                "proposal_post_maternity_benefits.list",
                "proposal_post_maternity_benefits.partial_update",
                "proposal_post_maternity_benefits.retrieve",
                "proposal_post_maternity_benefits.update",
                "proposal_post_maternity_benefits.approve",
                "proposal_post_maternity_benefits.reject",
                "proposal_post_maternity_benefits.export",
                "proposal_timesheet_entry_complaint.create",
                "proposal_timesheet_entry_complaint.destroy",
                "proposal_timesheet_entry_complaint.histories",
                "proposal_timesheet_entry_complaint.history_detail",
                "proposal_timesheet_entry_complaint.list",
                "proposal_timesheet_entry_complaint.partial_update",
                "proposal_timesheet_entry_complaint.retrieve",
                "proposal_timesheet_entry_complaint.update",
                "proposal_timesheet_entry_complaint.approve",
                "proposal_timesheet_entry_complaint.reject",
                "proposal_timesheet_entry_complaint.export",
                "proposal_unpaid_leave.create",
                "proposal_unpaid_leave.destroy",
                "proposal_unpaid_leave.histories",
                "proposal_unpaid_leave.history_detail",
                "proposal_unpaid_leave.list",
                "proposal_unpaid_leave.partial_update",
                "proposal_unpaid_leave.retrieve",
                "proposal_unpaid_leave.update",
                "proposal_unpaid_leave.approve",
                "proposal_unpaid_leave.reject",
                "proposal_unpaid_leave.export",
                "proposal.histories",
                "proposal.history_detail",
                "proposal.list",
                "proposal.mine",
                "proposal.retrieve",
                "proposal.verify",
                "proposal.export",
                "proposal_verifier.create",
                "proposal_verifier.destroy",
                "proposal_verifier.histories",
                "proposal_verifier.history_detail",
                "proposal_verifier.list",
                "proposal_verifier.mine",
                "proposal_verifier.partial_update",
                "proposal_verifier.retrieve",
                "proposal_verifier.update",
                "proposal_verifier.verify",
                "proposal_verifier.reject",
                "recruitment_application.create",
                "recruitment_application.destroy",
                "recruitment_application.histories",
                "recruitment_application.history_detail",
                "recruitment_application.list",
                "recruitment_application.partial_update",
                "recruitment_application.retrieve",
                "recruitment_application.update",
                "recruitment_job_post.create",
                "recruitment_job_post.destroy",
                "recruitment_job_post.histories",
                "recruitment_job_post.history_detail",
                "recruitment_job_post.list",
                "recruitment_job_post.partial_update",
                "recruitment_job_post.retrieve",
                "recruitment_job_post.update",
            ]
        )

        out = StringIO()
        call_command("import_roles", stdout=out, stderr=StringIO())

        # Verify roles were imported
        self.assertGreaterEqual(Role.objects.count(), 4)

        # Check specific roles
        admin_role = Role.objects.get(code="VT000000001")
        self.assertEqual(admin_role.name, "System Admin")
        self.assertTrue(admin_role.is_system_role)

        employee_role = Role.objects.get(code="VT000000002")
        self.assertEqual(employee_role.name, "Nhân viên")
        self.assertTrue(employee_role.is_system_role)

    def test_import_roles_has_correct_permissions(self):
        """Test that imported roles have correct permissions assigned."""
        # Create all needed permissions for fixture roles
        self._create_permissions(
            [
                "attendance_record.wifi_attendance",
                "attendance_record.geolocation_attendance",
                "attendance_record.retrieve",
                "attendance_record.list",
                "attendance_record.partial_update",
                "role.create",
                "role.update",
                "role.destroy",
                "user.create",
                "user.update",
                "proposal_asset_allocation.create",
                "proposal_asset_allocation.destroy",
                "proposal_asset_allocation.histories",
                "proposal_asset_allocation.history_detail",
                "proposal_asset_allocation.list",
                "proposal_asset_allocation.partial_update",
                "proposal_asset_allocation.retrieve",
                "proposal_asset_allocation.update",
                "proposal_asset_allocation.approve",
                "proposal_asset_allocation.reject",
                "proposal_device_change.create",
                "proposal_device_change.destroy",
                "proposal_device_change.histories",
                "proposal_device_change.history_detail",
                "proposal_device_change.list",
                "proposal_device_change.partial_update",
                "proposal_device_change.retrieve",
                "proposal_device_change.update",
                "proposal_device_change.approve",
                "proposal_device_change.reject",
                "proposal_device_change.export",
                "proposal_job_transfer.create",
                "proposal_job_transfer.destroy",
                "proposal_job_transfer.histories",
                "proposal_job_transfer.history_detail",
                "proposal_job_transfer.list",
                "proposal_job_transfer.partial_update",
                "proposal_job_transfer.retrieve",
                "proposal_job_transfer.update",
                "proposal_job_transfer.approve",
                "proposal_job_transfer.reject",
                "proposal_job_transfer.export",
                "proposal_late_exemption.create",
                "proposal_late_exemption.destroy",
                "proposal_late_exemption.histories",
                "proposal_late_exemption.history_detail",
                "proposal_late_exemption.list",
                "proposal_late_exemption.partial_update",
                "proposal_late_exemption.retrieve",
                "proposal_late_exemption.update",
                "proposal_late_exemption.approve",
                "proposal_late_exemption.reject",
                "proposal_late_exemption.export",
                "proposal_maternity_leave.create",
                "proposal_maternity_leave.destroy",
                "proposal_maternity_leave.histories",
                "proposal_maternity_leave.history_detail",
                "proposal_maternity_leave.list",
                "proposal_maternity_leave.partial_update",
                "proposal_maternity_leave.retrieve",
                "proposal_maternity_leave.update",
                "proposal_maternity_leave.approve",
                "proposal_maternity_leave.reject",
                "proposal_maternity_leave.export",
                "proposal_overtime_work.create",
                "proposal_overtime_work.destroy",
                "proposal_overtime_work.histories",
                "proposal_overtime_work.history_detail",
                "proposal_overtime_work.list",
                "proposal_overtime_work.partial_update",
                "proposal_overtime_work.retrieve",
                "proposal_overtime_work.update",
                "proposal_overtime_work.approve",
                "proposal_overtime_work.reject",
                "proposal_overtime_work.export",
                "proposal_paid_leave.create",
                "proposal_paid_leave.destroy",
                "proposal_paid_leave.histories",
                "proposal_paid_leave.history_detail",
                "proposal_paid_leave.list",
                "proposal_paid_leave.partial_update",
                "proposal_paid_leave.retrieve",
                "proposal_paid_leave.update",
                "proposal_paid_leave.approve",
                "proposal_paid_leave.reject",
                "proposal_paid_leave.export",
                "proposal_post_maternity_benefits.create",
                "proposal_post_maternity_benefits.destroy",
                "proposal_post_maternity_benefits.histories",
                "proposal_post_maternity_benefits.history_detail",
                "proposal_post_maternity_benefits.list",
                "proposal_post_maternity_benefits.partial_update",
                "proposal_post_maternity_benefits.retrieve",
                "proposal_post_maternity_benefits.update",
                "proposal_post_maternity_benefits.approve",
                "proposal_post_maternity_benefits.reject",
                "proposal_post_maternity_benefits.export",
                "proposal_timesheet_entry_complaint.create",
                "proposal_timesheet_entry_complaint.destroy",
                "proposal_timesheet_entry_complaint.histories",
                "proposal_timesheet_entry_complaint.history_detail",
                "proposal_timesheet_entry_complaint.list",
                "proposal_timesheet_entry_complaint.partial_update",
                "proposal_timesheet_entry_complaint.retrieve",
                "proposal_timesheet_entry_complaint.update",
                "proposal_timesheet_entry_complaint.approve",
                "proposal_timesheet_entry_complaint.reject",
                "proposal_timesheet_entry_complaint.export",
                "proposal_unpaid_leave.create",
                "proposal_unpaid_leave.destroy",
                "proposal_unpaid_leave.histories",
                "proposal_unpaid_leave.history_detail",
                "proposal_unpaid_leave.list",
                "proposal_unpaid_leave.partial_update",
                "proposal_unpaid_leave.retrieve",
                "proposal_unpaid_leave.update",
                "proposal_unpaid_leave.approve",
                "proposal_unpaid_leave.reject",
                "proposal_unpaid_leave.export",
                "proposal.histories",
                "proposal.history_detail",
                "proposal.list",
                "proposal.mine",
                "proposal.retrieve",
                "proposal.verify",
                "proposal.export",
                "proposal_verifier.create",
                "proposal_verifier.destroy",
                "proposal_verifier.histories",
                "proposal_verifier.history_detail",
                "proposal_verifier.list",
                "proposal_verifier.mine",
                "proposal_verifier.partial_update",
                "proposal_verifier.retrieve",
                "proposal_verifier.update",
                "proposal_verifier.verify",
                "proposal_verifier.reject",
                "recruitment_application.create",
                "recruitment_application.destroy",
                "recruitment_application.histories",
                "recruitment_application.history_detail",
                "recruitment_application.list",
                "recruitment_application.partial_update",
                "recruitment_application.retrieve",
                "recruitment_application.update",
                "recruitment_job_post.create",
                "recruitment_job_post.destroy",
                "recruitment_job_post.histories",
                "recruitment_job_post.history_detail",
                "recruitment_job_post.list",
                "recruitment_job_post.partial_update",
                "recruitment_job_post.retrieve",
                "recruitment_job_post.update",
            ]
        )

        out = StringIO()
        call_command("import_roles", stdout=out, stderr=StringIO())

        # Employee role should have attendance_record permissions
        employee_role = Role.objects.get(code="VT000000002")
        employee_perms = set(employee_role.permissions.values_list("code", flat=True))

        self.assertIn("attendance_record.wifi_attendance", employee_perms)
        self.assertIn("attendance_record.geolocation_attendance", employee_perms)
        self.assertIn("attendance_record.retrieve", employee_perms)
        self.assertIn("attendance_record.list", employee_perms)

    def test_import_updates_existing_role(self):
        """Test that import updates an existing role's metadata."""
        # Create existing role with old name
        Role.objects.create(code="VT000000002", name="Old Name", is_system_role=False)

        # Create permissions
        self._create_permissions(
            [
                "attendance_record.wifi_attendance",
                "attendance_record.geolocation_attendance",
                "attendance_record.retrieve",
                "attendance_record.list",
                "attendance_record.partial_update",
                "role.create",
                "role.update",
                "role.destroy",
                "user.create",
                "user.update",
                "proposal_asset_allocation.create",
                "proposal_asset_allocation.destroy",
                "proposal_asset_allocation.histories",
                "proposal_asset_allocation.history_detail",
                "proposal_asset_allocation.list",
                "proposal_asset_allocation.partial_update",
                "proposal_asset_allocation.retrieve",
                "proposal_asset_allocation.update",
                "proposal_asset_allocation.approve",
                "proposal_asset_allocation.reject",
                "proposal_device_change.create",
                "proposal_device_change.destroy",
                "proposal_device_change.histories",
                "proposal_device_change.history_detail",
                "proposal_device_change.list",
                "proposal_device_change.partial_update",
                "proposal_device_change.retrieve",
                "proposal_device_change.update",
                "proposal_device_change.approve",
                "proposal_device_change.reject",
                "proposal_device_change.export",
                "proposal_job_transfer.create",
                "proposal_job_transfer.destroy",
                "proposal_job_transfer.histories",
                "proposal_job_transfer.history_detail",
                "proposal_job_transfer.list",
                "proposal_job_transfer.partial_update",
                "proposal_job_transfer.retrieve",
                "proposal_job_transfer.update",
                "proposal_job_transfer.approve",
                "proposal_job_transfer.reject",
                "proposal_job_transfer.export",
                "proposal_late_exemption.create",
                "proposal_late_exemption.destroy",
                "proposal_late_exemption.histories",
                "proposal_late_exemption.history_detail",
                "proposal_late_exemption.list",
                "proposal_late_exemption.partial_update",
                "proposal_late_exemption.retrieve",
                "proposal_late_exemption.update",
                "proposal_late_exemption.approve",
                "proposal_late_exemption.reject",
                "proposal_late_exemption.export",
                "proposal_maternity_leave.create",
                "proposal_maternity_leave.destroy",
                "proposal_maternity_leave.histories",
                "proposal_maternity_leave.history_detail",
                "proposal_maternity_leave.list",
                "proposal_maternity_leave.partial_update",
                "proposal_maternity_leave.retrieve",
                "proposal_maternity_leave.update",
                "proposal_maternity_leave.approve",
                "proposal_maternity_leave.reject",
                "proposal_maternity_leave.export",
                "proposal_overtime_work.create",
                "proposal_overtime_work.destroy",
                "proposal_overtime_work.histories",
                "proposal_overtime_work.history_detail",
                "proposal_overtime_work.list",
                "proposal_overtime_work.partial_update",
                "proposal_overtime_work.retrieve",
                "proposal_overtime_work.update",
                "proposal_overtime_work.approve",
                "proposal_overtime_work.reject",
                "proposal_overtime_work.export",
                "proposal_paid_leave.create",
                "proposal_paid_leave.destroy",
                "proposal_paid_leave.histories",
                "proposal_paid_leave.history_detail",
                "proposal_paid_leave.list",
                "proposal_paid_leave.partial_update",
                "proposal_paid_leave.retrieve",
                "proposal_paid_leave.update",
                "proposal_paid_leave.approve",
                "proposal_paid_leave.reject",
                "proposal_paid_leave.export",
                "proposal_post_maternity_benefits.create",
                "proposal_post_maternity_benefits.destroy",
                "proposal_post_maternity_benefits.histories",
                "proposal_post_maternity_benefits.history_detail",
                "proposal_post_maternity_benefits.list",
                "proposal_post_maternity_benefits.partial_update",
                "proposal_post_maternity_benefits.retrieve",
                "proposal_post_maternity_benefits.update",
                "proposal_post_maternity_benefits.approve",
                "proposal_post_maternity_benefits.reject",
                "proposal_post_maternity_benefits.export",
                "proposal_timesheet_entry_complaint.create",
                "proposal_timesheet_entry_complaint.destroy",
                "proposal_timesheet_entry_complaint.histories",
                "proposal_timesheet_entry_complaint.history_detail",
                "proposal_timesheet_entry_complaint.list",
                "proposal_timesheet_entry_complaint.partial_update",
                "proposal_timesheet_entry_complaint.retrieve",
                "proposal_timesheet_entry_complaint.update",
                "proposal_timesheet_entry_complaint.approve",
                "proposal_timesheet_entry_complaint.reject",
                "proposal_timesheet_entry_complaint.export",
                "proposal_unpaid_leave.create",
                "proposal_unpaid_leave.destroy",
                "proposal_unpaid_leave.histories",
                "proposal_unpaid_leave.history_detail",
                "proposal_unpaid_leave.list",
                "proposal_unpaid_leave.partial_update",
                "proposal_unpaid_leave.retrieve",
                "proposal_unpaid_leave.update",
                "proposal_unpaid_leave.approve",
                "proposal_unpaid_leave.reject",
                "proposal_unpaid_leave.export",
                "proposal.histories",
                "proposal.history_detail",
                "proposal.list",
                "proposal.mine",
                "proposal.retrieve",
                "proposal.verify",
                "proposal.export",
                "proposal_verifier.create",
                "proposal_verifier.destroy",
                "proposal_verifier.histories",
                "proposal_verifier.history_detail",
                "proposal_verifier.list",
                "proposal_verifier.mine",
                "proposal_verifier.partial_update",
                "proposal_verifier.retrieve",
                "proposal_verifier.update",
                "proposal_verifier.verify",
                "proposal_verifier.reject",
                "recruitment_application.create",
                "recruitment_application.destroy",
                "recruitment_application.histories",
                "recruitment_application.history_detail",
                "recruitment_application.list",
                "recruitment_application.partial_update",
                "recruitment_application.retrieve",
                "recruitment_application.update",
                "recruitment_job_post.create",
                "recruitment_job_post.destroy",
                "recruitment_job_post.histories",
                "recruitment_job_post.history_detail",
                "recruitment_job_post.list",
                "recruitment_job_post.partial_update",
                "recruitment_job_post.retrieve",
                "recruitment_job_post.update",
            ]
        )

        out = StringIO()
        call_command("import_roles", stdout=out, stderr=StringIO())

        # Role should be updated
        role = Role.objects.get(code="VT000000002")
        self.assertEqual(role.name, "Nhân viên")
        self.assertTrue(role.is_system_role)

    def test_verbose_flag_shows_debug_messages(self):
        """Test that --verbose flag shows debug messages."""
        self._create_permissions(
            [
                "attendance_record.wifi_attendance",
                "attendance_record.geolocation_attendance",
                "attendance_record.retrieve",
                "attendance_record.list",
                "attendance_record.partial_update",
                "role.create",
                "role.update",
                "role.destroy",
                "user.create",
                "user.update",
                "proposal_asset_allocation.create",
                "proposal_asset_allocation.destroy",
                "proposal_asset_allocation.histories",
                "proposal_asset_allocation.history_detail",
                "proposal_asset_allocation.list",
                "proposal_asset_allocation.partial_update",
                "proposal_asset_allocation.retrieve",
                "proposal_asset_allocation.update",
                "proposal_asset_allocation.approve",
                "proposal_asset_allocation.reject",
                "proposal_device_change.create",
                "proposal_device_change.destroy",
                "proposal_device_change.histories",
                "proposal_device_change.history_detail",
                "proposal_device_change.list",
                "proposal_device_change.partial_update",
                "proposal_device_change.retrieve",
                "proposal_device_change.update",
                "proposal_device_change.approve",
                "proposal_device_change.reject",
                "proposal_device_change.export",
                "proposal_job_transfer.create",
                "proposal_job_transfer.destroy",
                "proposal_job_transfer.histories",
                "proposal_job_transfer.history_detail",
                "proposal_job_transfer.list",
                "proposal_job_transfer.partial_update",
                "proposal_job_transfer.retrieve",
                "proposal_job_transfer.update",
                "proposal_job_transfer.approve",
                "proposal_job_transfer.reject",
                "proposal_job_transfer.export",
                "proposal_late_exemption.create",
                "proposal_late_exemption.destroy",
                "proposal_late_exemption.histories",
                "proposal_late_exemption.history_detail",
                "proposal_late_exemption.list",
                "proposal_late_exemption.partial_update",
                "proposal_late_exemption.retrieve",
                "proposal_late_exemption.update",
                "proposal_late_exemption.approve",
                "proposal_late_exemption.reject",
                "proposal_late_exemption.export",
                "proposal_maternity_leave.create",
                "proposal_maternity_leave.destroy",
                "proposal_maternity_leave.histories",
                "proposal_maternity_leave.history_detail",
                "proposal_maternity_leave.list",
                "proposal_maternity_leave.partial_update",
                "proposal_maternity_leave.retrieve",
                "proposal_maternity_leave.update",
                "proposal_maternity_leave.approve",
                "proposal_maternity_leave.reject",
                "proposal_maternity_leave.export",
                "proposal_overtime_work.create",
                "proposal_overtime_work.destroy",
                "proposal_overtime_work.histories",
                "proposal_overtime_work.history_detail",
                "proposal_overtime_work.list",
                "proposal_overtime_work.partial_update",
                "proposal_overtime_work.retrieve",
                "proposal_overtime_work.update",
                "proposal_overtime_work.approve",
                "proposal_overtime_work.reject",
                "proposal_overtime_work.export",
                "proposal_paid_leave.create",
                "proposal_paid_leave.destroy",
                "proposal_paid_leave.histories",
                "proposal_paid_leave.history_detail",
                "proposal_paid_leave.list",
                "proposal_paid_leave.partial_update",
                "proposal_paid_leave.retrieve",
                "proposal_paid_leave.update",
                "proposal_paid_leave.approve",
                "proposal_paid_leave.reject",
                "proposal_paid_leave.export",
                "proposal_post_maternity_benefits.create",
                "proposal_post_maternity_benefits.destroy",
                "proposal_post_maternity_benefits.histories",
                "proposal_post_maternity_benefits.history_detail",
                "proposal_post_maternity_benefits.list",
                "proposal_post_maternity_benefits.partial_update",
                "proposal_post_maternity_benefits.retrieve",
                "proposal_post_maternity_benefits.update",
                "proposal_post_maternity_benefits.approve",
                "proposal_post_maternity_benefits.reject",
                "proposal_post_maternity_benefits.export",
                "proposal_timesheet_entry_complaint.create",
                "proposal_timesheet_entry_complaint.destroy",
                "proposal_timesheet_entry_complaint.histories",
                "proposal_timesheet_entry_complaint.history_detail",
                "proposal_timesheet_entry_complaint.list",
                "proposal_timesheet_entry_complaint.partial_update",
                "proposal_timesheet_entry_complaint.retrieve",
                "proposal_timesheet_entry_complaint.update",
                "proposal_timesheet_entry_complaint.approve",
                "proposal_timesheet_entry_complaint.reject",
                "proposal_timesheet_entry_complaint.export",
                "proposal_unpaid_leave.create",
                "proposal_unpaid_leave.destroy",
                "proposal_unpaid_leave.histories",
                "proposal_unpaid_leave.history_detail",
                "proposal_unpaid_leave.list",
                "proposal_unpaid_leave.partial_update",
                "proposal_unpaid_leave.retrieve",
                "proposal_unpaid_leave.update",
                "proposal_unpaid_leave.approve",
                "proposal_unpaid_leave.reject",
                "proposal_unpaid_leave.export",
                "proposal.histories",
                "proposal.history_detail",
                "proposal.list",
                "proposal.mine",
                "proposal.retrieve",
                "proposal.verify",
                "proposal.export",
                "proposal_verifier.create",
                "proposal_verifier.destroy",
                "proposal_verifier.histories",
                "proposal_verifier.history_detail",
                "proposal_verifier.list",
                "proposal_verifier.mine",
                "proposal_verifier.partial_update",
                "proposal_verifier.retrieve",
                "proposal_verifier.update",
                "proposal_verifier.verify",
                "proposal_verifier.reject",
                "recruitment_application.create",
                "recruitment_application.destroy",
                "recruitment_application.histories",
                "recruitment_application.history_detail",
                "recruitment_application.list",
                "recruitment_application.partial_update",
                "recruitment_application.retrieve",
                "recruitment_application.update",
                "recruitment_job_post.create",
                "recruitment_job_post.destroy",
                "recruitment_job_post.histories",
                "recruitment_job_post.history_detail",
                "recruitment_job_post.list",
                "recruitment_job_post.partial_update",
                "recruitment_job_post.retrieve",
                "recruitment_job_post.update",
            ]
        )

        out = StringIO()
        call_command("import_roles", verbose=True, stdout=out, stderr=StringIO())

        output = out.getvalue()
        self.assertIn("→", output)  # Debug output marker

    def test_dry_run_does_not_modify_database(self):
        """Test that --dry-run option prevents database changes."""
        self._create_permissions(
            [
                "attendance_record.wifi_attendance",
                "attendance_record.geolocation_attendance",
                "attendance_record.retrieve",
                "attendance_record.list",
                "attendance_record.partial_update",
                "role.create",
                "role.update",
                "role.destroy",
                "user.create",
                "user.update",
                "proposal_asset_allocation.create",
                "proposal_asset_allocation.destroy",
                "proposal_asset_allocation.histories",
                "proposal_asset_allocation.history_detail",
                "proposal_asset_allocation.list",
                "proposal_asset_allocation.partial_update",
                "proposal_asset_allocation.retrieve",
                "proposal_asset_allocation.update",
                "proposal_asset_allocation.approve",
                "proposal_asset_allocation.reject",
                "proposal_device_change.create",
                "proposal_device_change.destroy",
                "proposal_device_change.histories",
                "proposal_device_change.history_detail",
                "proposal_device_change.list",
                "proposal_device_change.partial_update",
                "proposal_device_change.retrieve",
                "proposal_device_change.update",
                "proposal_device_change.approve",
                "proposal_device_change.reject",
                "proposal_device_change.export",
                "proposal_job_transfer.create",
                "proposal_job_transfer.destroy",
                "proposal_job_transfer.histories",
                "proposal_job_transfer.history_detail",
                "proposal_job_transfer.list",
                "proposal_job_transfer.partial_update",
                "proposal_job_transfer.retrieve",
                "proposal_job_transfer.update",
                "proposal_job_transfer.approve",
                "proposal_job_transfer.reject",
                "proposal_job_transfer.export",
                "proposal_late_exemption.create",
                "proposal_late_exemption.destroy",
                "proposal_late_exemption.histories",
                "proposal_late_exemption.history_detail",
                "proposal_late_exemption.list",
                "proposal_late_exemption.partial_update",
                "proposal_late_exemption.retrieve",
                "proposal_late_exemption.update",
                "proposal_late_exemption.approve",
                "proposal_late_exemption.reject",
                "proposal_late_exemption.export",
                "proposal_maternity_leave.create",
                "proposal_maternity_leave.destroy",
                "proposal_maternity_leave.histories",
                "proposal_maternity_leave.history_detail",
                "proposal_maternity_leave.list",
                "proposal_maternity_leave.partial_update",
                "proposal_maternity_leave.retrieve",
                "proposal_maternity_leave.update",
                "proposal_maternity_leave.approve",
                "proposal_maternity_leave.reject",
                "proposal_maternity_leave.export",
                "proposal_overtime_work.create",
                "proposal_overtime_work.destroy",
                "proposal_overtime_work.histories",
                "proposal_overtime_work.history_detail",
                "proposal_overtime_work.list",
                "proposal_overtime_work.partial_update",
                "proposal_overtime_work.retrieve",
                "proposal_overtime_work.update",
                "proposal_overtime_work.approve",
                "proposal_overtime_work.reject",
                "proposal_overtime_work.export",
                "proposal_paid_leave.create",
                "proposal_paid_leave.destroy",
                "proposal_paid_leave.histories",
                "proposal_paid_leave.history_detail",
                "proposal_paid_leave.list",
                "proposal_paid_leave.partial_update",
                "proposal_paid_leave.retrieve",
                "proposal_paid_leave.update",
                "proposal_paid_leave.approve",
                "proposal_paid_leave.reject",
                "proposal_paid_leave.export",
                "proposal_post_maternity_benefits.create",
                "proposal_post_maternity_benefits.destroy",
                "proposal_post_maternity_benefits.histories",
                "proposal_post_maternity_benefits.history_detail",
                "proposal_post_maternity_benefits.list",
                "proposal_post_maternity_benefits.partial_update",
                "proposal_post_maternity_benefits.retrieve",
                "proposal_post_maternity_benefits.update",
                "proposal_post_maternity_benefits.approve",
                "proposal_post_maternity_benefits.reject",
                "proposal_post_maternity_benefits.export",
                "proposal_timesheet_entry_complaint.create",
                "proposal_timesheet_entry_complaint.destroy",
                "proposal_timesheet_entry_complaint.histories",
                "proposal_timesheet_entry_complaint.history_detail",
                "proposal_timesheet_entry_complaint.list",
                "proposal_timesheet_entry_complaint.partial_update",
                "proposal_timesheet_entry_complaint.retrieve",
                "proposal_timesheet_entry_complaint.update",
                "proposal_timesheet_entry_complaint.approve",
                "proposal_timesheet_entry_complaint.reject",
                "proposal_timesheet_entry_complaint.export",
                "proposal_unpaid_leave.create",
                "proposal_unpaid_leave.destroy",
                "proposal_unpaid_leave.histories",
                "proposal_unpaid_leave.history_detail",
                "proposal_unpaid_leave.list",
                "proposal_unpaid_leave.partial_update",
                "proposal_unpaid_leave.retrieve",
                "proposal_unpaid_leave.update",
                "proposal_unpaid_leave.approve",
                "proposal_unpaid_leave.reject",
                "proposal_unpaid_leave.export",
                "proposal.histories",
                "proposal.history_detail",
                "proposal.list",
                "proposal.mine",
                "proposal.retrieve",
                "proposal.verify",
                "proposal.export",
                "proposal_verifier.create",
                "proposal_verifier.destroy",
                "proposal_verifier.histories",
                "proposal_verifier.history_detail",
                "proposal_verifier.list",
                "proposal_verifier.mine",
                "proposal_verifier.partial_update",
                "proposal_verifier.retrieve",
                "proposal_verifier.update",
                "proposal_verifier.verify",
                "proposal_verifier.reject",
                "recruitment_application.create",
                "recruitment_application.destroy",
                "recruitment_application.histories",
                "recruitment_application.history_detail",
                "recruitment_application.list",
                "recruitment_application.partial_update",
                "recruitment_application.retrieve",
                "recruitment_application.update",
                "recruitment_job_post.create",
                "recruitment_job_post.destroy",
                "recruitment_job_post.histories",
                "recruitment_job_post.history_detail",
                "recruitment_job_post.list",
                "recruitment_job_post.partial_update",
                "recruitment_job_post.retrieve",
                "recruitment_job_post.update",
            ]
        )

        # Get count before dry-run
        role_count_before = Role.objects.count()

        out = StringIO()
        call_command("import_roles", dry_run=True, stdout=out, stderr=StringIO())

        # Verify database was not changed
        role_count_after = Role.objects.count()
        self.assertEqual(role_count_before, role_count_after)

        # Verify dry-run message was shown
        output = out.getvalue()
        self.assertIn("DRY-RUN mode", output)
