# Generated by Django 5.2.6 on 2026-01-08 07:03

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("hrm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("config", models.JSONField(verbose_name="KPI Configuration")),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
            ],
            options={
                "verbose_name": "KPI Configuration",
                "verbose_name_plural": "KPI Configurations",
                "db_table": "payroll_kpi_config",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="SalaryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("config", models.JSONField(verbose_name="Salary Configuration")),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
            ],
            options={
                "verbose_name": "Salary Configuration",
                "verbose_name_plural": "Salary Configurations",
                "db_table": "payroll_salary_config",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="KPIAssessmentPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "month",
                    models.DateField(
                        help_text="First day of the assessment month",
                        unique=True,
                        verbose_name="Assessment month",
                    ),
                ),
                (
                    "kpi_config_snapshot",
                    models.JSONField(
                        help_text="Snapshot of KPIConfig used for this assessment period",
                        verbose_name="KPI config snapshot",
                    ),
                ),
                (
                    "finalized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the entire assessment period is locked (no further edits)",
                        verbose_name="Finalized",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or comments",
                        verbose_name="Note",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this period",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_periods_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this period",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_periods_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Assessment Period",
                "verbose_name_plural": "KPI Assessment Periods",
                "db_table": "payroll_kpi_assessment_period",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeKPIAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Mới"),
                            ("waiting_manager", "Chờ đánh giá"),
                            ("completed", "Đã hoàn thành"),
                        ],
                        default="new",
                        help_text="Assessment status (system-managed)",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_possible_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all component_total_score from items",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Total possible score",
                    ),
                ),
                (
                    "total_employee_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sum of all employee scores from items",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Total employee score",
                    ),
                ),
                (
                    "total_manager_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sum of all manager scores from items",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Total manager score",
                    ),
                ),
                (
                    "grade_manager",
                    models.CharField(
                        blank=True,
                        help_text="Final grade used for payroll (A/B/C/D)",
                        max_length=10,
                        null=True,
                        verbose_name="Manager grade",
                    ),
                ),
                (
                    "grade_manager_overridden",
                    models.CharField(
                        blank=True,
                        help_text="Manager's explicit grade override",
                        max_length=10,
                        null=True,
                        verbose_name="Manager grade override",
                    ),
                ),
                (
                    "plan_tasks",
                    libs.models.fields.SafeTextField(
                        blank=True,
                        help_text="Planned tasks for the assessment period",
                        verbose_name="Plan tasks",
                    ),
                ),
                (
                    "extra_tasks",
                    libs.models.fields.SafeTextField(
                        blank=True,
                        help_text="Extra tasks handled during the period",
                        verbose_name="Extra tasks",
                    ),
                ),
                (
                    "proposal",
                    libs.models.fields.SafeTextField(
                        blank=True,
                        help_text="Employee's proposals or suggestions",
                        verbose_name="Proposal",
                    ),
                ),
                (
                    "manager_assessment",
                    libs.models.fields.SafeTextField(
                        blank=True,
                        help_text="Manager's assessment comments and feedback",
                        verbose_name="Manager assessment",
                    ),
                ),
                (
                    "manager_assessment_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when manager completed assessment",
                        null=True,
                        verbose_name="Manager assessment date",
                    ),
                ),
                (
                    "grade_hrm",
                    models.CharField(
                        blank=True,
                        help_text="HRM department's final grade assessment",
                        max_length=10,
                        null=True,
                        verbose_name="HRM grade",
                    ),
                ),
                (
                    "hrm_assessed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether HRM has assessed this",
                        verbose_name="HRM assessed",
                    ),
                ),
                (
                    "hrm_assessment_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when HRM completed assessment",
                        null=True,
                        verbose_name="HRM assessment date",
                    ),
                ),
                (
                    "finalized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether assessment is locked (no further edits)",
                        verbose_name="Finalized",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or comments",
                        verbose_name="Note",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this assessment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_assessments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "department_snapshot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee's department when KPI period was generated (snapshot)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_kpi_assessments",
                        to="hrm.department",
                        verbose_name="Department Snapshot",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee being assessed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpi_assessments",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager responsible for assessing this employee (from department leader)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_kpi_assessments",
                        to="hrm.employee",
                        verbose_name="Manager",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this assessment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_assessments_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="KPI assessment period this assessment belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assessments",
                        to="payroll.kpiassessmentperiod",
                        verbose_name="Assessment period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee KPI Assessment",
                "verbose_name_plural": "Employee KPI Assessments",
                "db_table": "payroll_employee_kpi_assessment",
                "ordering": ["-period__month", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentKPIAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "grade",
                    models.CharField(
                        help_text="Department's grade (A/B/C/D)",
                        max_length=10,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "default_grade",
                    models.CharField(
                        default="C",
                        help_text="Default grade when auto-created",
                        max_length=10,
                        verbose_name="Default grade",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when grade was assigned",
                        null=True,
                        verbose_name="Assigned at",
                    ),
                ),
                (
                    "finalized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether assessment is locked",
                        verbose_name="Finalized",
                    ),
                ),
                (
                    "is_finished",
                    models.BooleanField(
                        default=False,
                        help_text="Whether all employees in this department have been graded",
                        verbose_name="Is finished",
                    ),
                ),
                (
                    "is_valid_unit_control",
                    models.BooleanField(
                        default=True,
                        help_text="This department valid unit control or not",
                        verbose_name="Is valid unit control",
                    ),
                ),
                (
                    "grade_distribution",
                    models.JSONField(
                        default=dict,
                        help_text="Number of employees by grade: {'A': 2, 'B': 5, 'C': 10, 'D': 1}",
                        verbose_name="Grade distribution",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, help_text="Additional notes", verbose_name="Note"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who assigned the grade",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_kpi_assessments_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this assessment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_kpi_assessments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department being assessed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpi_assessments",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this assessment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_kpi_assessments_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="KPI assessment period this assessment belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="department_assessments",
                        to="payroll.kpiassessmentperiod",
                        verbose_name="Assessment period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department KPI Assessment",
                "verbose_name_plural": "Department KPI Assessments",
                "db_table": "payroll_department_kpi_assessment",
                "ordering": ["-period__month", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPICriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "target",
                    models.CharField(
                        choices=[("sales", "Sales"), ("backoffice", "Backoffice")],
                        default="sales",
                        help_text="Target group or role",
                        max_length=200,
                        verbose_name="Target",
                    ),
                ),
                (
                    "evaluation_type",
                    models.CharField(
                        choices=[
                            ("work_performance", "Work Performance"),
                            ("discipline", "Discipline"),
                        ],
                        help_text="Type of evaluation (work performance or discipline)",
                        max_length=50,
                        verbose_name="Evaluation type",
                    ),
                ),
                (
                    "criterion",
                    models.CharField(
                        help_text="Main evaluation criterion",
                        max_length=255,
                        verbose_name="Criterion",
                    ),
                ),
                (
                    "sub_criterion",
                    models.CharField(
                        blank=True,
                        help_text="Additional details for the criterion",
                        max_length=255,
                        null=True,
                        verbose_name="Sub-criterion",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the criterion",
                        verbose_name="Description",
                    ),
                ),
                (
                    "component_total_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum percentage score (0-100)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Component total score",
                    ),
                ),
                (
                    "group_number",
                    models.IntegerField(
                        help_text="Group number for displaying criteria in the same block",
                        verbose_name="Group number",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Display order within evaluation type",
                        verbose_name="Order",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this criterion is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this criterion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_criteria_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this criterion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_criteria_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Criterion",
                "verbose_name_plural": "KPI Criteria",
                "db_table": "payroll_kpi_criterion",
                "ordering": ["evaluation_type", "order"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeKPIItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "target",
                    models.CharField(
                        choices=[("sales", "Sales"), ("backoffice", "Backoffice")],
                        help_text="Snapshot of target group or role",
                        max_length=200,
                        verbose_name="Target",
                    ),
                ),
                (
                    "criterion",
                    models.CharField(
                        help_text="Snapshot of criterion name",
                        max_length=255,
                        verbose_name="Criterion",
                    ),
                ),
                (
                    "sub_criterion",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of sub-criterion",
                        max_length=255,
                        null=True,
                        verbose_name="Sub-criterion",
                    ),
                ),
                (
                    "evaluation_type",
                    models.CharField(
                        choices=[
                            ("work_performance", "Work Performance"),
                            ("discipline", "Discipline"),
                        ],
                        help_text="Snapshot of evaluation type",
                        max_length=50,
                        verbose_name="Evaluation type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Snapshot of criterion description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "component_total_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of maximum score",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Component total score",
                    ),
                ),
                (
                    "group_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Snapshot of group number for UI display",
                        null=True,
                        verbose_name="Group number",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(help_text="Display order", verbose_name="Order"),
                ),
                (
                    "employee_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Employee self-evaluation score",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Employee score",
                    ),
                ),
                (
                    "manager_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Manager evaluation score",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Manager score",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, help_text="Additional notes", verbose_name="Note"),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        help_text="Parent assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payroll.employeekpiassessment",
                        verbose_name="Assessment",
                    ),
                ),
                (
                    "criterion_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original criterion (can be NULL if deleted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payroll.kpicriterion",
                        verbose_name="Criterion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee KPI Item",
                "verbose_name_plural": "Employee KPI Items",
                "db_table": "payroll_employee_kpi_item",
                "ordering": ["-evaluation_type", "order"],
            },
        ),
        migrations.CreateModel(
            name="PenaltyTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "employee_code",
                    models.CharField(max_length=50, verbose_name="Employee Code"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=200, verbose_name="Employee Name"),
                ),
                (
                    "violation_count",
                    models.PositiveIntegerField(default=1, verbose_name="Violation Count"),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("UNDER_10_MINUTES", "Violation under 10 minutes"),
                            ("OVER_10_MINUTES", "Violation over 10 minutes"),
                            ("ABSENT_WITHOUT_REASON", "Absent without reason"),
                            ("UNIFORM_ERROR", "Uniform error"),
                            ("OTHER", "Other violation"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                        verbose_name="Violation Type",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Amount")),
                ("month", models.DateField(db_index=True, verbose_name="Month")),
                (
                    "status",
                    models.CharField(
                        choices=[("PAID", "Paid"), ("UNPAID", "Unpaid")],
                        db_index=True,
                        default="UNPAID",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "note",
                    libs.models.fields.SafeTextField(blank=True, max_length=500, verbose_name="Note"),
                ),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="penalty_tickets",
                        to="files.filemodel",
                        verbose_name="Attachments",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="penalty_tickets_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penalty_tickets",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="penalty_tickets_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penalty Ticket",
                "verbose_name_plural": "Penalty Tickets",
                "db_table": "payroll_penalty_ticket",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecoveryVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Voucher Code"),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[("RECOVERY", "Recovery"), ("BACK_PAY", "Back Pay")],
                        max_length=20,
                        verbose_name="Voucher Type",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(max_length=50, verbose_name="Employee Code"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=250, verbose_name="Employee Name"),
                ),
                ("amount", models.IntegerField(verbose_name="Amount (VND)")),
                ("month", models.DateField(verbose_name="Month")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_CALCULATED", "Not Calculated"),
                            ("CALCULATED", "Calculated"),
                        ],
                        default="NOT_CALCULATED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "note",
                    libs.models.fields.SafeTextField(blank=True, max_length=500, verbose_name="Note"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recovery_vouchers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_vouchers",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_recovery_vouchers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recovery Voucher",
                "verbose_name_plural": "Recovery Vouchers",
                "db_table": "payroll_recovery_voucher",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SalaryPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code in format SP-YYYYMM",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        db_index=True,
                        help_text="First day of the salary month",
                        unique=True,
                        verbose_name="Month",
                    ),
                ),
                (
                    "salary_config_snapshot",
                    models.JSONField(
                        help_text="Snapshot of salary configuration for this period",
                        verbose_name="Salary Config Snapshot",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ONGOING", "Ongoing"), ("COMPLETED", "Completed")],
                        db_index=True,
                        default="ONGOING",
                        help_text="Current status of the period",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "standard_working_days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total working days in the month",
                        max_digits=5,
                        verbose_name="Standard Working Days",
                    ),
                ),
                (
                    "total_employees",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of employees with payroll slips in this period",
                        verbose_name="Total Employees",
                    ),
                ),
                (
                    "proposal_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Deadline for submitting payroll-related proposals (default: 2nd of next month)",
                        null=True,
                        verbose_name="Proposal Deadline",
                    ),
                ),
                (
                    "kpi_assessment_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Deadline for KPI assessments (default: 5th of next month)",
                        null=True,
                        verbose_name="KPI Assessment Deadline",
                    ),
                ),
                (
                    "employees_need_recovery",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of employees with recovery vouchers",
                        verbose_name="Employees Need Recovery",
                    ),
                ),
                (
                    "employees_with_penalties",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of employees with penalty tickets",
                        verbose_name="Employees With Penalties",
                    ),
                ),
                (
                    "employees_paid_penalties",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of employees who paid penalties",
                        verbose_name="Employees Paid Penalties",
                    ),
                ),
                (
                    "employees_with_travel",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of employees with travel expenses",
                        verbose_name="Employees With Travel",
                    ),
                ),
                (
                    "employees_need_email",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of employees needing payroll email",
                        verbose_name="Employees Need Email",
                    ),
                ),
                (
                    "pending_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of payroll slips in PENDING status",
                        verbose_name="Pending Count",
                    ),
                ),
                (
                    "ready_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of payroll slips in READY status",
                        verbose_name="Ready Count",
                    ),
                ),
                (
                    "hold_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of payroll slips in HOLD status",
                        verbose_name="Hold Count",
                    ),
                ),
                (
                    "delivered_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of payroll slips in DELIVERED status",
                        verbose_name="Delivered Count",
                    ),
                ),
                (
                    "total_gross_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Sum of gross income from all payroll slips",
                        max_digits=20,
                        verbose_name="Total Gross Income",
                    ),
                ),
                (
                    "total_net_salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Sum of net salary from all payroll slips",
                        max_digits=20,
                        verbose_name="Total Net Salary",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when period was completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who completed the period",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_salary_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completed By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_salary_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_salary_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Period",
                "verbose_name_plural": "Salary Periods",
                "db_table": "payroll_salary_period",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="PayrollSlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "employee_code",
                    models.CharField(max_length=50, verbose_name="Employee Code"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=250, verbose_name="Employee Name"),
                ),
                (
                    "employee_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Employee Email",
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="Tax Code"),
                ),
                (
                    "department_name",
                    models.CharField(max_length=250, verbose_name="Department Name"),
                ),
                (
                    "position_name",
                    models.CharField(max_length=250, verbose_name="Position Name"),
                ),
                (
                    "employment_status",
                    models.CharField(max_length=20, verbose_name="Employment Status"),
                ),
                (
                    "has_unpaid_penalty",
                    models.BooleanField(
                        default=False,
                        help_text="Flag if employee has unpaid penalty tickets",
                        verbose_name="Has Unpaid Penalty",
                    ),
                ),
                (
                    "unpaid_penalty_count",
                    models.IntegerField(
                        default=0,
                        help_text="Count of unpaid penalty tickets",
                        verbose_name="Unpaid Penalty Count",
                    ),
                ),
                (
                    "contract_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Contract ID"),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Base Salary",
                    ),
                ),
                (
                    "kpi_salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="KPI Salary",
                    ),
                ),
                (
                    "lunch_allowance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Lunch Allowance",
                    ),
                ),
                (
                    "phone_allowance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Phone Allowance",
                    ),
                ),
                (
                    "other_allowance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Allowance",
                    ),
                ),
                (
                    "kpi_grade",
                    models.CharField(default="C", max_length=10, verbose_name="KPI Grade"),
                ),
                (
                    "kpi_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=5,
                        verbose_name="KPI Percentage",
                    ),
                ),
                (
                    "kpi_bonus",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="KPI Bonus",
                    ),
                ),
                (
                    "sales_revenue",
                    models.BigIntegerField(default=0, verbose_name="Sales Revenue"),
                ),
                (
                    "sales_transaction_count",
                    models.IntegerField(default=0, verbose_name="Sales Transaction Count"),
                ),
                (
                    "business_grade",
                    models.CharField(default="M0", max_length=10, verbose_name="Business Grade"),
                ),
                (
                    "business_progressive_salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Business Progressive Salary",
                    ),
                ),
                (
                    "standard_working_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Standard Working Days",
                    ),
                ),
                (
                    "total_working_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Total Working Days",
                    ),
                ),
                (
                    "official_working_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Official Working Days",
                    ),
                ),
                (
                    "probation_working_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Probation Working Days",
                    ),
                ),
                (
                    "tc1_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="TC1 Overtime Hours (Weekday & Sat)",
                    ),
                ),
                (
                    "tc2_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="TC2 Overtime Hours (Sunday)",
                    ),
                ),
                (
                    "tc3_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="TC3 Overtime Hours (Holiday)",
                    ),
                ),
                (
                    "total_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Total Overtime Hours",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=20,
                        verbose_name="Hourly Rate",
                    ),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Overtime Pay",
                    ),
                ),
                (
                    "total_position_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Position Income",
                    ),
                ),
                (
                    "actual_working_days_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Actual Working Days Income",
                    ),
                ),
                (
                    "taxable_overtime_salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Taxable Overtime Salary",
                    ),
                ),
                (
                    "overtime_progress_allowance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Overtime Progress Allowance",
                    ),
                ),
                (
                    "non_taxable_overtime_salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Non-Taxable Overtime Salary",
                    ),
                ),
                (
                    "taxable_travel_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Taxable Travel Expense",
                    ),
                ),
                (
                    "non_taxable_travel_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Non-Taxable Travel Expense",
                    ),
                ),
                (
                    "total_travel_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Travel Expense",
                    ),
                ),
                (
                    "gross_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Gross Income",
                    ),
                ),
                (
                    "taxable_income_base",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Taxable Income Base",
                    ),
                ),
                (
                    "social_insurance_base",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Social Insurance Base",
                    ),
                ),
                (
                    "employee_social_insurance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Employee Social Insurance",
                    ),
                ),
                (
                    "employee_health_insurance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Employee Health Insurance",
                    ),
                ),
                (
                    "employee_unemployment_insurance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Employee Unemployment Insurance",
                    ),
                ),
                (
                    "employee_union_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Employee Union Fee",
                    ),
                ),
                (
                    "employer_social_insurance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Employer Social Insurance",
                    ),
                ),
                (
                    "employer_health_insurance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Employer Health Insurance",
                    ),
                ),
                (
                    "employer_unemployment_insurance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Employer Unemployment Insurance",
                    ),
                ),
                (
                    "employer_union_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Employer Union Fee",
                    ),
                ),
                (
                    "employer_accident_insurance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Employer Accident Insurance",
                    ),
                ),
                (
                    "personal_deduction",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Personal Deduction",
                    ),
                ),
                (
                    "dependent_count",
                    models.IntegerField(default=0, verbose_name="Dependent Count"),
                ),
                (
                    "dependent_deduction",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Dependent Deduction",
                    ),
                ),
                (
                    "taxable_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Taxable Income",
                    ),
                ),
                (
                    "personal_income_tax",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Personal Income Tax",
                    ),
                ),
                (
                    "back_pay_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Back Pay Amount",
                    ),
                ),
                (
                    "recovery_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Recovery Amount",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Net Salary",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("HOLD", "Hold"),
                            ("DELIVERED", "Delivered"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_note",
                    models.TextField(
                        blank=True,
                        help_text="Reason for PENDING or HOLD status",
                        verbose_name="Status Note",
                    ),
                ),
                (
                    "need_resend_email",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Flag if email needs to be resent",
                        verbose_name="Need Resend Email",
                    ),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Email Sent At"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Delivered At"),
                ),
                (
                    "calculation_log",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed breakdown of calculation",
                        verbose_name="Calculation Log",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Calculated At",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payroll_slips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivered_payroll_slips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delivered By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_slips",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_payroll_slips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "salary_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_slips",
                        to="payroll.salaryperiod",
                        verbose_name="Salary Period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Slip",
                "verbose_name_plural": "Payroll Slips",
                "db_table": "payroll_payroll_slip",
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "kpi_target",
                    models.BigIntegerField(
                        default=50000000,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="KPI Target",
                    ),
                ),
                (
                    "revenue",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Revenue",
                    ),
                ),
                (
                    "transaction_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Transaction count",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        db_index=True,
                        help_text="First day of the revenue month",
                        verbose_name="Month",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_CALCULATED", "Not calculated"),
                            ("CALCULATED", "Calculated"),
                        ],
                        db_index=True,
                        default="NOT_CALCULATED",
                        editable=False,
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_revenues_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_revenues",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_revenues_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Revenue",
                "verbose_name_plural": "Sales Revenues",
                "db_table": "payroll_sales_revenue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesRevenueReportFlatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "report_date",
                    models.DateField(db_index=True, verbose_name="Report date"),
                ),
                (
                    "need_refresh",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this report needs to be recalculated by batch task",
                        verbose_name="Needs refresh",
                    ),
                ),
                (
                    "month_key",
                    models.CharField(
                        help_text="Month in MM/YYYY format",
                        max_length=10,
                        verbose_name="Month key",
                    ),
                ),
                (
                    "total_transactions",
                    models.IntegerField(default=0, verbose_name="Total transactions"),
                ),
                (
                    "total_revenue",
                    models.BigIntegerField(default=0, verbose_name="Total revenue"),
                ),
                (
                    "total_sales_employees",
                    models.IntegerField(
                        default=0,
                        help_text="Active sales employees at end of month",
                        verbose_name="Total sales employees",
                    ),
                ),
                (
                    "employees_with_revenue",
                    models.IntegerField(
                        default=0,
                        help_text="Count of employees who generated revenue in the month",
                        verbose_name="Employees with revenue",
                    ),
                ),
                (
                    "target_per_employee",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000000.0,
                        help_text="Fixed target per employee (50,000,000 VND)",
                        max_digits=15,
                        verbose_name="Target per employee",
                    ),
                ),
                (
                    "total_kpi_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total sales employees * Target per employee",
                        max_digits=20,
                        verbose_name="Total KPI target",
                    ),
                ),
                (
                    "revenue_vs_target_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue / Total target * 100",
                        max_digits=7,
                        verbose_name="Revenue vs target (%)",
                    ),
                ),
                (
                    "employee_with_revenue_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Employees with revenue / Total sales employees * 100",
                        max_digits=7,
                        verbose_name="Employee with revenue (%)",
                    ),
                ),
                (
                    "avg_revenue_per_employee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue / Total sales employees",
                        max_digits=20,
                        verbose_name="Average revenue per employee",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Revenue Report",
                "verbose_name_plural": "Sales Revenue Reports",
                "db_table": "payroll_sales_revenue_report",
            },
        ),
        migrations.CreateModel(
            name="TravelExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Expense name")),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("TAXABLE", "Taxable"),
                            ("NON_TAXABLE", "Non-taxable"),
                        ],
                        max_length=20,
                        verbose_name="Expense type",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        db_index=True,
                        help_text="First day of the expense month",
                        verbose_name="Month",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_CALCULATED", "Not calculated"),
                            ("CALCULATED", "Calculated"),
                        ],
                        db_index=True,
                        default="NOT_CALCULATED",
                        editable=False,
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "note",
                    libs.models.fields.SafeTextField(blank=True, default="", max_length=500, verbose_name="Note"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_expenses_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="travel_expenses",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_expenses_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Travel Expense",
                "verbose_name_plural": "Travel Expenses",
                "db_table": "payroll_travel_expense",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="kpiassessmentperiod",
            index=models.Index(fields=["month"], name="payroll_kpi_month_fab165_idx"),
        ),
        migrations.AddIndex(
            model_name="kpiassessmentperiod",
            index=models.Index(fields=["finalized"], name="payroll_kpi_finaliz_41594e_idx"),
        ),
        migrations.AddIndex(
            model_name="employeekpiassessment",
            index=models.Index(fields=["employee", "period"], name="payroll_emp_employe_3f0ec9_idx"),
        ),
        migrations.AddIndex(
            model_name="employeekpiassessment",
            index=models.Index(fields=["period"], name="payroll_emp_period__bd86bb_idx"),
        ),
        migrations.AddIndex(
            model_name="employeekpiassessment",
            index=models.Index(fields=["finalized"], name="payroll_emp_finaliz_4434ed_idx"),
        ),
        migrations.AddIndex(
            model_name="employeekpiassessment",
            index=models.Index(fields=["status"], name="payroll_emp_status_969e1d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="employeekpiassessment",
            unique_together={("employee", "period")},
        ),
        migrations.AddIndex(
            model_name="departmentkpiassessment",
            index=models.Index(fields=["department", "period"], name="payroll_dep_departm_ca8754_idx"),
        ),
        migrations.AddIndex(
            model_name="departmentkpiassessment",
            index=models.Index(fields=["period"], name="payroll_dep_period__7e8c25_idx"),
        ),
        migrations.AddIndex(
            model_name="departmentkpiassessment",
            index=models.Index(fields=["finalized"], name="payroll_dep_finaliz_adf75a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="departmentkpiassessment",
            unique_together={("department", "period")},
        ),
        migrations.AddIndex(
            model_name="kpicriterion",
            index=models.Index(
                fields=["target", "evaluation_type"],
                name="payroll_kpi_target_c4af82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kpicriterion",
            index=models.Index(fields=["active"], name="payroll_kpi_active_c2e4dc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="kpicriterion",
            unique_together={("target", "evaluation_type", "criterion", "sub_criterion")},
        ),
        migrations.AddIndex(
            model_name="employeekpiitem",
            index=models.Index(fields=["assessment", "order"], name="payroll_emp_assessm_3e4bf8_idx"),
        ),
        migrations.AddIndex(
            model_name="penaltyticket",
            index=models.Index(fields=["month", "employee"], name="pen_ticket_month_emp_idx"),
        ),
        migrations.AddIndex(
            model_name="penaltyticket",
            index=models.Index(fields=["status"], name="pen_ticket_status_idx"),
        ),
        migrations.AddIndex(
            model_name="penaltyticket",
            index=models.Index(fields=["month"], name="payroll_pen_month_b4f6e7_idx"),
        ),
        migrations.AddIndex(
            model_name="penaltyticket",
            index=models.Index(fields=["-created_at"], name="payroll_pen_created_idx"),
        ),
        migrations.AddIndex(
            model_name="recoveryvoucher",
            index=models.Index(fields=["month", "employee"], name="payroll_rec_month_7f4ba3_idx"),
        ),
        migrations.AddIndex(
            model_name="recoveryvoucher",
            index=models.Index(fields=["status"], name="payroll_rec_status_fbfa30_idx"),
        ),
        migrations.AddIndex(
            model_name="recoveryvoucher",
            index=models.Index(fields=["-updated_at"], name="payroll_rec_updated_c4a29a_idx"),
        ),
        migrations.AddIndex(
            model_name="salaryperiod",
            index=models.Index(fields=["month"], name="salary_period_month_idx"),
        ),
        migrations.AddIndex(
            model_name="salaryperiod",
            index=models.Index(fields=["status"], name="salary_period_status_idx"),
        ),
        migrations.AddIndex(
            model_name="salaryperiod",
            index=models.Index(fields=["-created_at"], name="salary_period_created_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollslip",
            index=models.Index(
                fields=["salary_period", "status"],
                name="payroll_slip_period_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollslip",
            index=models.Index(fields=["employee"], name="payroll_slip_employee_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollslip",
            index=models.Index(fields=["status"], name="payroll_slip_status_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollslip",
            index=models.Index(fields=["need_resend_email"], name="payroll_slip_resend_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollslip",
            index=models.Index(fields=["-calculated_at"], name="payroll_slip_calculated_idx"),
        ),
        migrations.AddConstraint(
            model_name="payrollslip",
            constraint=models.UniqueConstraint(
                fields=("salary_period", "employee"),
                name="unique_salary_period_employee",
            ),
        ),
        migrations.AddIndex(
            model_name="salesrevenue",
            index=models.Index(fields=["month"], name="payroll_sal_month_0d5769_idx"),
        ),
        migrations.AddIndex(
            model_name="salesrevenue",
            index=models.Index(fields=["status"], name="payroll_sal_status_3e5dae_idx"),
        ),
        migrations.AddIndex(
            model_name="salesrevenue",
            index=models.Index(fields=["-created_at"], name="payroll_sal_created_ade7ab_idx"),
        ),
        migrations.AddIndex(
            model_name="salesrevenue",
            index=models.Index(fields=["employee", "month"], name="payroll_sal_employe_efb999_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="salesrevenue",
            unique_together={("employee", "month")},
        ),
        migrations.AddIndex(
            model_name="salesrevenuereportflatmodel",
            index=models.Index(fields=["report_date"], name="payroll_sal_report__39e89b_idx"),
        ),
        migrations.AddIndex(
            model_name="salesrevenuereportflatmodel",
            index=models.Index(
                fields=["branch", "block", "department"],
                name="payroll_sal_branch__6b3124_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesrevenuereportflatmodel",
            index=models.Index(fields=["month_key"], name="payroll_sal_month_k_c3a1ee_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="salesrevenuereportflatmodel",
            unique_together={("report_date", "branch", "block", "department")},
        ),
        migrations.AddIndex(
            model_name="travelexpense",
            index=models.Index(fields=["month", "expense_type"], name="payroll_tra_month_48ae3a_idx"),
        ),
        migrations.AddIndex(
            model_name="travelexpense",
            index=models.Index(fields=["status"], name="payroll_tra_status_201d11_idx"),
        ),
        migrations.AddIndex(
            model_name="travelexpense",
            index=models.Index(fields=["-created_at"], name="payroll_tra_created_230bf1_idx"),
        ),
    ]
