# Generated by Django 5.2.6 on 2025-12-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalaryConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("config", models.JSONField(verbose_name="Salary Configuration")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="Version")),
            ],
            options={
                "verbose_name": "Salary Configuration",
                "verbose_name_plural": "Salary Configurations",
                "db_table": "payroll_salary_config",
                "ordering": ["-version"],
            },
        ),
    ]
