# Generated by Django 5.2.6 on 2026-01-08 09:58

from django.db import migrations

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentkpiassessment",
            name="note",
            field=libs.models.fields.SafeTextField(
                blank=True, help_text="Additional notes", max_length=250, verbose_name="Note"
            ),
        ),
    ]
