# Generated by Django 5.2.9 on 2025-12-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(verbose_name='KPI Configuration')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'KPI Configuration',
                'verbose_name_plural': 'KPI Configurations',
                'db_table': 'payroll_kpi_config',
                'ordering': ['-version'],
            },
        ),
    ]
