# Generated by Django 5.2.6 on 2025-12-11 07:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_kpiconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(help_text="Target group or role (e.g., 'sales', 'backoffice')", max_length=200, verbose_name='Target')),
                ('evaluation_type', models.CharField(help_text="Type of evaluation (e.g., 'job performance', 'discipline')", max_length=200, verbose_name='Evaluation type')),
                ('name', models.CharField(help_text='Name of the KPI criterion', max_length=255, verbose_name='Criterion name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the criterion', verbose_name='Description')),
                ('component_total_score', models.DecimalField(decimal_places=2, help_text='Maximum percentage score (0-100)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Component total score')),
                ('ordering', models.PositiveSmallIntegerField(default=0, help_text='Order for sorting and display', verbose_name='Display order')),
                ('active', models.BooleanField(default=True, help_text='Whether this criterion is active', verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this criterion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_criteria_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this criterion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_criteria_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'KPI Criterion',
                'verbose_name_plural': 'KPI Criteria',
                'db_table': 'payroll_kpi_criterion',
                'ordering': ['target', 'evaluation_type', 'ordering', 'name'],
                'indexes': [models.Index(fields=['target', 'evaluation_type'], name='payroll_kpi_target_c4af82_idx'), models.Index(fields=['active'], name='payroll_kpi_active_c2e4dc_idx')],
                'unique_together': {('target', 'evaluation_type', 'name')},
            },
        ),
    ]
