# Generated by Django 5.2.6 on 2026-01-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0002_alter_departmentkpiassessment_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentkpiassessment",
            name="manager_grade_distribution",
            field=models.JSONField(
                default=dict,
                help_text="Number of employees by manager grade: {'A': 2, 'B': 5, 'C': 10, 'D': 1}",
                verbose_name="Manager grade distribution",
            ),
        ),
    ]
