# Generated by Django 5.2.6 on 2025-12-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0003_kpicriterion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpicriterion",
            name="target",
            field=models.CharField(
                choices=[("sales", "Sales"), ("backoffice", "Backoffice")],
                help_text="Target group or role",
                max_length=200,
                verbose_name="Target",
            ),
        ),
    ]
