# Generated by Django 5.2.6 on 2025-12-16 06:33

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0008_timesheetentry_day_type_timesheetentry_working_days_and_more"),
        ("payroll", "0004_kpicriterion_model_enhancement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentKPIAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.CharField(help_text="Department's grade (A/B/C/D)", max_length=10, verbose_name="Grade"),
                ),
                (
                    "default_grade",
                    models.CharField(
                        default="C",
                        help_text="Default grade when auto-created",
                        max_length=10,
                        verbose_name="Default grade",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when grade was assigned",
                        null=True,
                        verbose_name="Assigned at",
                    ),
                ),
                (
                    "auto_assigned_to_employees",
                    models.BooleanField(
                        default=False,
                        help_text="Whether grades have been auto-assigned to employees",
                        verbose_name="Auto-assigned to employees",
                    ),
                ),
                (
                    "finalized",
                    models.BooleanField(
                        default=False, help_text="Whether assessment is locked", verbose_name="Finalized"
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Additional notes", verbose_name="Note")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who assigned the grade",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_kpi_assessments_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this assessment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_kpi_assessments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department being assessed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpi_assessments",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this assessment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_kpi_assessments_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department KPI Assessment",
                "verbose_name_plural": "Department KPI Assessments",
                "db_table": "payroll_department_kpi_assessment",
                "ordering": ["-period__month", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPIAssessmentPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "month",
                    models.DateField(
                        help_text="First day of the assessment month", unique=True, verbose_name="Assessment month"
                    ),
                ),
                (
                    "kpi_config_snapshot",
                    models.JSONField(
                        help_text="Snapshot of KPIConfig used for this assessment period",
                        verbose_name="KPI config snapshot",
                    ),
                ),
                (
                    "finalized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the entire assessment period is locked (no further edits)",
                        verbose_name="Finalized",
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Additional notes or comments", verbose_name="Note")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this period",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_periods_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this period",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_periods_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Assessment Period",
                "verbose_name_plural": "KPI Assessment Periods",
                "db_table": "payroll_kpi_assessment_period",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeKPIAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_possible_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all component_total_score from items",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Total possible score",
                    ),
                ),
                (
                    "total_manager_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sum of all manager scores from items",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Total manager score",
                    ),
                ),
                (
                    "grade_manager",
                    models.CharField(
                        blank=True,
                        help_text="Final grade used for payroll (A/B/C/D)",
                        max_length=10,
                        null=True,
                        verbose_name="Manager grade",
                    ),
                ),
                (
                    "grade_manager_overridden",
                    models.CharField(
                        blank=True,
                        help_text="Manager's explicit grade override",
                        max_length=10,
                        null=True,
                        verbose_name="Manager grade override",
                    ),
                ),
                (
                    "plan_tasks",
                    libs.models.fields.SafeTextField(
                        blank=True, help_text="Planned tasks for the assessment period", verbose_name="Plan tasks"
                    ),
                ),
                (
                    "extra_tasks",
                    libs.models.fields.SafeTextField(
                        blank=True, help_text="Extra tasks handled during the period", verbose_name="Extra tasks"
                    ),
                ),
                (
                    "proposal",
                    libs.models.fields.SafeTextField(
                        blank=True, help_text="Employee's proposals or suggestions", verbose_name="Proposal"
                    ),
                ),
                (
                    "grade_hrm",
                    models.CharField(
                        blank=True,
                        help_text="HRM department's final grade assessment",
                        max_length=10,
                        null=True,
                        verbose_name="HRM grade",
                    ),
                ),
                (
                    "finalized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether assessment is locked (no further edits)",
                        verbose_name="Finalized",
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Additional notes or comments", verbose_name="Note")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this assessment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_assessments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "department_assignment_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to DepartmentKPIAssessment if grade assigned by dept",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_employee_assessments",
                        to="payroll.departmentkpiassessment",
                        verbose_name="Department assignment source",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee being assessed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpi_assessments",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this assessment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_assessments_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="KPI assessment period this assessment belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assessments",
                        to="payroll.kpiassessmentperiod",
                        verbose_name="Assessment period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee KPI Assessment",
                "verbose_name_plural": "Employee KPI Assessments",
                "db_table": "payroll_employee_kpi_assessment",
                "ordering": ["-period__month", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="departmentkpiassessment",
            name="period",
            field=models.ForeignKey(
                help_text="KPI assessment period this assessment belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="department_assessments",
                to="payroll.kpiassessmentperiod",
                verbose_name="Assessment period",
            ),
        ),
        migrations.CreateModel(
            name="DepartmentAssignmentLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(help_text="Type of action performed", max_length=100, verbose_name="Action"),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, help_text="JSON data containing action details", null=True, verbose_name="Payload"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action occurred", verbose_name="Timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_assignment_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "department_assessment",
                    models.ForeignKey(
                        help_text="Related department assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_logs",
                        to="payroll.departmentkpiassessment",
                        verbose_name="Department assessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Assignment Log",
                "verbose_name_plural": "Department Assignment Logs",
                "db_table": "payroll_department_assignment_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["department_assessment", "-timestamp"], name="payroll_dep_departm_009dac_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeKPIItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "criterion",
                    models.CharField(help_text="Snapshot of criterion name", max_length=255, verbose_name="Criterion"),
                ),
                (
                    "sub_criterion",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of sub-criterion",
                        max_length=255,
                        null=True,
                        verbose_name="Sub-criterion",
                    ),
                ),
                (
                    "evaluation_type",
                    models.CharField(
                        help_text="Snapshot of evaluation type", max_length=50, verbose_name="Evaluation type"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Snapshot of criterion description", verbose_name="Description"
                    ),
                ),
                (
                    "component_total_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of maximum score",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Component total score",
                    ),
                ),
                (
                    "group_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Snapshot of group number for UI display",
                        null=True,
                        verbose_name="Group number",
                    ),
                ),
                ("ordering", models.IntegerField(help_text="Display order", verbose_name="Order")),
                (
                    "employee_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Employee self-evaluation score",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Employee score",
                    ),
                ),
                (
                    "manager_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Manager evaluation score",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Manager score",
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Additional notes", verbose_name="Note")),
                (
                    "assessment",
                    models.ForeignKey(
                        help_text="Parent assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payroll.employeekpiassessment",
                        verbose_name="Assessment",
                    ),
                ),
                (
                    "criterion_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original criterion (can be NULL if deleted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payroll.kpicriterion",
                        verbose_name="Criterion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee KPI Item",
                "verbose_name_plural": "Employee KPI Items",
                "db_table": "payroll_employee_kpi_item",
                "ordering": ["ordering"],
                "indexes": [models.Index(fields=["assessment", "ordering"], name="payroll_emp_assessm_11cfe3_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="kpiassessmentperiod",
            index=models.Index(fields=["month"], name="payroll_kpi_month_fab165_idx"),
        ),
        migrations.AddIndex(
            model_name="kpiassessmentperiod",
            index=models.Index(fields=["finalized"], name="payroll_kpi_finaliz_41594e_idx"),
        ),
        migrations.AddIndex(
            model_name="employeekpiassessment",
            index=models.Index(fields=["employee", "period"], name="payroll_emp_employe_3f0ec9_idx"),
        ),
        migrations.AddIndex(
            model_name="employeekpiassessment",
            index=models.Index(fields=["period"], name="payroll_emp_period__bd86bb_idx"),
        ),
        migrations.AddIndex(
            model_name="employeekpiassessment",
            index=models.Index(fields=["finalized"], name="payroll_emp_finaliz_4434ed_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="employeekpiassessment",
            unique_together={("employee", "period")},
        ),
        migrations.AddIndex(
            model_name="departmentkpiassessment",
            index=models.Index(fields=["department", "period"], name="payroll_dep_departm_ca8754_idx"),
        ),
        migrations.AddIndex(
            model_name="departmentkpiassessment",
            index=models.Index(fields=["period"], name="payroll_dep_period__7e8c25_idx"),
        ),
        migrations.AddIndex(
            model_name="departmentkpiassessment",
            index=models.Index(fields=["finalized"], name="payroll_dep_finaliz_adf75a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="departmentkpiassessment",
            unique_together={("department", "period")},
        ),
    ]
