# Generated by Django 5.2.6 on 2025-12-16 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0005_departmentkpiassessment_kpiassessmentperiod_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kpicriterion",
            unique_together={("target", "evaluation_type", "criterion", "sub_criterion")},
        ),
    ]
