# Generated by Django 5.2.6 on 2025-12-17 06:36

import django.db.models.deletion
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0008_timesheetentry_day_type_timesheetentry_working_days_and_more"),
        ("payroll", "0005_alter_kpicriterion_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeekpiassessment",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager responsible for assessing this employee (from department leader)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_kpi_assessments",
                to="hrm.employee",
                verbose_name="Manager",
            ),
        ),
        migrations.AddField(
            model_name="employeekpiassessment",
            name="manager_assessment",
            field=libs.models.fields.SafeTextField(
                blank=True, help_text="Manager's assessment comments and feedback", verbose_name="Manager assessment"
            ),
        ),
    ]
