# Generated by Django 5.2.6 on 2025-12-16 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0006_alter_kpicriterion_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departmentkpiassessment",
            name="auto_assigned_to_employees",
        ),
        migrations.DeleteModel(
            name="DepartmentAssignmentLog",
        ),
    ]
