# Generated by Django 5.2.6 on 2025-12-18 04:34

from django.db import migrations, models


def populate_target_from_criterion(apps, schema_editor):
    """Populate target field from related criterion_id."""
    EmployeeKPIItem = apps.get_model("payroll", "EmployeeKPIItem")

    for item in EmployeeKPIItem.objects.select_related("criterion_id").all():
        if item.criterion_id:
            item.target = item.criterion_id.target
            item.save(update_fields=["target"])


def reverse_populate_target(apps, schema_editor):
    """No need to reverse - target will be removed."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0006_add_manager_and_manager_assessment_to_employee_kpi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeekpiitem",
            options={
                "ordering": ["-evaluation_type", "order"],
                "verbose_name": "Employee KPI Item",
                "verbose_name_plural": "Employee KPI Items",
            },
        ),
        migrations.RemoveIndex(
            model_name="employeekpiitem",
            name="payroll_emp_assessm_11cfe3_idx",
        ),
        migrations.RenameField(
            model_name="employeekpiitem",
            old_name="ordering",
            new_name="order",
        ),
        migrations.AddField(
            model_name="employeekpiitem",
            name="target",
            field=models.CharField(
                choices=[("sales", "Sales"), ("backoffice", "Backoffice")],
                default="sales",
                help_text="Snapshot of target group or role",
                max_length=200,
                verbose_name="Target",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_target_from_criterion, reverse_populate_target),
        migrations.AlterField(
            model_name="employeekpiitem",
            name="evaluation_type",
            field=models.CharField(
                choices=[("work_performance", "Work Performance"), ("discipline", "Discipline")],
                help_text="Snapshot of evaluation type",
                max_length=50,
                verbose_name="Evaluation type",
            ),
        ),
        migrations.AddIndex(
            model_name="employeekpiitem",
            index=models.Index(fields=["assessment", "order"], name="payroll_emp_assessm_3e4bf8_idx"),
        ),
    ]
