# Generated by Django 5.2.6 on 2026-01-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0006_add_family_deduction_and_non_taxable_allowance"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollslip",
            name="travel_expense_by_working_days",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=20, verbose_name="Travel Expense By Working Days"
            ),
        ),
        migrations.AlterField(
            model_name="travelexpense",
            name="expense_type",
            field=models.CharField(
                choices=[
                    ("TAXABLE", "Taxable"),
                    ("NON_TAXABLE", "Non-taxable"),
                    ("BY_WORKING_DAYS", "By working days"),
                ],
                max_length=20,
                verbose_name="Expense type",
            ),
        ),
    ]
