# Generated by Django 5.2.6 on 2026-01-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0007_update_travel_expense_and_payroll_slip"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollslip",
            name="employee_official_date",
            field=models.DateField(
                blank=True,
                help_text="Date when employee became OFFICIAL, used for insurance calculation",
                null=True,
                verbose_name="Employee Official Date",
            ),
        ),
    ]
