# Generated by Django 5.2.6 on 2025-12-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0007_rename_ordering_to_order_and_add_target_with_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentkpiassessment",
            name="is_finished",
            field=models.BooleanField(
                default=False,
                verbose_name="Is finished",
                help_text="Whether all employees in this department have been graded",
            ),
        ),
    ]
