# Generated by Django 5.2.6 on 2025-12-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0008_add_is_finished_to_department_kpi_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentkpiassessment",
            name="grade_distribution",
            field=models.JSONField(
                default=dict,
                help_text="Number of employees by grade: {'A': 2, 'B': 5, 'C': 10, 'D': 1}",
                verbose_name="Grade distribution",
            ),
        ),
    ]
