# Generated by Django 5.2.6 on 2026-01-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0008_add_employee_official_date_to_payroll_slip"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollslip",
            name="has_social_insurance",
            field=models.BooleanField(
                default=True, help_text="Snapshot from contract", verbose_name="Has Social Insurance"
            ),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="is_sale_employee",
            field=models.BooleanField(
                default=False,
                help_text="True if Department.function == BUSINESS, False otherwise",
                verbose_name="Is Sale Employee",
            ),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="net_percentage",
            field=models.IntegerField(blank=True, null=True, verbose_name="Net Percentage"),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="tax_calculation_method",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Tax Calculation Method"),
        ),
    ]
