# Generated by Django 5.2.6 on 2026-01-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0009_add_payroll_slip_snapshot_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollslip",
            name="position_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Snapshot of position code",
                max_length=50,
                verbose_name="Position Code",
            ),
        ),
    ]
