# Generated by Django 5.2.6 on 2025-12-23 04:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0019_alter_attendancedailyreport_options_and_more"),
        ("payroll", "0009_add_grade_distribution_to_department_assessment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Expense name")),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("TAXABLE", "Taxable"),
                            ("NON_TAXABLE", "Non-taxable"),
                        ],
                        max_length=20,
                        verbose_name="Expense type",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        db_index=True,
                        help_text="First day of the expense month",
                        verbose_name="Month",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_CALCULATED", "Not calculated"),
                            ("CALCULATED", "Calculated"),
                        ],
                        db_index=True,
                        default="NOT_CALCULATED",
                        editable=False,
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "note",
                    libs.models.fields.SafeTextField(blank=True, default="", max_length=500, verbose_name="Note"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_expenses_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="travel_expenses",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_expenses_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Travel Expense",
                "verbose_name_plural": "Travel Expenses",
                "db_table": "payroll_travel_expense",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["month", "expense_type"],
                        name="payroll_tra_month_48ae3a_idx",
                    ),
                    models.Index(fields=["status"], name="payroll_tra_status_201d11_idx"),
                    models.Index(fields=["-created_at"], name="payroll_tra_created_230bf1_idx"),
                ],
            },
        ),
    ]
