# Generated by Django 5.2.6 on 2025-12-23 06:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0020_alter_attendancedailyreport_options_and_more"),
        ("payroll", "0010_travelexpense"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRevenue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "revenue",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)], verbose_name="Revenue"
                    ),
                ),
                (
                    "transaction_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)], verbose_name="Transaction count"
                    ),
                ),
                (
                    "month",
                    models.DateField(db_index=True, help_text="First day of the revenue month", verbose_name="Month"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("NOT_CALCULATED", "Not calculated"), ("CALCULATED", "Calculated")],
                        db_index=True,
                        default="NOT_CALCULATED",
                        editable=False,
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_revenues_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_revenues",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_revenues_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Revenue",
                "verbose_name_plural": "Sales Revenues",
                "db_table": "payroll_sales_revenue",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["month"], name="payroll_sal_month_0d5769_idx"),
                    models.Index(fields=["status"], name="payroll_sal_status_3e5dae_idx"),
                    models.Index(fields=["-created_at"], name="payroll_sal_created_ade7ab_idx"),
                    models.Index(fields=["employee", "month"], name="payroll_sal_employe_efb999_idx"),
                ],
                "unique_together": {("employee", "month")},
            },
        ),
    ]
