# Generated by Django 5.2.6 on 2025-12-23 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0021_alter_attendancedailyreport_options_and_more"),
        ("payroll", "0010_travelexpense"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Voucher Code"),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[("RECOVERY", "Recovery"), ("BACK_PAY", "Back Pay")],
                        max_length=20,
                        verbose_name="Voucher Type",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(max_length=50, verbose_name="Employee Code"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=250, verbose_name="Employee Name"),
                ),
                ("amount", models.IntegerField(verbose_name="Amount (VND)")),
                ("month", models.DateField(verbose_name="Month")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_CALCULATED", "Not Calculated"),
                            ("CALCULATED", "Calculated"),
                        ],
                        default="NOT_CALCULATED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "note",
                    libs.models.fields.SafeTextField(blank=True, max_length=500, verbose_name="Note"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recovery_vouchers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_vouchers",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_recovery_vouchers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recovery Voucher",
                "verbose_name_plural": "Recovery Vouchers",
                "db_table": "payroll_recovery_voucher",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["month", "employee"],
                        name="payroll_rec_month_7f4ba3_idx",
                    ),
                    models.Index(fields=["status"], name="payroll_rec_status_fbfa30_idx"),
                    models.Index(fields=["-updated_at"], name="payroll_rec_updated_c4a29a_idx"),
                ],
            },
        ),
    ]
