# Generated by Django 5.2.6 on 2025-12-24 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0011_add_sales_revenue"),
        ("payroll", "0011_recoveryvoucher"),
    ]

    operations = []
