# Generated by Django 5.2.6 on 2026-01-16 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0011_add_is_for_leader_field"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employeekpiassessment",
            new_name="payroll_emp_is_for__16823a_idx",
            old_name="payroll_emp_is_for__idx",
        ),
    ]
