# Generated by Django 5.2.6 on 2025-12-25 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        ("hrm", "0024_alter_attendancedailyreport_options_and_more"),
        ("payroll", "0012_merge_0011_add_sales_revenue_0011_recoveryvoucher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PenaltyTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "employee_code",
                    models.CharField(max_length=50, verbose_name="Employee Code"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=200, verbose_name="Employee Name"),
                ),
                (
                    "violation_count",
                    models.PositiveIntegerField(default=1, verbose_name="Violation Count"),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("UNDER_10_MINUTES", "Violation under 10 minutes"),
                            ("OVER_10_MINUTES", "Violation over 10 minutes"),
                            ("ABSENT_WITHOUT_REASON", "Absent without reason"),
                            ("UNIFORM_ERROR", "Uniform error"),
                            ("OTHER", "Other violation"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                        verbose_name="Violation Type",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Amount")),
                ("month", models.DateField(db_index=True, verbose_name="Month")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("PAID", "Paid"), ("UNPAID", "Unpaid")],
                        db_index=True,
                        default="UNPAID",
                        max_length=15,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "payroll_status",
                    models.CharField(
                        choices=[
                            ("CALCULATED", "Calculated"),
                            ("NOT_CALCULATED", "Not Calculated"),
                        ],
                        db_index=True,
                        default="NOT_CALCULATED",
                        max_length=20,
                        verbose_name="Payroll Status",
                    ),
                ),
                (
                    "note",
                    libs.models.fields.SafeTextField(blank=True, max_length=500, verbose_name="Note"),
                ),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="penalty_tickets",
                        to="files.filemodel",
                        verbose_name="Attachments",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="penalty_tickets_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penalty_tickets",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="penalty_tickets_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penalty Ticket",
                "verbose_name_plural": "Penalty Tickets",
                "db_table": "payroll_penalty_ticket",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["month", "employee"], name="pen_ticket_month_emp_idx"),
                    models.Index(fields=["payment_status"], name="pen_ticket_pay_status_idx"),
                    models.Index(fields=["payroll_status"], name="pen_ticket_payroll_idx"),
                    models.Index(fields=["month"], name="payroll_pen_month_b4f6e7_idx"),
                    models.Index(fields=["-created_at"], name="payroll_pen_created_idx"),
                ],
            },
        ),
    ]
