# Generated by Django 5.2.6 on 2025-12-25 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        ("hrm", "0024_alter_attendancedailyreport_options_and_more"),
        ("payroll", "0013_penaltyticket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="penaltyticket",
            name="pen_ticket_pay_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="penaltyticket",
            name="pen_ticket_payroll_idx",
        ),
        migrations.RemoveField(
            model_name="penaltyticket",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="penaltyticket",
            name="payroll_status",
        ),
        migrations.AddField(
            model_name="penaltyticket",
            name="status",
            field=models.CharField(
                choices=[("PAID", "Paid"), ("UNPAID", "Unpaid")],
                db_index=True,
                default="UNPAID",
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="penaltyticket",
            index=models.Index(fields=["status"], name="pen_ticket_status_idx"),
        ),
    ]
