# Generated by Django 5.2.6 on 2025-12-25 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0024_alter_attendancedailyreport_options_and_more"),
        ("payroll", "0014_remove_penaltyticket_pen_ticket_pay_status_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employeekpiassessment",
            name="hrm_assessed",
            field=models.BooleanField(
                default=False, help_text="Whether HRM has assessed this", verbose_name="HRM assessed"
            ),
        ),
        migrations.AddField(
            model_name="employeekpiassessment",
            name="hrm_assessment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when HRM completed assessment",
                null=True,
                verbose_name="HRM assessment date",
            ),
        ),
        migrations.AddField(
            model_name="employeekpiassessment",
            name="manager_assessment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when manager completed assessment",
                null=True,
                verbose_name="Manager assessment date",
            ),
        ),
        migrations.AddField(
            model_name="employeekpiassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("waiting_manager", "Waiting for manager assessment"),
                    ("completed", "Completed"),
                ],
                default="new",
                help_text="Assessment status (system-managed)",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="employeekpiassessment",
            index=models.Index(fields=["status"], name="payroll_emp_status_969e1d_idx"),
        ),
    ]
