# Generated by Django 5.2.6 on 2025-12-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0014_remove_penaltyticket_pen_ticket_pay_status_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="penaltyticket",
            name="payment_date",
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name="Payment Date"),
        ),
    ]
