# Generated by Django 5.2.6 on 2025-12-25 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0015_add_status_and_assessment_dates_to_employee_kpi"),
        ("payroll", "0015_penaltyticket_payment_date"),
    ]

    operations = []
