# Generated by Django 5.2.6 on 2025-12-29 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0015_salaryperiod_payrollslip_and_more"),
        ("payroll", "0016_merge_20251225_1739"),
    ]

    operations = []
