# Generated by Django 5.2.6 on 2025-12-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0017_merge_20251229_0920"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryperiod",
            name="employees_need_email",
            field=models.PositiveIntegerField(
                default=0, help_text="Count of employees needing payroll email", verbose_name="Employees Need Email"
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="employees_need_recovery",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Count of employees with recovery vouchers",
                verbose_name="Employees Need Recovery",
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="employees_paid_penalties",
            field=models.PositiveIntegerField(
                default=0, help_text="Count of employees who paid penalties", verbose_name="Employees Paid Penalties"
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="employees_with_penalties",
            field=models.PositiveIntegerField(
                default=0, help_text="Count of employees with penalty tickets", verbose_name="Employees With Penalties"
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="employees_with_travel",
            field=models.PositiveIntegerField(
                default=0, help_text="Count of employees with travel expenses", verbose_name="Employees With Travel"
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="kpi_assessment_deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline for KPI assessments (default: 5th of next month)",
                null=True,
                verbose_name="KPI Assessment Deadline",
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="proposal_deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline for submitting payroll-related proposals (default: 2nd of next month)",
                null=True,
                verbose_name="Proposal Deadline",
            ),
        ),
    ]
