# Generated by Django 5.2.6 on 2025-12-30 09:12

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0017_merge_20251229_0920"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payrollslip",
            old_name="saturday_inweek_overtime_hours",
            new_name="tc1_overtime_hours",
        ),
        migrations.RenameField(
            model_name="payrollslip",
            old_name="sunday_overtime_hours",
            new_name="tc2_overtime_hours",
        ),
        migrations.RenameField(
            model_name="payrollslip",
            old_name="holiday_overtime_hours",
            new_name="tc3_overtime_hours",
        ),
        migrations.AlterField(
            model_name="payrollslip",
            name="tc1_overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="TC1 Overtime Hours (Weekday & Sat)",
            ),
        ),
        migrations.AlterField(
            model_name="payrollslip",
            name="tc2_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="TC2 Overtime Hours (Sunday)"
            ),
        ),
        migrations.AlterField(
            model_name="payrollslip",
            name="tc3_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="TC3 Overtime Hours (Holiday)"
            ),
        ),
    ]
