# Generated by Django 5.2.6 on 2025-12-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0018_salaryperiod_employees_need_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryperiod",
            name="delivered_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Count of payroll slips in DELIVERED status", verbose_name="Delivered Count"
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="hold_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Count of payroll slips in HOLD status", verbose_name="Hold Count"
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="pending_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Count of payroll slips in PENDING status", verbose_name="Pending Count"
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="ready_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Count of payroll slips in READY status", verbose_name="Ready Count"
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="total_gross_income",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Sum of gross income from all payroll slips",
                max_digits=20,
                verbose_name="Total Gross Income",
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="total_net_salary",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Sum of net salary from all payroll slips",
                max_digits=20,
                verbose_name="Total Net Salary",
            ),
        ),
    ]
