# Generated by Django 5.2.6 on 2025-12-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0019_add_aggregate_statistics_to_salary_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollslip",
            name="actual_working_days_income",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=20, verbose_name="Actual Working Days Income"
            ),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="non_taxable_overtime_salary",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=20, verbose_name="Non-Taxable Overtime Salary"
            ),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="overtime_progress_allowance",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=20, verbose_name="Overtime Progress Allowance"
            ),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="taxable_overtime_salary",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=20, verbose_name="Taxable Overtime Salary"
            ),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="total_position_income",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=20, verbose_name="Total Position Income"
            ),
        ),
    ]
