# Generated by Django 5.2.6 on 2025-12-31 03:24

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0020_add_new_salary_calculation_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payrollslip",
            name="holiday_overtime_hours",
        ),
        migrations.RemoveField(
            model_name="payrollslip",
            name="saturday_inweek_overtime_hours",
        ),
        migrations.RemoveField(
            model_name="payrollslip",
            name="sunday_overtime_hours",
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="tc1_overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="TC1 Overtime Hours (Weekday & Sat)",
            ),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="tc2_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="TC2 Overtime Hours (Sunday)"
            ),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="tc3_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8, verbose_name="TC3 Overtime Hours (Holiday)"
            ),
        ),
    ]
