# Generated by Django 5.2.6 on 2025-12-31 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0018_rename_overtime_fields_in_payroll_slip"),
        ("payroll", "0020_add_new_salary_calculation_fields"),
    ]

    operations = []
