# Generated by Django 5.2.6 on 2025-12-31 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0030_remove_department_assignment_source_add_department"),
        ("payroll", "0021_remove_payrollslip_holiday_overtime_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeekpiassessment",
            name="department_assignment_source",
        ),
        migrations.AddField(
            model_name="employeekpiassessment",
            name="department_snapshot",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee's department when KPI period was generated (snapshot)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_kpi_assessments",
                to="hrm.department",
                verbose_name="Department Snapshot",
            ),
        ),
    ]
