# Generated by Django 5.2.6 on 2025-12-31 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrm", "0031_alter_employeemonthlytimesheet_early_leaving_minutes_and_more"),
        ("payroll", "0022_remove_employeekpiassessment_department_assignment_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRevenueReportFlatModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(verbose_name="Report date")),
                (
                    "need_refresh",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this report needs to be recalculated by batch task",
                        verbose_name="Needs refresh",
                    ),
                ),
                (
                    "month_key",
                    models.CharField(help_text="Month in MM/YYYY format", max_length=10, verbose_name="Month key"),
                ),
                ("total_transactions", models.IntegerField(default=0, verbose_name="Total transactions")),
                ("total_revenue", models.BigIntegerField(default=0, verbose_name="Total revenue")),
                (
                    "total_sales_employees",
                    models.IntegerField(
                        default=0,
                        help_text="Active sales employees at end of month",
                        verbose_name="Total sales employees",
                    ),
                ),
                (
                    "employees_with_revenue",
                    models.IntegerField(
                        default=0,
                        help_text="Count of employees who generated revenue in the month",
                        verbose_name="Employees with revenue",
                    ),
                ),
                (
                    "target_per_employee",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000000.0,
                        help_text="Fixed target per employee (50,000,000 VND)",
                        max_digits=15,
                        verbose_name="Target per employee",
                    ),
                ),
                (
                    "total_kpi_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total sales employees * Target per employee",
                        max_digits=20,
                        verbose_name="Total KPI target",
                    ),
                ),
                (
                    "revenue_vs_target_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue / Total target * 100",
                        max_digits=7,
                        verbose_name="Revenue vs target (%)",
                    ),
                ),
                (
                    "employee_with_revenue_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Employees with revenue / Total sales employees * 100",
                        max_digits=7,
                        verbose_name="Employee with revenue (%)",
                    ),
                ),
                (
                    "avg_revenue_per_employee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue / Total sales employees",
                        max_digits=20,
                        verbose_name="Average revenue per employee",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.block",
                        verbose_name="Block",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Revenue Report",
                "verbose_name_plural": "Sales Revenue Reports",
                "db_table": "payroll_sales_revenue_report",
                "indexes": [
                    models.Index(fields=["report_date"], name="payroll_sal_report__39e89b_idx"),
                    models.Index(fields=["branch", "block", "department"], name="payroll_sal_branch__6b3124_idx"),
                    models.Index(fields=["month_key"], name="payroll_sal_month_k_c3a1ee_idx"),
                ],
                "unique_together": {("report_date", "branch", "block", "department")},
            },
        ),
    ]
