# Generated by Django 5.2.6 on 2026-01-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0023_salesrevenuereportflatmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollslip",
            name="employee_email",
            field=models.EmailField(blank=True, default="", max_length=254, verbose_name="Employee Email"),
        ),
        migrations.AddField(
            model_name="payrollslip",
            name="tax_code",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Tax Code"),
        ),
    ]
