# Generated by Django 5.2.6 on 2026-01-06 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0024_add_tax_code_to_payroll_slip"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrevenue",
            name="kpi_target",
            field=models.BigIntegerField(
                default=50000000,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="KPI Target",
            ),
        ),
    ]
