# Generated by Django 5.2.6 on 2026-01-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0026_alter_departmentkpiassessment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollslip",
            name="need_resend_email",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Flag if email needs to be resent",
                verbose_name="Need Resend Email",
            ),
        ),
    ]
