# Generated by Django 5.2.6 on 2026-01-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0027_change_need_resend_email_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeekpiassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Mới"),
                    ("waiting_manager", "Chờ đánh giá"),
                    ("completed", "Đã hoàn thành"),
                ],
                default="new",
                help_text="Assessment status (system-managed)",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
