# Generated by Django 5.2.6 on 2026-01-08 07:03

from django.db import migrations, models

import libs.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=200, verbose_name="Project name")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Project code"),
                ),
                (
                    "address",
                    libs.models.fields.SafeTextField(blank=True, verbose_name="Address"),
                ),
                (
                    "description",
                    libs.models.fields.SafeTextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "realestate_project",
                "ordering": ["name"],
            },
        ),
    ]
