# Generated by Django 5.2.6 on 2026-01-08 07:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for tracking the background job",
                        max_length=255,
                        null=True,
                        verbose_name="Celery task ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        help_text="Current status of the import job",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_rows",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of rows to process",
                        null=True,
                        verbose_name="Total rows",
                    ),
                ),
                (
                    "processed_rows",
                    models.IntegerField(
                        default=0,
                        help_text="Number of rows processed",
                        verbose_name="Processed rows",
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of rows processed successfully",
                        verbose_name="Success count",
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of rows that failed processing",
                        verbose_name="Failure count",
                    ),
                ),
                (
                    "percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of completion (0-100)",
                        null=True,
                        verbose_name="Percentage",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="Import options including handler path and other settings",
                        null=True,
                        verbose_name="Options",
                    ),
                ),
                (
                    "result_success_s3_path",
                    models.CharField(
                        blank=True,
                        help_text="S3 path for successfully processed rows file",
                        max_length=1024,
                        null=True,
                        verbose_name="Success result S3 path",
                    ),
                ),
                (
                    "result_failed_s3_path",
                    models.CharField(
                        blank=True,
                        help_text="S3 path for failed rows file",
                        max_length=1024,
                        null=True,
                        verbose_name="Failed result S3 path",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the import failed",
                        null=True,
                        verbose_name="Error message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the import job was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the import job started processing",
                        null=True,
                        verbose_name="Started at",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the import job finished",
                        null=True,
                        verbose_name="Finished at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the import",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="Source file for import",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_jobs",
                        to="files.filemodel",
                        verbose_name="File",
                    ),
                ),
                (
                    "result_failed_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="FileModel record for failed rows",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_failed_for",
                        to="files.filemodel",
                        verbose_name="Failed result file",
                    ),
                ),
                (
                    "result_success_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="FileModel record for successfully processed rows",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_success_for",
                        to="files.filemodel",
                        verbose_name="Success result file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Job",
                "verbose_name_plural": "Import Jobs",
                "db_table": "imports_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "status"],
                        name="imports_job_created_41d9da_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="imports_job_status_6af8c2_idx",
                    ),
                    models.Index(fields=["celery_task_id"], name="imports_job_celery__c9a03b_idx"),
                ],
            },
        ),
    ]
