# Generated by Django 5.2.6 on 2025-10-16 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        help_text="File purpose category (e.g., job_description, invoice, employee_cv)",
                        max_length=100,
                        verbose_name="Purpose",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original name of the uploaded file", max_length=255, verbose_name="File name"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="S3 path where the file is stored", max_length=500, verbose_name="File path"
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True, verbose_name="File size"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="MD5 checksum for file integrity verification",
                        max_length=64,
                        null=True,
                        verbose_name="Checksum",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, help_text="Whether the file upload has been confirmed", verbose_name="Confirmed"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="Object ID")),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "db_table": "files_file",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["purpose", "is_confirmed"], name="files_file_purpose_ec0d83_idx"),
                    models.Index(fields=["content_type", "object_id"], name="files_file_content_20a48a_idx"),
                ],
            },
        ),
    ]
