name: Deploy to Test Environment

on:
  push:
    branches: [ master ]

jobs:
  deploy-test:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Deploy to EC2 Test Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USERNAME }}
        key: ${{ secrets.TEST_SSH_KEY }}
        script: |
          # Navigate to application directory
          cd /home/ubuntu/maivietland/backend
          
          # Pull latest changes from master
          git pull origin master
          
          # Activate virtual environment and install dependencies
          source .venv/bin/activate
          poetry install --no-interaction --no-root
          
          # Use existing .env file configured on server
          # (No environment variable replacement - managed on server)
          
          # Run database migrations
          python manage.py migrate
          
          # Update supervisor configuration and restart gunicorn workers
          sudo supervisorctl reread
          sudo supervisorctl update
          sudo supervisorctl restart maivietland-api
          
          # Reload nginx configuration
          sudo nginx -t && sudo nginx -s reload

    - name: Health Check
      run: |
        # Health check for EC2 test environment
        echo "Performing health check on test environment..."
        sleep 10  # Wait for services to start
        
        # Check if the application is responding
        curl -f ${{ secrets.TEST_APP_URL }}/health/ || echo "Health check endpoint not available"
        
        echo "Health check completed"