# Generated by Django 5.2.6 on 2026-01-08 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "verb",
                    models.CharField(
                        help_text="The action that was performed",
                        max_length=255,
                        verbose_name="Verb",
                    ),
                ),
                (
                    "target_object_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Target object ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional custom message for the notification",
                        verbose_name="Message",
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the notification has been read",
                        verbose_name="Read",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional JSON data to provide context for rendering",
                        verbose_name="Extra data",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("firebase", "Firebase"),
                            ("email", "Email"),
                            ("both", "Both"),
                        ],
                        default="firebase",
                        help_text="How the notification should be delivered",
                        max_length=20,
                        verbose_name="Delivery method",
                    ),
                ),
                (
                    "target_client",
                    models.CharField(
                        blank=True,
                        choices=[("mobile", "Mobile"), ("web", "Web")],
                        help_text="Specific client to send the notification to. If null, send to all active devices.",
                        max_length=20,
                        null=True,
                        verbose_name="Target client",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="The user who triggered the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_as_actor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user receiving the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_targets",
                        to="contenttypes.contenttype",
                        verbose_name="Target content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                    models.Index(
                        fields=["recipient", "read", "-created_at"],
                        name="notificatio_recipie_b41e6c_idx",
                    ),
                ],
            },
        ),
    ]
