# Generated by Django 5.2.6 on 2025-12-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_client",
            field=models.CharField(
                blank=True,
                choices=[("mobile", "Mobile"), ("web", "Web")],
                help_text="Specific client to send the notification to. If null, send to all active devices.",
                max_length=20,
                null=True,
                verbose_name="Target client",
            ),
        ),
    ]
