# Generated by Django 5.2.6 on 2025-12-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_role_options"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_device",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific device to send the notification to. If null, send to all active devices.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.userdevice",
                verbose_name="Target device",
            ),
        ),
    ]
